### ISSUE TITLE
Unable login with a LDAP user - Jumpcloud - "Unable to validate user credentials!"

### ISSUE THREAD

**Issue by maorweissSV** [grokability/snipe-it#10013]
#### Please confirm you have done the following before posting your bug report:

- [V] I have enabled debug mode 
- [V] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After successfully LDAP sync test I'm getting the "Unable to validate user credentials!" error.
I'm using the [JumpCloud configuration settings for LDAP sync](https://support.jumpcloud.com/support/s/article/Configuring-SNIPE-IT-to-use-JumpCloud-s-LDAP-as-a-Service) and it's working properly without user login.

**To Reproduce**
1. Go to 'Admin'
2. Click on LDAP'
3. Scroll down to 'Test LDAP Login'
4. See the error "Unable to validate user credentials!"

**Expected behavior**
Successful log messages and successful login of the users.

**Screenshots**
![image](https://user-images.githubusercontent.com/83959332/131494265-6f1899fc-99ab-44e9-a659-86e7ff4ba7bf.png)
![image](https://user-images.githubusercontent.com/83959332/131494358-f7b6fdc7-6537-426e-af27-ca6f112d5fa6.png)
![image](https://user-images.githubusercontent.com/83959332/131495013-0b5aacbf-39f6-4e47-809a-a48357804baa.png)
![image](https://user-images.githubusercontent.com/83959332/131495077-c7374b2b-87d1-4c33-9279-76833e55e059.png)

**Server (please complete the following information):**
 - Snipe-IT Version : V5.1.8
 - OS: Ubuntu 20.04.3 LTS
 - Web Server: nginx/1.18.0
 - PHP Version : PHP 7.4.22 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome 
 - Version : 92.0.4515.159 64-bit

**Comment by uberbrady** [comment]
Snipe-IT performs logins by doing an LDAP bind *as* your user - does your user have bind permissions? I've definitely seen that on Jumpcloud before.

Under "User Security Settings and Permissions" - check the box for "Enable as LDAP Bind DN".

Does that work any better?

**Comment by maorweissSV** [comment]
Thank you @uberbrady  for the reply :)
I've configured my user as you suggested on JumpCloud 5 hours ago and I've resync LDAP with the `sudo artisan snipeit:ldap-sync ` command right now. 

Unfurthently, I still see the same `Base table or view not found` log error when I'm trying to test the LDAP credentials again.
![image](https://user-images.githubusercontent.com/83959332/131654969-1c1157d5-7d14-46c4-b3d8-bc28d117cae5.png)


Is there any other idea of what can I do to solve this issue?

**Comment by uberbrady** [comment]
That sounds like possible missing migrations? What happens if you run `php artisan migrate` - paste your output here if you wouldn't mind, especially so if it errors (of course, if it fixes it, then you can just close the issue and say that that fixed it :) )

**Comment by maorweissSV** [comment]
Sorry... Nothing to migrate.
![image](https://user-images.githubusercontent.com/83959332/131793561-fc1306ab-c239-4e51-998c-8cfab22ff59a.png)

**Comment by maorweissSV** [comment]
Same issue, but I'm open to new ideas :)

**Comment by uberbrady** [comment]
Any way you can get us more of that error message? "Base table or view not found" is probably not a particularly good situation for us to be in, and we'll probably need to fix it, if we can figure out what 'it' is.

**Comment by maorweissSV** [comment]
Thanks @uberbrady ,

The full error message is: 
`[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeitdb.users' doesn't exist at /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79)
[stacktrace]
#0 /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(79): PDO->prepare()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Doctrine\\DBAL\\Driver\\PDOConnection->prepare()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Connection->select()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2147): Illuminate\\Database\\Query\\Builder->runSelect()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2619): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2148): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(546): Illuminate\\Database\\Query\\Builder->get()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(530): Illuminate\\Database\\Eloquent\\Builder->getModels()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(52): Illuminate\\Database\\Eloquent\\Builder->first()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(139): Illuminate\\Auth\\EloquentUserProvider->retrieveById()
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\SessionGuard->user()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(307): Illuminate\\Auth\\SessionGuard->check()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Auth\\AuthManager->__call()
#17 /var/www/snipeit/app/Http/Middleware/CheckForDebug.php(21): Illuminate\\Support\\Facades\\Facade::__callStatic()
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#19 /var/www/snipeit/app/Http/Middleware/CheckForSetup.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#21 /var/www/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#29 /var/www/snipeit/app/Http/Middleware/NoSessionStore.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\NoSessionStore->handle()
#31 /var/www/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#35 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#36 /var/www/snipeit/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
#37 {main}
"}
`.

My table name is 'snipeitdb'. As you can see, it should work.
![image](https://user-images.githubusercontent.com/83959332/132841929-73c74092-7286-4883-8535-1d6da868206e.png)

**Comment by uberbrady** [comment]
Somehow, your Snipe-IT environment can't see your database, or it's maybe looking at the wrong one? If your Snipe-IT web application works, you should be able to run stuff similarly via the command-line.

Try `php artisan list` and make sure you get output. Try `php artisan tinker` and then try something like `$s=App\Models\Setting::first()` - that should give you a dump of your settings, which are stored in the database.

This way we can at least confirm that your command-line environment can at least connect to your database the same way the web application can.

**Comment by maorweissSV** [comment]
Thanks for the support, @uberbrady !
After checking the DB connection by your instructions, I've got this.

![image](https://user-images.githubusercontent.com/83959332/133214505-bda76401-ac1c-4442-a00c-1ac7626df129.png)

Is there something particular that we need from this output?

**Comment by snipe** [comment]
Hi there - I know this is a pretty old issue, but I wanted to check and see if you ever got this resolved? If so, can you please close the ticket? If not, can you update us on what version of Snipe-IT you're currently using, so we can see if it's still an issue on latest?

:) Thanks!

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
