### ISSUE TITLE
Switching to English when German was configured in .env file previously

### ISSUE THREAD

**Issue by FriendlyBanter** [grokability/snipe-it#10116]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Originally set APP_LOCALE in .env to 'de'. UI was displayed in German correctly.

Then set language to English (US) through web UI. Some (most) parts were still shown in German.

Went into .env file and changed locale there to 'en'. Restarted web server (IIS) and ran 'php artisan config:clear'.

No change - still most parts are in German.

### Reproduction steps

1. Set locale to 'de' in .env during initial setup/configuration.
2. Set language to 'English (US)' through web UI.
3. Set locale to 'en' in .env.

### Expected behavior

Expected to change language to English in all parts.

### Snipe-IT Version

v5.2.0 build 6339 (g14a8baeca)

### Operating System

Windows Server 2019 Version 1809 Build 17763.2145

### Web Server

IIS 10.0.17763.1

### PHP Version

8.0.9

### Operating System

Windows 10 Version 21H1 Build 19043.1237

### Browser

MS Edge 

### Version

93.0.961.52 (Official build) (64-bit)

### Error messages

```shell
[2021-09-09 09:12:46] production.ERROR: file_get_contents(C:\inetpub\wwwroot\snipe-it\.env): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_get_contents(C:\\inetpub\\wwwroot\\snipe-it\\.env): Failed to open stream: No such file or directory at C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\KeyGenerateCommand.php:96)
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(96): file_get_contents()
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(80): Illuminate\Foundation\Console\KeyGenerateCommand->writeNewEnvironmentFileWith()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(45): Illuminate\Foundation\Console\KeyGenerateCommand->setKeyInEnvironmentFile()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Foundation\Console\KeyGenerateCommand->handle()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#10 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#12 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#13 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#17 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#18 {main}  

ERROR
[2021-09-09 09:12:46] production.ERROR: ErrorException: file_get_contents(C:\inetpub\wwwroot\snipe-it\.env): Failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php:96
```

**Comment by snipe** [comment]
When you go to your profile preferences, what language does it have set?

**Comment by FriendlyBanter** [comment]
🤦‍♂️

That was it. Never been so embarrassed.

Apologies if I wasted anyone's time.

**Comment by snipe** [comment]
No worries at all - this is a complicated system, no need to be embarrassed. We’re just glad you’re sorted out. :)

**Comment by snipe** [comment]
We have three different tiers of localization- it’s not your fault, I promise.
