### ISSUE TITLE
keeps using SMTP instead of sendmail

### ISSUE THREAD

**Issue by brandhout** [grokability/snipe-it#10214]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I cannot send a test mail from the installation. I have declared sendmail in my .env but snipe-it keeps sending via smtp, which is not available in my environment. This makes me hesitant to continue, I need mail functionality. 

`
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=sendmail
#MAIL_HOST=localhost
#MAIL_PORT=587
#MAIL_USERNAME=YOURUSERNAME
#MAIL_PASSWORD=YOURPASSWORD
#MAIL_ENCRYPTION=null
MAIL_FROM_ADDR='_Some adress_'
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR='_Some adress_'
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'
`

It also doesn't work with all variables uncommented. I can see the SMTP functionality being called in the syslog (postfix).

### Reproduction steps

1. Install the latest version of Snipe-It
2. Open the preflight
3. Send test-mail
...

### Expected behavior

snipe-it has to send email from /usr/sbin/sendmail

### Screenshots

![Screenshot 2021-10-21 at 18-03-35 Create a User Snipe-IT Setup](https://user-images.githubusercontent.com/23652365/138315275-a5de4afc-4dc0-4599-bbfb-86d6cce2c031.png)

### Snipe-IT Version

5.3.0

### Operating System

Centos 8

### Web Server

Apache

### PHP Version

7.4

### Error messages

```shell
[2021-10-21 17:53:20] production.ERROR: Expected response code 220 but got an empty response {"exception":"[object] (Swift_TransportException(code: 0): Expected response code 220 but got an empty response at /var/www/clients/client0/web22/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:447)
#0 /var/www/clients/client0/web22/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(360): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 /var/www/clients/client0/web22/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 /var/www/clients/client0/web22/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/clients/client0/web22/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_SendmailTransport->start()
```

**Comment by snipe** [comment]
Hi @brandhout - this is very likely not an issue on our end. People use all sorts of mail systems to send notifications, and they all work. (This is built into the framework we use, I don't claim any credit for that.) I'd check to make sure you've cleared your config cache (`php artisan config:clear`)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
