### ISSUE TITLE
Unable to add asset model (v6.0.0-RC-1)

### ISSUE THREAD

**Issue by michaelredus** [grokability/snipe-it#10536]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When clicking the "Create New" button on the view models page, I get an error 500. When in debug mode, the error is: Attempt to read property "fieldset_id" on null (View: C:\inetpub\wwwroot\snipe6\resources\views\models\edit.blade.php)

### Reproduction steps

1. Log in to Snipe-IT, go to Settings > Asset Models
2. Click "Create New" button.
...

### Expected behavior

The add an asset page opens.

### Screenshots

![image](https://user-images.githubusercontent.com/98006216/150220283-c0da0a70-bb53-4c4d-8354-71600d14b9b4.png)
![image](https://user-images.githubusercontent.com/98006216/150220432-0ec97160-ef04-43c8-890c-b10287674781.png)

### Snipe-IT Version

6.0.0-RC-1

### Operating System

Windows

### Web Server

IIS 10

### PHP Version

8.0

### Operating System

Windows 10

### Browser

Google Chrome

### Version

97

### Error messages

```shell
**php -m output:**
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**From the debug page:**
ErrorException: Attempt to read property "fieldset_id" on null in C:\inetpub\wwwroot\snipe6\app\Http\Livewire\CustomFieldSetDefaultValuesForModel.php:21
Stack trace:
#0 C:\inetpub\wwwroot\snipe6\app\Http\Livewire\CustomFieldSetDefaultValuesForModel.php(21): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Http\Livewire\CustomFieldSetDefaultValuesForModel->mount()
#2 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#4 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#5 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\LifecycleManager.php(114): Illuminate\Container\BoundMethod::call()
#6 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\LivewireManager.php(104): Livewire\LifecycleManager->mount()
#7 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Livewire\LivewireManager->mount()
#8 C:\inetpub\wwwroot\snipe6\storage\framework\views\1f4bd7a914ef70f77147b95492b13f5df0885730.php(31): Illuminate\Support\Facades\Facade::__callStatic()
#9 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(107): require('...')
#10 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#11 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#12 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(35): Illuminate\View\Engines\PhpEngine->evaluatePath()
#13 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(61): Livewire\CompilerEngineForIgnition->evaluatePath()
#14 C:\inetpub\wwwroot\snipe6\vendor\facade\ignition\src\Views\Engines\CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get()
#15 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\View.php(139): Facade\Ignition\Views\Engines\CompilerEngine->get()
#16 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
#17 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#18 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#19 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response->setContent()
#20 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(794): Illuminate\Http\Response->__construct()
#21 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(763): Illuminate\Routing\Router::toResponse()
#22 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(695): Illuminate\Routing\Router->prepareResponse()
#23 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#24 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#26 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#28 C:\inetpub\wwwroot\snipe6\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#30 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#32 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#34 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#36 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#38 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#40 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(697): Illuminate\Pipeline\Pipeline->then()
#42 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(672): Illuminate\Routing\Router->runRouteWithinStack()
#43 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(636): Illuminate\Routing\Router->runRoute()
#44 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->dispatchToRoute()
#45 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch()
#46 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#47 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#49 C:\inetpub\wwwroot\snipe6\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#51 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#53 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#55 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#57 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#58 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#60 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#62 C:\inetpub\wwwroot\snipe6\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#64 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#66 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#68 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#69 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#71 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#73 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#74 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#75 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#76 C:\inetpub\wwwroot\snipe6\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#77 {main}

Next Facade\Ignition\Exceptions\ViewException: Attempt to read property "fieldset_id" on null (View: C:\inetpub\wwwroot\snipe6\resources\views\models\edit.blade.php) in C:\inetpub\wwwroot\snipe6\app\Http\Livewire\CustomFieldSetDefaultValuesForModel.php:21
Stack trace:
#0 C:\inetpub\wwwroot\snipe6\app\Http\Livewire\CustomFieldSetDefaultValuesForModel.php(21): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Http\Livewire\CustomFieldSetDefaultValuesForModel->mount()
#2 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#4 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#5 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\LifecycleManager.php(114): Illuminate\Container\BoundMethod::call()
#6 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\LivewireManager.php(104): Livewire\LifecycleManager->mount()
#7 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Livewire\LivewireManager->mount()
#8 C:\inetpub\wwwroot\snipe6\resources\views/models/edit.blade.php(39): Illuminate\Support\Facades\Facade::__callStatic()
#9 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(107): require('...')
#10 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#11 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#12 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(35): Illuminate\View\Engines\PhpEngine->evaluatePath()
#13 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(61): Livewire\CompilerEngineForIgnition->evaluatePath()
#14 C:\inetpub\wwwroot\snipe6\vendor\facade\ignition\src\Views\Engines\CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get()
#15 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\View.php(139): Facade\Ignition\Views\Engines\CompilerEngine->get()
#16 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
#17 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#18 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#19 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response->setContent()
#20 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(794): Illuminate\Http\Response->__construct()
#21 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(763): Illuminate\Routing\Router::toResponse()
#22 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(695): Illuminate\Routing\Router->prepareResponse()
#23 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#24 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#26 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#28 C:\inetpub\wwwroot\snipe6\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#30 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#32 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#34 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#36 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#38 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#40 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(697): Illuminate\Pipeline\Pipeline->then()
#42 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(672): Illuminate\Routing\Router->runRouteWithinStack()
#43 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(636): Illuminate\Routing\Router->runRoute()
#44 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->dispatchToRoute()
#45 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch()
#46 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#47 C:\inetpub\wwwroot\snipe6\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#49 C:\inetpub\wwwroot\snipe6\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#51 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#53 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#55 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#57 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#58 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#60 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#62 C:\inetpub\wwwroot\snipe6\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#64 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#66 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#68 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#69 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#71 C:\inetpub\wwwroot\snipe6\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#73 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#74 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#75 C:\inetpub\wwwroot\snipe6\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#76 C:\inetpub\wwwroot\snipe6\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#77 {main}
```

### Additional context

This is a fresh install to test out v6.0.0. Snipe-IT was installed manually, following the [installation guide](https://snipe-it.readme.io/docs/installation). So far, I have enabled LDAP authentication and added one manufacturer with no error. I did edit the models table just to see if it did anything (the model added via the database did show up) but I have since rolled back to a snapshot from before I touched the database.

I have also ran the below commands, mentioned on the [common issues](https://snipe-it.readme.io/docs/common-issues) page:
composer dump-autoload; php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan debugbar:clear; php artisan event:clear; php artisan view:clear; php artisan optimize:clear; php artisan clear-compiled

**Comment by uberbrady** [comment]
I bet I messed something up in the Livewire changes; I'm seeing that specific controller pop up. I'll see if I can reproduce, then get it fixed.

Thank you *SO* much for helping test our v6 RC! It really helps us get to a place where our 6.0.0 release will be really solid and reliable!

**Comment by snipe** [comment]
@michaelredus  TYSM for kicking the tires on the RC! We'll have a fix out for you shortly. <3

**Comment by michaelredus** [comment]
@uberbrady @snipe Not a problem at all, Snipe-IT is great software and I'm very excited to get to testing out version 6! Thank you both for all of your hard work on it.

**Comment by snipe** [comment]
We're on this - I'm having a hard time reproducing it, but we'll get it fixed.

**Comment by inietov** [comment]
I encounter this issue too
The commit that fix it is in this PR. Sorry, I don't remember to mention it in the Stand Up https://github.com/snipe/snipe-it/pull/10522

**Comment by inietov** [comment]
Ok, I take out the condition that removes the functionality and added an early return if no `model_id` is passed to the class that charges the livewire, (I think?)
