### ISSUE TITLE
Unable to associate custom fields with a fieldset. (v6.0.0-RC-1)

### ISSUE THREAD

**Issue by michaelredus** [grokability/snipe-it#10600]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When attempting to add custom fields to a custom fieldset, I receive an HTTP 500 error.

### Reproduction steps

1. Create some custom fields (or don't and just use the default MAC address field).
2. Create a custom fieldset.
3. Edit the custom fieldset, and try to add a custom field.
4. HTTP 500
...

### Expected behavior

Custom fieldset is added and available for use on models.

### Screenshots

![image](https://user-images.githubusercontent.com/98006216/152178226-19c0f0b0-1711-4372-8aba-9b4ce31ee274.png)

### Snipe-IT Version

v6.0.0-RC-1

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

8.0.0

### Operating System

Windows 10 20H2

### Browser

Google Chrome

### Version

97.0.4692.99

### Error messages

```shell
ERROR MESSAGE:
BadMethodCallException
Method App\Http\Controllers\CustomFieldsController::associate does not exist.

PHP -M:
PS C:\inetpub\wwwroot> php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sodium
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

STACK TRACE:
BadMethodCallException: Method App\Http\Controllers\CustomFieldsController::associate does not exist. in C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:68
Stack trace:
#0 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Illuminate\Routing\Controller->__call()
#1 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#2 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#3 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#4 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(695): Illuminate\Routing\Route->run()
#5 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#7 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#8 C:\inetpub\wwwroot\app\Http\Middleware\AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#10 C:\inetpub\wwwroot\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#12 C:\inetpub\wwwroot\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#14 C:\inetpub\wwwroot\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#16 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#18 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#20 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#22 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(697): Illuminate\Pipeline\Pipeline->then()
#24 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(672): Illuminate\Routing\Router->runRouteWithinStack()
#25 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(636): Illuminate\Routing\Router->runRoute()
#26 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->dispatchToRoute()
#27 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch()
#28 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#29 C:\inetpub\wwwroot\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#31 C:\inetpub\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#33 C:\inetpub\wwwroot\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#35 C:\inetpub\wwwroot\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#37 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#39 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#40 C:\inetpub\wwwroot\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#42 C:\inetpub\wwwroot\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#44 C:\inetpub\wwwroot\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#46 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#48 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#50 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#51 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#53 C:\inetpub\wwwroot\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#55 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#57 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#58 C:\inetpub\wwwroot\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#59 {main}
```

### Additional context

This is a fresh install for testing, running on Windows with IIS. I installed manually following the official instructions and ran in to no errors during that process. I haven't tried very many troubleshooting steps, and have not touched the database.

**Comment by inietov** [comment]
Hello there!! We have a [commit](https://github.com/snipe/snipe-it/commit/fcd203f4dc6b299d9593d2c0824311ad1404a5fe) that fix this. The new RC is here: https://github.com/snipe/snipe-it/releases/tag/v6.0.0-RC-2.

If you can help us to confirm that this is working now on the new version we will really grateful. 

Have a nice day!! 

<blockquote><img src="https://opengraph.githubassets.com/61ceb67897bf30ab3515e918ad69497d8eb18b695b38fd75c5ad0e8cb40c38e6/snipe/snipe-it/releases/tag/v6.0.0-RC-2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v6.0.0-RC-2">Release v6.0.0-RC-2 · snipe/snipe-it</a></strong></div><div>⚠️  IMPORTANT: This version of Snipe-IT REQUIRES PHP 7.4 or greater.
Thanks to our amazing community of testers, we're ready to release RC-2 of Snipe-IT v6! Unlike v5's release, I think this one wo...</div></blockquote>

**Comment by michaelredus** [comment]
That did it, thanks! I found this issue yesterday right before leaving for the day, it looks like RC2 was released shortly after that and I didn't notice this morning before submitting the issue.

**Comment by inietov** [comment]
No problem, glad it got sorted out. 
And thank YOU to report your observed issues!!
