### ISSUE TITLE
Unable to update SnipeIT with php upgrade.php

### ISSUE THREAD

**Issue by ITRich01** [grokability/snipe-it#10676]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after running upgrade.php the script reports success, however the versions number does not change and no files were modified. I have checked the common issues page it recommends doing a git pull but this fails with not a git repo or any parent of the directories. I noticed this also came up when I was running upgrade.php   output of that below. 

I have used php upgrade in the past to get on to version 5.3.8 without issue. (my current version)   
PHP is version 7.4.27
OS: windows server with IIS. 
Snipe-it is currently ruining as expected.

PHP upgrade output:

PS C:\inetpub\wwwroot\snipeit> php upgrade.php
Skipping user check as it is not supported on Windows or Posix is not installed on this server.
--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER!
--------------------------------------------------------

This script will attempt to:

- check your PHP version and extension requirements
- do a git pull to bring you to the latest version
- run composer install to get your vendors up to date
- run migrations to get your schema up to date
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements:
--------------------------------------------------------

Current PHP version: (7.4.27) is at least 7.2.5 - continuing...
FYI: The php.ini used by this PHP is: C:\Program Files\PHP\php.ini

Checking Required PHP extensions...

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified.
.
#0 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully()
#1 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul()
#2 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(252): Spatie\DbDumper\Databases\MySql->dumpToFile()
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}()
#4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Support\Collection.php(638): array_map()
#5 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(255): Illuminate\Support\Collection->map()
#6 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(169): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(145): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#10 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#12 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#13 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#14 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#15 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#16 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#17 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run()
#18 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Concerns\CallsCommands.php(56): Spatie\Backup\Commands\BaseCommand->run()
#19 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Concerns\CallsCommands.php(28): Illuminate\Console\Command->runCommand()
#20 C:\inetpub\wwwroot\snipeit\app\Console\Commands\SystemBackup.php(42): Illuminate\Console\Command->call()
#21 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SystemBackup->handle()
#22 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#24 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#25 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#26 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#27 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#28 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#29 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#30 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#31 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#32 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#33 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#34 C:\inetpub\wwwroot\snipeit\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#35 {main}
Backup failed because: The dump process failed with exitcode 1 : General error : The system cannot find the path specified.
.

--------------------------------------------------------
STEP 3: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- -- --
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
65 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Generating optimized autoload files
Generated optimized autoload files containing 6019 classes

--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use
your upgraded Snipe-IT!
--------------------------------------------------------

PS C:\inetpub\wwwroot\snipeit>

 

### Reproduction steps

1. run php upgrade.php
2. folloed instructions on clearing cache
3. checked version number
3.checked the files in snipe it 
...

### Expected behavior

upgrade.php should update SnipeIT 

### Snipe-IT Version

5.3.8

### Operating System

windows 

### Web Server

IIS

### PHP Version

7.4.27

### Operating System

windows 10

### Browser

Edge/ Chrome

### Version

98

### Error messages

```shell
none
```

**Comment by ITRich01** [comment]
This is now working after following the  Switching to a Git Install,  even though I'm pretty sure I did this when I installed.
