### ISSUE TITLE
Error 403 on Maintenance entry

### ISSUE THREAD

**Issue by CVB2000** [grokability/snipe-it#10711]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

User who is not a super admin cannot enter a maintenance report on assets.

### Reproduction steps

1. Enable user as super user
2. Create maintenance report https://url/hardware/maintenances/create?asset_id=1
3. Working fine
4. Remove super user rights, grant all different rights
5. Error 403 on calling https://url/hardware/maintenances/create?asset_id=1

### Expected behavior

There should be a specific right to grant without permitting everything to user.

### Snipe-IT Version

5.3.10

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.28

### Error messages

```shell
This action is unauthorized./var/www/asset/vendor/laravel/framework/src/Illuminate/Auth/Access/Response.php#119Illuminate\Auth\Access\AuthorizationException

        public function authorize()
        {
            if ($this->denied()) {
                throw (new AuthorizationException($this->message(), $this->code()))
                            ->setResponse($this);
            }


    #0 /var/www/asset/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php(318): Illuminate\Auth\Access\Response->authorize()
    #1 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php(23): Illuminate\Auth\Access\Gate->authorize()
    #2 /var/www/asset/app/Http/Controllers/AssetMaintenancesController.php(70): App\Http\Controllers\Controller->authorize()
    #3 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\AssetMaintenancesController->create()
    #4 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
    #5 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
    #6 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
    #7 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
    #8 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
    #9 /var/www/asset/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #10 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle()
    #11 /var/www/asset/app/Http/Middleware/AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #12 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle()
    #13 /var/www/asset/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #14 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
    #15 /var/www/asset/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #16 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle()
    #17 /var/www/asset/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #18 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckLocale->handle()
    #19 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #20 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
    #21 /var/www/asset/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #22 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
    #23 /var/www/asset/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #24 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
    #25 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #26 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
    #27 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
    #28 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
    #29 /var/www/asset/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
    #30 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch()
    #31 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
    #32 /var/www/asset/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #33 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
    #34 /var/www/asset/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #35 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\PreventBackHistory->handle()
    #36 /var/www/asset/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #37 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle()
    #38 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #39 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
    #40 /var/www/asset/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #41 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle()
    #42 /var/www/asset/app/Http/Middleware/CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #43 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle()
    #44 /var/www/asset/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #45 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
    #46 /var/www/asset/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #47 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
    #48 /var/www/asset/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #49 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
    #50 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #51 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
    #52 /var/www/asset/app/Http/Middleware/NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #53 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle()
    #54 /var/www/asset/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #55 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle()
    #56 /var/www/asset/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #57 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
    #58 /var/www/asset/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
    #59 /var/www/asset/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
    #60 {main}
```

### Additional context

Fresh install, installation via git, no data changed manually.

**Comment by snipe** [comment]
Please upgrade to latest. This was fixed in [5.4.1](https://github.com/snipe/snipe-it/releases/tag/v5.4.1).
