### ISSUE TITLE
Error 500 after upgrading from 5.3.10 to 5.4.0

### ISSUE THREAD

**Issue by alexanderd24** [grokability/snipe-it#10744]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I'm trying to upgrade from working 5.3.10 to 5.4.0 (with `php upgrade.php`) installation goes with errors:

```
In ProviderRepository.php line 208:
                                                   
  Class 'Barryvdh\Cors\ServiceProvider' not found  

```
next error:

`Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable`

On previous upgrades there is no such issue.
My snipe-it directory is: `/var/www/snipe-it`.
Of course upgrade script cannot write to /var/www/. 

Now I have broken installation with HTTP 500 error. 

How can I fix this?

### Reproduction steps

run `php upgrade.php` on 5.3.10

### Expected behavior

succesfull upgrade

### Snipe-IT Version

5.3.10

### Operating System

Ubuntu 20.04.4

### Web Server

Apache

### PHP Version

7.4.3

### Error messages

```shell
Relevant errors from log (when I'm trying to open web interface):

--

[2022-02-26 08:51:00] production.ERROR: Uncaught ReflectionException: Class view does not exist in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build()

--

Errors from web interface with debug on:

--

Illuminate\Contracts\Container\BindingResolutionException thrown with message "Target class [session] does not exist."

Stacktrace:
#16 Illuminate\Contracts\Container\BindingResolutionException in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
#15 ReflectionException in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
#14 ReflectionClass:__construct in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
#13 Illuminate\Container\Container:build in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
#12 Illuminate\Container\Container:resolve in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:785
#11 Illuminate\Foundation\Application:resolve in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
#10 Illuminate\Container\Container:make in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:770
#9 Illuminate\Foundation\Application:make in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:945
#8 Illuminate\Container\Container:resolveClass in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:873
#7 Illuminate\Container\Container:resolveDependencies in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:834
#6 Illuminate\Container\Container:build in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
#5 Illuminate\Container\Container:resolve in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:785
#4 Illuminate\Foundation\Application:resolve in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
#3 Illuminate\Container\Container:make in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:770
#2 Illuminate\Foundation\Application:make in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:209
#1 Illuminate\Foundation\Http\Kernel:terminateMiddleware in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:183
#0 Illuminate\Foundation\Http\Kernel:terminate in /var/www/snipe-it/public/index.php:63



#2 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\Foundation\Application->make()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facad {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught ReflectionException: Class view does not exist in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#2 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\\Foundation\\Application->make()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facad at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:805)
[stacktrace]
#0 {main}
"}
```

**Comment by uberbrady** [comment]
`composer install`

**Comment by alexanderd24** [comment]
Thank you very much, @uberbrady! That helped.
Can you explain what exactly does this command do and why should I run it?

**Comment by snipe** [comment]
Composer install installs the package dependencies that Snipe-IT uses.
