### ISSUE TITLE
 500 Server Error. Please check your server logs for more information. When attempting to Test LDAP Syncroniazation

### ISSUE THREAD

**Issue by t-dao** [grokability/snipe-it#10795]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Our LDAP has been unable to sync and bring in new users. 

![image](https://user-images.githubusercontent.com/101153426/157140726-f055722d-bddd-47bf-b725-d2adc42f3618.png)

### Reproduction steps

1.Manually initiate LDAP sync through PHP artisan or through Test LDAP Synchronization button
2.Process cycles and and then produces a 500 Server error
3.New users no longer become synced in through LDAP.

### Expected behavior

LDAP sync to update users processes and new users appear for asset assignment.

### Screenshots

![image](https://user-images.githubusercontent.com/101153426/157140743-dd0c0119-b8d6-49b7-bed1-1ab682cd5118.png)

### Snipe-IT Version

v5.3.10 build 6684 (g05c081977) 

### Operating System

Cent OS

### Web Server

Apache

### PHP Version

 7.3.25

### Error messages

```shell
[2022-03-07 14:37:18] production.ERROR: Symfony\Component\Console\Exception\RuntimeException: The "--list" option does not exist. in /opt/snipe-it/vendor/symfony/console/Input/ArgvInput.php:201
Stack trace:
#0 /opt/snipe-it/vendor/symfony/console/Input/ArgvInput.php(145): Symfony\Component\Console\Input\ArgvInput->addLongOption('list', NULL)
#1 /opt/snipe-it/vendor/symfony/console/Input/ArgvInput.php(79): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--list')
#2 /opt/snipe-it/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /opt/snipe-it/vendor/symfony/console/Command/Command.php(214): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 /opt/snipe-it/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/snipe-it/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\ListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/snipe-it/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /opt/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}  
[2022-03-07 14:37:18] production.ERROR: The "--list" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--list\" option does not exist. at /opt/snipe-it/vendor/symfony/console/Input/ArgvInput.php:201)
[stacktrace]
#0 /opt/snipe-it/vendor/symfony/console/Input/ArgvInput.php(145): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption('list', NULL)
#1 /opt/snipe-it/vendor/symfony/console/Input/ArgvInput.php(79): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption('--list')
#2 /opt/snipe-it/vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#3 /opt/snipe-it/vendor/symfony/console/Command/Command.php(214): Symfony\\Component\\Console\\Input\\Input->bind(Object(Symfony\\Component\\Console\\Input\\InputDefinition))
#4 /opt/snipe-it/vendor/symfony/console/Application.php(1009): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /opt/snipe-it/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Symfony\\Component\\Console\\Command\\ListCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /opt/snipe-it/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /opt/snipe-it/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 {main}
"}
```

### Additional context

Prior to moving to PHP 7.3 we were on PHP 7.2 and were recieving this error: 

[2022-03-02 13:28:51] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/snipe-it/app/Models/Ldap.php:293
Stack trace:
#0 {main}  
[2022-03-02 13:28:51] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) {"userId":8788,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at /opt/snipe-it/app/Models/Ldap.php:293)
[stacktrace]
#0 {main}
"} 
[2022-03-02 20:22:49] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/snipe-it/app/Models/Ldap.php:293
Stack trace:
#0 {main}  
[2022-03-02 20:22:49] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) {"userId":8788,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at /opt/snipe-it/app/Models/Ldap.php:293)

**Comment by snipe** [comment]
I'd probably start by upgrading your install. [A lot has changed since 5.3.10](https://github.com/snipe/snipe-it/compare/v5.3.10...v5.4.1).

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
