### ISSUE TITLE
Back Up Error

### ISSUE THREAD

**Issue by calvinslee** [grokability/snipe-it#10794]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi Team

Just spun up Snipe-IT on a local VM - everything is working fine so far except the back up 

### Reproduction steps

1. Login as SuperAdmin
2. Admin
3. Backup
4. Generate Backup
...

### Expected behavior

It should show back up successful? 

### Screenshots

![Screen Shot 2022-03-07 at 2 03 08 PM](https://user-images.githubusercontent.com/81184877/157125451-d1b8d4a6-8c8d-4674-9425-3a50e3c10fe5.png)

### Snipe-IT Version

v5.4.0 build 6685 (dfbff274839)

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.16

### Operating System

MacOS Monterey

### Browser

Google Chrome

### Version

Version 99.0.4844.51

### Error messages

```shell
The error code

 Error: Backup failed because The dump process failed with exitcode 1 : General error : . #0 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(252): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Support\Collection.php(638): array_map() #5 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(255): Illuminate\Support\Collection->map() #6 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(169): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(145): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #10 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #11 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #12 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #13 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call() #14 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call() #15 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute() #16 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run() #17 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run() #18 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(1009): Spatie\Backup\Commands\BaseCommand->run() #19 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand() #20 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun() #21 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run() #22 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(185): Illuminate\Console\Application->run() #23 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(273): Illuminate\Console\Application->call() #24 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #25 C:\inetpub\wwwroot\snipeit\app\Http\Controllers\SettingsController.php(1085): Illuminate\Support\Facades\Facade::__callStatic() #26 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #27 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #28 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch() #29 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController() #30 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run() #31 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckPermissions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckPermissions->handle() #34 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle() #36 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle() #38 C:\inetpub\wwwroot\snipeit\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle() #42 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckLocale->handle() #44 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #46 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #48 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #50 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute() #54 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 C:\inetpub\wwwroot\snipeit\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #59 C:\inetpub\wwwroot\snipeit\vendor\fruitcake\laravel-cors\src\HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fruitcake\Cors\HandleCors->handle() #61 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\PreventBackHistory->handle() #63 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle() #65 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #67 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle() #69 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle() #71 C:\inetpub\wwwroot\snipeit\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #73 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #75 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #76 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #77 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #78 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #79 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #80 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle() #81 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #82 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #83 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #84 C:\inetpub\wwwroot\snipeit\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle() #85 {main} Backup failed because: The dump process failed with exitcode 1 : General error : .
```

### Additional context

We wanted to test the import feature. Per https://snipe-it.readme.io/docs/importing > suggest to back up before import, and that's when we found out the error

**Comment by snipe** [comment]
Have you checked that your path to mysqldump is set correctly in your .env?

**Comment by calvinslee** [comment]
Hi,

Yes I checked it and I verified with double slashes per https://snipe-it.readme.io/docs/configuration 

I also tried following https://www.youtube.com/watch?v=_Ofy9nT5fek ,and I realize I don't have the user IIS_IUSRS, I got an error when I clicked CHECK NAMES in the security pane in Properties (C:/Windows/Temp) 

What are my next steps?

Cheers
Calvin

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required. Don't be intimidated by the length of this page. The configurati...</div></blockquote>
<blockquote><img src="https://i.ytimg.com/vi/_Ofy9nT5fek/maxresdefault.jpg" width="48" align="right"><div><img src="https://www.youtube.com/s/desktop/a264670a/img/favicon_144x144.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=_Ofy9nT5fek">Part 2 - SNIPE-IT BackUp Fix</a></strong></div><div>We will look at the fix for backup feature of SNIPE-IT. Few users reported an error when they tried to use this feature of snipe-it on Windows Server with II...</div></blockquote>

**Comment by yosiasz** [comment]
1. scale back your php version to < 8
2. could you please share that sqldump setting here?

**Comment by Jaysunusn** [comment]
I'm having the exact same issue with two new snipe it builds on windows 2016 server

**Comment by snipe** [comment]
Nothing has changed in Snipe-IT pertaining to backups, so this must be a server configuration/permissions/path issue.

**Comment by Jaysunusn** [comment]
Thank you! I'll keep working the issue.

**Comment by Jaysunusn** [comment]
Followed the entire video above and that fixed my issues. Thank you!

**Comment by calvinslee** [comment]
> 

Hi Team,

I am going to work on troubleshooting this next week. You mention to scale back PHP Version <8. Any suggestions on how far back? 7.4.27?

**Comment by calvinslee** [comment]
> Followed the entire video above and that fixed my issues. Thank you!

Hey Jaysunusn - PHP Version are you using on your local host server?

**Comment by calvinslee** [comment]
This is fixed on my end. Thanks for all the assistance
