### ISSUE TITLE
HTPP Error 500 on GoDaddy

### ISSUE THREAD

**Issue by louieblackman** [grokability/snipe-it#10888]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am receiving Error 500 on GoDaddy Shared hosting. 

I have set the document root as required but still receive the error. GoDaddy advise it is a content issue.

**Error Log Below**
[30-Mar-2022 11:32:31 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[30-Mar-2022 11:32:31 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[30-Mar-2022 11:32:32 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[30-Mar-2022 11:32:32 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[30-Mar-2022 17:16:33 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[30-Mar-2022 17:16:33 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:30:51 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:30:51 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:33:41 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:33:41 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:36:54 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:36:54 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:37:41 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:37:41 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:37:49 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:37:49 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:37:51 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:37:51 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:38:32 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:38:32 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:38:33 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:38:33 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:39:38 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:39:38 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:46:59 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:46:59 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:48:27 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:48:27 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:49:02 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:49:02 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:49:05 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:49:05 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:50:29 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:50:29 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:53:44 UTC] PHP Warning:  require(/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17
[31-Mar-2022 15:53:44 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/../vendor/autoload.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php:17
Stack trace:
#0 /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/public/index.php(22): require()
#1 {main}
  thrown in /home/nfg4tpxdpa1n/public_html/assets.lockeandhorn.co.uk/bootstrap/autoload.php on line 17

### Reproduction steps

1. Upload .ZIP Folder to CPanel
2. Extract Contents
3. Set Document Root
...

### Expected behavior

Install page should appear.

### Snipe-IT Version

5.4.1

### Operating System

Linux

### Web Server

GoDaddy

### PHP Version

8.0

**Comment by snipe** [comment]
It looks like you maybe didn't run composer install. Please see our documentation.
