### ISSUE TITLE
Error on Docker setup - permission denied for laravel.log

### ISSUE THREAD

**Issue by helinbei** [grokability/snipe-it#11032]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

<img width="901" alt="屏幕截图 2022-05-06 213516" src="https://user-images.githubusercontent.com/105055230/167230284-6851c3b5-fbc5-4fb8-8426-8e0c40cbae6d.png">

### Reproduction steps

1. docker - This happens after the pull completes the installation
2.
3.
...

### Expected behavior

Successful installation

### Screenshots

<img width="901" alt="屏幕截图 2022-05-06 213516" src="https://user-images.githubusercontent.com/105055230/167230294-8dc05c33-302d-4397-92b1-ee4b9d55d424.png">

### Snipe-IT Version

v5.4.0

### Operating System

centos

### Web Server

apache

### PHP Version

v7.4

### Version

v5.4.0

**Comment by helinbei** [comment]
![image](https://user-images.githubusercontent.com/105055230/167235704-62b89835-1f92-4efd-868b-ea17375a7c2e.png)

**Comment by helinbei** [comment]
就算加了权限也是这样的

Translation: "Even with permissions added"

**Comment by snipe** [comment]
Please answer in English. Use google translate if you have to - we're trying to help you, but you've got to help us to help you.

**Comment by helinbei** [comment]
Even with permissions added

**Comment by helinbei** [comment]
Help must be rewarded

**Comment by sergregory** [comment]
@helinbei please check your <my_env_file>
Find the APP_URL variable and check that you've specified the port number.
If you, like me, copied it from the docs, it says:
`APP_URL=http://127.0.0.1:YOUR_PORT_NUMBER`
and you need something like
`APP_URL=http://127.0.0.1:8080` instead

**Comment by lordgreg** [comment]
We have exact same issue, which is actually happening since the release 5.3.8 (5.3.7 was the last where this didn't occur):

```
Module ssl disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Nothing to migrate.
Configuration cache cleared!
Configuration cache cleared!
Configuration cached successfully!
2022-05-25 14:01:37,638 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-05-25 14:01:37,641 INFO supervisord started with pid 1
2022-05-25 14:01:38,643 INFO spawned: 'exit_on_any_fatal' with pid 43
2022-05-25 14:01:38,645 INFO spawned: 'apache' with pid 44
2022-05-25 14:01:38,647 INFO spawned: 'run_schedule' with pid 45
2022-05-25 14:01:39,731 INFO success: exit_on_any_fatal entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-25 14:01:39,731 INFO success: apache entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-25 14:01:39,731 INFO success: run_schedule entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using OUR_INTERN_IP. Set the 'ServerName' directive globally to suppress this message

   UnexpectedValueException 

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied
The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied
The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied
The exception occurred while attempting to log: Your APP_URL in your .env is misconfigured - it is: [what I have actually entered in env]. Many things will work strangely unless you fix it. in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
Stack trace:
#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write()
#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(342): Monolog\Handler\AbstractProcessingHandler->handle()
#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(583): Monolog\Logger->addRecord()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error()
#7 /var/www/html/app/Providers/AppServiceProvider.php(53): Illuminate\Support\Facades\Facade::__callStatic()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\AppServiceProvider->boot()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\Container\Container->call()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\Foundation\Application->bootProvider()
#15 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()
#21 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#22 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
Stack trace:
#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write()
#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(342): Monolog\Handler\AbstractProcessingHandler->handle()
#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(583): Monolog\Logger->addRecord()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error()
#7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic()
#8 /var/www/html/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): App\Exceptions\Handler->report()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Foundation\Console\Kernel->reportException()
#11 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#12 {main}

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142▕             restore_error_handler();
    143▕             if (!is_resource($stream)) {
    144▕                 $this->stream = null;
    145▕ 
  ➜ 146▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url) . Utils::getRecordMessageForException($record));
    147▕             }
    148▕             stream_set_chunk_size($stream, $this->streamChunkSize);
    149▕             $this->stream = $stream;
    150▕         }

      +7 vendor frames 
  8   app/Exceptions/Handler.php:44
      Illuminate\Support\Facades\Facade::__callStatic()

      +2 vendor frames 
  11  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleException()
2022-05-25 14:02:10,045 WARN received SIGTERM indicating exit request
2022-05-25 14:02:10,046 INFO waiting for exit_on_any_fatal, apache, run_schedule to die
2022-05-25 14:02:11,047 INFO stopped: run_schedule (terminated by SIGTERM)
2022-05-25 14:02:11,231 INFO stopped: apache (terminated by SIGTERM)
2022-05-25 14:02:11,435 INFO stopped: exit_on_any_fatal (terminated by SIGTERM)

```

And yes, APP_URL is set.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
