### ISSUE TITLE
ErrorException in getimagesize on asset acceptance

### ISSUE THREAD

**Issue by prodigymw** [grokability/snipe-it#11116]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Get the following error when accepting an asset. Have tried with and without signatures.

URL is https://track.prodigy.com.au/account/accept/12

ErrorException
getimagesize(): Read of 8192 bytes failed with errno=21 Is a directory

[14:57:44] LOG.error: ErrorException: getimagesize(): Read of 8192 bytes failed with errno=21 Is a directory in 
/var/www/html/snipeit/vendor/dompdf/dompdf/src/Helpers.php:649

### Reproduction steps

1. Accept an asset via emailed URL

### Expected behavior

An acceptance confirmation page?

### Screenshots

![acceptissue1](https://user-images.githubusercontent.com/71476384/168732983-ab9cba63-e872-4341-8c8e-2f6d0cd776f3.png)

### Snipe-IT Version

6.0.1

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1

### Operating System

Windows 10

### Browser

Microsoft Edge

### Version

101

### Error messages

```shell
ErrorException: getimagesize(): Read of 8192 bytes failed with errno=21 Is a directory in /var/www/html/snipeit/vendor/dompdf/dompdf/src/Helpers.php:649
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/snipeit/vendor/dompdf/dompdf/src/Helpers.php(649): getimagesize()
#2 /var/www/html/snipeit/vendor/dompdf/dompdf/src/Image/Cache.php(164): Dompdf\Helpers::dompdf_getimagesize()
#3 /var/www/html/snipeit/vendor/dompdf/dompdf/src/FrameDecorator/Image.php(56): Dompdf\Image\Cache::resolve_url()
#4 /var/www/html/snipeit/vendor/dompdf/dompdf/src/Frame/Factory.php(202): Dompdf\FrameDecorator\Image->__construct()
#5 /var/www/html/snipeit/vendor/dompdf/dompdf/src/Dompdf.php(786): Dompdf\Frame\Factory::decorate_frame()
#6 /var/www/html/snipeit/vendor/barryvdh/laravel-dompdf/src/PDF.php(208): Dompdf\Dompdf->render()
#7 /var/www/html/snipeit/vendor/barryvdh/laravel-dompdf/src/PDF.php(164): Barryvdh\DomPDF\PDF->render()
#8 /var/www/html/snipeit/app/Http/Controllers/Account/AcceptanceController.php(155): Barryvdh\DomPDF\PDF->output()
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Account\AcceptanceController->store()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#17 /var/www/html/snipeit/app/Http/Middleware/AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#19 /var/www/html/snipeit/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#21 /var/www/html/snipeit/app/Http/Middleware/CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#23 /var/www/html/snipeit/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle()
#25 /var/www/html/snipeit/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#27 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#29 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#31 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#33 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#35 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#36 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#37 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#38 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#39 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 /var/www/html/snipeit/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#42 /var/www/html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#44 /var/www/html/snipeit/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#46 /var/www/html/snipeit/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#48 /var/www/html/snipeit/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#50 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#52 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#53 /var/www/html/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#55 /var/www/html/snipeit/app/Http/Middleware/CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#57 /var/www/html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#59 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#61 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#63 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#64 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#66 /var/www/html/snipeit/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#68 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#70 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#71 /var/www/html/snipeit/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#72 {main}


[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

Recently upgraded from 5.4.4 to 6.0.1.

Issue occured with both PHP 7.4 and 8.1.

**Comment by snipe** [comment]
I'm not able to reproduce this locally - What image is it trying to display exactly? This is when the user gets the email, clicks on the acceptance links, signs it and hits submit, or?

**Comment by prodigymw** [comment]
>> What image is it trying to display exactly?

Not sure. What info can I share?

>> This is when the user gets the email, clicks on the acceptance links, signs it and hits submit

Yep, click acceptance link in the email, choose I accept, hit the Submit button and if debug isn't on, 500 error on a blank page.

**Comment by snipe** [comment]
Can you check latest on master. I did a lot of futzing with the asset acceptance stuff over the past few days.

**Comment by KCarette82** [comment]
Hello, I have exactly the same issue on 6.0.2
There seems to be an issue here:
![image](https://user-images.githubusercontent.com/106228119/170198602-a5db830d-f740-47ed-9ebd-f5be43d78790.png)

**Comment by snipe** [comment]
More info would be helpful. Does the file actually exist in your file system or not? Are you using local time storage vs S3, or?

**Comment by gyurina** [comment]
Here is the full stacktrace:
https://flareapp.io/share/x7X6EApm

<blockquote><div><img src="https://flareapp.io/favicon-16x16.png" height="14"> Flare</div><div><strong><a href="https://flareapp.io/share/x7X6EApm">Laravel error tracking – Flare</a></strong></div><div>getimagesize(): read of 8192 bytes failed with errno=21 Is a directory - The error occurred at http://itasset.ad.mazs.hu/account/accept/222</div></blockquote>

the file is not created in the file system:
![image](https://user-images.githubusercontent.com/79877778/170202161-f6c2538c-1f44-42a7-a9cc-758d5166d4fa.png)

**Comment by KCarette82** [comment]
> More info would be helpful. Does the file actually exist in your file system or not? Are you using local time storage vs S3, or?

No files are created in my setup either.  upgraded from 5.4.3 -> 6.0.2 and issue started occurring.
Local storage, local setup.

**Comment by gyurina** [comment]
Hi, 

I have found the problem. :) I guess.
There was no site branding logo uploaded. The moment I have uploaded one, the issue is gone and the pdf is generated correctly.

**Comment by KCarette82** [comment]
> Hi,
> 
> I have found the problem. :) I guess. There was no site branding logo uploaded. The moment I have uploaded one, the issue is gone and the pdf is generated correctly.

I can confirm this solution also works on our setup

**Comment by KCarette82** [comment]
Maybe I'm missing something, but where can the PDF file of the signed EULA / Asset acceptance be viewed or downloaded?
Is it possible for the end user to download this? Or only for admins?
Thanks

**Comment by prodigymw** [comment]
> Maybe I'm missing something, but where can the PDF file of the signed EULA / Asset acceptance be viewed or downloaded? Is it possible for the end user to download this? Or only for admins? Thanks

If you go into the History of an asset, enable the Signature and Download columns (they're off by default);

![image](https://user-images.githubusercontent.com/71476384/170910625-e5af9246-3755-439c-a084-e11728da7cc6.png)

**Comment by prodigymw** [comment]
Can confirm that once a brand logo is in use, issue no longer occurs.
