### ISSUE TITLE
500 Error When Assigning Asset During Asset Creation - Undefined array key "checkout_counter"

### ISSUE THREAD

**Issue by ntbutler-nbcs** [grokability/snipe-it#11293]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi awesome people!

We are seeing Internal Server errors when assigning a new asset to someone at the time the asset is being created. The asset is created, but we reach the "500 | Server Error" screen.

The asset is created, and it is correctly checked out to the user, but we get the error screen.

### Reproduction steps

1. Go to Assets -> Create New
2. Populate Asset Tag, Serial, Model, Status (ready to deploy)
3. Checkout asset to a user (also occurs checking out to a location)
4. Click Save

### Expected behavior

Return to the asset list without seeing an error.

### Snipe-IT Version

6.0.2

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0.20 (also occurred on 8.0.0)

### Error messages

```shell
[2022-06-10 15:14:13] production.DEBUG: onCheckedOut in the Checkoutable listener fired  
[2022-06-10 15:14:13] production.ERROR: ErrorException: Undefined array key "checkout_counter" in C:\inetpub\snipe-it\app\Observers\AssetObserver.php:26
Stack trace:
#0 C:\inetpub\snipe-it\app\Observers\AssetObserver.php(26): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(424): App\Observers\AssetObserver->updating()
#2 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#3 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(222): Illuminate\Events\Dispatcher->dispatch()
#4 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasEvents.php(189): Illuminate\Events\Dispatcher->until()
#5 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(859): Illuminate\Database\Eloquent\Model->fireModelEvent()
#6 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(820): Illuminate\Database\Eloquent\Model->incrementOrDecrement()
#7 C:\inetpub\snipe-it\app\Models\Asset.php(346): Illuminate\Database\Eloquent\Model->increment()
#8 C:\inetpub\snipe-it\app\Http\Controllers\Assets\AssetsController.php(200): App\Models\Asset->checkOut()
#9 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Assets\AssetsController->store()
#10 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#11 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#12 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#13 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Route->run()
#14 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#17 C:\inetpub\snipe-it\app\Http\Middleware\AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#19 C:\inetpub\snipe-it\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#21 C:\inetpub\snipe-it\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#23 C:\inetpub\snipe-it\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle()
#25 C:\inetpub\snipe-it\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#27 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#29 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#31 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#33 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline->then()
#35 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#36 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRoute()
#37 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#38 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch()
#39 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 C:\inetpub\snipe-it\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#42 C:\inetpub\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#44 C:\inetpub\snipe-it\vendor\fruitcake\laravel-cors\src\HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#46 C:\inetpub\snipe-it\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#48 C:\inetpub\snipe-it\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#50 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#52 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#53 C:\inetpub\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#55 C:\inetpub\snipe-it\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#57 C:\inetpub\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#59 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#61 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#63 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#64 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#66 C:\inetpub\snipe-it\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#68 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#70 C:\inetpub\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#71 C:\inetpub\snipe-it\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#72 {main}  
[2022-06-10 15:14:13] production.ERROR: Undefined array key "checkout_counter" {"userId":283,"exception":"[object] (ErrorException(code: 0): Undefined array key \"checkout_counter\" at C:\\inetpub\\snipe-it\\app\\Observers\\AssetObserver.php:26)
[stacktrace]
#0 C:\\inetpub\\snipe-it\\app\\Observers\\AssetObserver.php(26): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(424): App\\Observers\\AssetObserver->updating()
#2 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#3 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(222): Illuminate\\Events\\Dispatcher->dispatch()
#4 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasEvents.php(189): Illuminate\\Events\\Dispatcher->until()
#5 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(859): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#6 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(820): Illuminate\\Database\\Eloquent\\Model->incrementOrDecrement()
#7 C:\\inetpub\\snipe-it\\app\\Models\\Asset.php(346): Illuminate\\Database\\Eloquent\\Model->increment()
#8 C:\\inetpub\\snipe-it\\app\\Http\\Controllers\\Assets\\AssetsController.php(200): App\\Models\\Asset->checkOut()
#9 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\Assets\\AssetsController->store()
#10 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#11 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#12 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#13 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Route->run()
#14 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#15 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#17 C:\\inetpub\\snipe-it\\app\\Http\\Middleware\\AssetCountForSidebar.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\AssetCountForSidebar->handle()
#19 C:\\inetpub\\snipe-it\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#21 C:\\inetpub\\snipe-it\\app\\Http\\Middleware\\CheckForTwoFactor.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForTwoFactor->handle()
#23 C:\\inetpub\\snipe-it\\app\\Http\\Middleware\\CheckUserIsActivated.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckUserIsActivated->handle()
#25 C:\\inetpub\\snipe-it\\app\\Http\\Middleware\\CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckLocale->handle()
#27 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 C:\\inetpub\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 C:\\inetpub\\snipe-it\\vendor\\laravel\\
```

**Comment by ntbutler-nbcs** [comment]
Just to add to this - After the asset is created, manually checking the asset in and out to users/locations does not produce any errors - this appears to be limited to when it is assigned as the same time the asset is created.

**Comment by inietov** [comment]
This bug was introduced a couple days ago. Now it's fixed if you pull latest master.
