### ISSUE TITLE
Error: Backup failed because The dump process failed with exitcode 2 

### ISSUE THREAD

**Issue by zm1868179** [grokability/snipe-it#11327]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Attempting to run a back either via CLI or inside of SnipeIT will result in a failure and no backup is created.  If I run a files only backup that will succeed Application is hosted on Azure Web App Services.  I have attempted with both DB SSL on and Off with the required Cert Pem file and both results in the same error

### Reproduction steps

1. Settings
2. Backup
3. Generate Backup

### Expected behavior

Backup Succeed

### Screenshots

![Screenshot 2022-06-15 183346](https://user-images.githubusercontent.com/20147174/173946373-79748c09-fb2b-47f9-be62-aa024407828e.png)
![Screenshot 2022-06-15 183414](https://user-images.githubusercontent.com/20147174/173946436-bc34eb76-f582-4974-b85a-3c85a2d3eeac.png)
![Screenshot 2022-06-15 183559](https://user-images.githubusercontent.com/20147174/173946857-22ba5227-584e-45d7-8a96-c4d57558e0a0.png)

### Snipe-IT Version

6.0.4

### Operating System

Windows

### Web Server

IIS

### PHP Version

PHP 7.4

### Operating System

Windows 11

### Browser

Edge

### Version

102

### Error messages

```shell
 Error Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2026: SSL connection error: socket layer receive error when trying to connect . #0 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(260): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(695): array_map() #5 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(263): Illuminate\Support\Collection->map() #6 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(171): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(147): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #10 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #11 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #12 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #13 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call() #14 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call() #15 C:\home\site\wwwroot\SnipeITWEB\vendor\symfony\console\Command\Command.php(298): Illuminate\Console\Command->execute() #16 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run() #17 C:\home\site\wwwroot\SnipeITWEB\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run() #18 C:\home\site\wwwroot\SnipeITWEB\vendor\symfony\console\Application.php(1015): Spatie\Backup\Commands\BaseCommand->run() #19 C:\home\site\wwwroot\SnipeITWEB\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand() #20 C:\home\site\wwwroot\SnipeITWEB\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun() #21 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Console\Application.php(94): Symfony\Component\Console\Application->run() #22 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Console\Application.php(186): Illuminate\Console\Application->run() #23 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(263): Illuminate\Console\Application->call() #24 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #25 C:\home\site\wwwroot\SnipeITWEB\app\Http\Controllers\SettingsController.php(1091): Illuminate\Support\Facades\Facade::__callStatic() #26 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #27 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #28 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch() #29 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController() #30 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Route->run() #31 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\CheckPermissions.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckPermissions->handle() #34 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle() #36 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle() #38 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle() #42 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle() #44 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle() #46 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #48 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #50 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle() #52 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #53 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline->then() #54 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router->runRouteWithinStack() #55 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRoute() #56 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router->dispatchToRoute() #57 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch() #58 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #59 C:\home\site\wwwroot\SnipeITWEB\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle() #61 C:\home\site\wwwroot\SnipeITWEB\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #63 C:\home\site\wwwroot\SnipeITWEB\vendor\fruitcake\laravel-cors\src\HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle() #65 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle() #67 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle() #69 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #71 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() #72 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #73 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle() #74 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #75 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle() #76 C:\home\site\wwwroot\SnipeITWEB\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #77 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle() #78 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #79 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #80 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #81 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #82 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle() #83 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #84 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #85 C:\home\site\wwwroot\SnipeITWEB\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #86 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #87 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #88 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #89 C:\home\site\wwwroot\SnipeITWEB\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #90 C:\home\site\wwwroot\SnipeITWEB\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle() #91 {main} Backup failed because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2026: SSL connection error: socket layer receive error when trying to connect .
```

### Additional context

This is a Clean install it was installed via GIT install.
At first I did not have the mysql folder defined in the .env which resulted in file not found but after adding that I have the SSL Error I can find no reference to Error 2026 but do see mentions of misuse of shell builtins.

Current .ENV Settings for DB

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST='removed'.mysql.database.azure.com
DB_DATABASE='removed'
DB_USERNAME='removed'
DB_PASSWORD='removed'
DB_PREFIX=null
DB_DUMP_PATH='C:\Program Files (x86)\mysql\5.7.9.0\bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

**Comment by uberbrady** [comment]
You might need some of the other `DB_*` variables - I'm thinking `DB_SSL=true` - since I'm seeing some SSL stuff in your error message. But if the rest of your connectivity to the DB works, I'm definitely a little confused as to why the Backup package can't connect...

There's also a `DB_SSL_IS_PAAS` variable which then allows for `DB_SSL_CA_PATH`, or without it, you can use: 
- `DB_SSL_KEY_PATH`
- `DB_SSL_CERT_PATH`
- `DB_SSL_CA_PATH`
- `DB_SSL_CIPHER`

I'm not so familiar with Azure so I can't speak to that, but those might be some options to play with. Again, though, I'd suspect that nothing would work at all if those values were wrong - not that it would just fail on backup, with everything else still working.

**Comment by zm1868179** [comment]
Yea that's the strange thing if I don't include the path the .pem file with DB_SSL enabled the application will not work and will result in a 500 error. If I include it,  it works over ssl and everything functions I just can't do backups

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zm1868179** [comment]
This is what's in the DB SSL Settings int eh .ENV

Since its hosted on a PAAS the DB_SSL_IS_PAAS needs to be set to true along with the CA Path and thats it
# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=true
DB_SSL_IS_PAAS=true
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH='C:\home\site\wwwroot\SnipeITWEB\BaltimoreCyberTrustRoot.crt.pem'
DB_SSL_CIPHER=null
