### ISSUE TITLE
 There are 500 errors after installing snipe it with docker according to the official manual

### ISSUE THREAD

**Issue by hehehebigking** [grokability/snipe-it#11566]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

按照官方手册使用Docker 安装Snipe-it后出现了500错误，问题无法解决

### Reproduction steps

1.
2.
3.
...

### Expected behavior

There are 500 errors after installing snipe it with docker according to the official manual, and the problem cannot be solved

### Screenshots

<img width="1008" alt="微信截图_20220727154419" src="https://user-images.githubusercontent.com/109956173/181191057-65032918-be04-4fc2-9cbd-14d94859cbc6.png">

### Snipe-IT Version

lastest

### Operating System

centos7

### Web Server

docker install

### PHP Version

docker install

### Operating System

win10

### Version

lastest

**Comment by antonc42** [comment]
I had a similar problem. It was a permission problem in the container. I found the solution in issue #11423.

```
docker exec -it <container-name> chown -R docker:root /var/www/html/storage/framework/cache
docker restart <container-name>
```

**Comment by uberbrady** [comment]
If we have some kind of permissions issue in our Docker container, we should fix it. But the last time I tested it, it seemed to work fine? Are we 1000% sure that this was the snipe/snipe-it container, and not something else?

**Comment by antonc42** [comment]
Ubuntu 22.04
Docker 20.10.17

Steps to reproduce:

1. Generate `APP_KEY`
 ```
SNIPE_APP_KEY=$(docker run --rm docker.io/snipe/snipe-it:latest php artisan key:generate -n --show)
```
2. Start database container. Watch `docker logs -f snipe-mysql` until database is initialized.
```
docker run \
-d --restart=always \
-e MYSQL_ROOT_PASSWORD="changeme" \
-e MYSQL_DATABASE=snipeit \
-e MYSQL_USER=snipeit \
-e MYSQL_PASSWORD="changeme" \
-v snipesql-vol:/var/lib/mysql \
--name=snipe-mysql docker.io/mariadb:latest
```
3. Start Snipe-IT container. Watch `docker logs -f snipe-it` until app is loaded.
```
docker run \
-d --restart=always \
-e MYSQL_ROOT_PASSWORD="changeme" \
-e MYSQL_DATABASE=snipeit \
-e MYSQL_USER=snipeit \
-e MYSQL_PASSWORD="changeme" \
-e APP_ENV=production \
-e APP_DEBUG=false \
-e APP_URL=http://localhost:8080 \
-e APP_TIMEZONE=$(cat /etc/timezone) \
-e APP_LOCALE=en \
-e APP_KEY=${SNIPE_APP_KEY} \
-v snipe-vol:/var/lib/snipeit \
-p 8080:80 \
--link snipe-mysql:mysql \
--name=snipe-it docker.io/snipe/snipe-it:latest
```
4. Go to `localhost:8080` in a broswer. Observe blank screen.
5. Exec into container shell.
```
docker exec -it snipe-it bash
```
6. Observe errors in Apache log.
```
cat /var/log/apache2/error.log
...
PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheMana in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187
```
7. Observe incorrect permissions on contents of `/var/www/html/storage/framework/cache` directory.
```
ls -l /var/www/html/storage/framework/cache
total 4
drwxr-xr-x 3 root root 4096 Jan 01 00:00 cf
```
8. Fix permissions either by restarting the container, which causes the `startup.sh` script to run again [which fixes the permissions](https://github.com/snipe/snipe-it/blob/d7d0056b736b17455463322eaf685a76a7fa9598/docker/startup.sh#L43) or by running the command to fix the permissions manually.
```
chown -R docker:root /var/www/html/storage/framework/cache
```
9. Go to `localhost:8080` in a broswer (or refresh). Observe the Snipe-IT Pre-Flight is now working.
10. To reproduce again, all the containers and volumes must be removed.
```
docker stop snipe-it snipe-mysql
docker rm snipe-it snipe-mysql
docker volume rm snipe-vol snipesql-vol
```

It appears that whatever is creating the contents of the `/var/www/html/storage/framework/cache` directory happens after the permissions are set by [the line in the startup script](https://github.com/snipe/snipe-it/blob/d7d0056b736b17455463322eaf685a76a7fa9598/docker/startup.sh#L43). Most likely that process is running as the root user and therefore creates the contents with the root user's permissions.

**Comment by sebrem** [comment]
For me it was sufficient to `docker exec snipe-it php artisan cache:clear` in order to be able to get the setup page after the first start of the container (once the application is ready). Maybe it should be added to the `/entrypoint.sh`. (I'm using the alpine image which also seems to be a bit different and seems to skip some steps)

PS: On a side-note, the documentation states correctly that the database server already needs to be running, so if you start mysql as a container e.g. in a script or docker-compose you need to make sure the database is reachable before starting the snipe-it container as it doesn't seem to have built-in checks regarding the database connection before performing those database migrations. That's another source for HTTP status 500 errors.

**Comment by thatsankur** [comment]
Really annoying issue while bootstrapping with docker-compose or downloading image from docker hub need to run 
composer require --dev laravel/dusk 
on sipe container to install this dependency to get rid of 

Class 'Laravel\Dusk\DuskServiceProvider' not found issue in latest image

**Comment by snipe** [comment]
Dusk is only required for dev instances.

**Comment by thatsankur** [comment]
Yes I am checking this out and  tried all possible ways in dev env it worked after this

**Comment by thatsankur** [comment]
even in production docker container I saw welcome screen after running this inside container

**Comment by thatsankur** [comment]
Any one stumbling across this issue until it is looked by experts.

Extend the image offered on docker hub and execute 
composer require --dev laravel/dusk
and make custom image as a work around for now 

Dockerfile

`FROM snipe/snipe-it:v6.0.14
RUN composer require --dev laravel/dusk`

build image 

docker build -t IMAGE_NAME  .


docker-compose.yml

`
version: '3'

services:
  snipeit:
    image: IMAGE_NAME
    ports:
    - "8000:80"
    volumes:
    - ./logs:/var/www/html/storage/logs
    depends_on:
    - mariadb
    - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - snipeit-backend


volumes:
  db: {}

networks:
  snipeit-backend: {}

`


In case they want to have a working image rather then running from code directly

**Comment by a-ml** [comment]
For me non of the above solution works. I'm keeping receiving "500 | SERVER ERROR"

**Comment by snipe** [comment]
Are you still seeing this on the latest on docker?
