### ISSUE TITLE
MYSQL_PORT_3306_TCP_ADDR stays localhost. Docker, Portainer, External DB

### ISSUE THREAD

**Issue by Refferic** [grokability/snipe-it#11560]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The problem is that the "MYSQL_PORT_3306_TCP_ADDR" doesn't get used. When populating this field in the .env file, the external IP shows up at the portainer .env, but the local IP address get's used in the logs. 

Also, the MYSQL user and password are working. It's even possible to remote login via the command line form within the VM. The problem is that the "MYSQL_PORT_3306_TCP_ADDR" values are not populated throughout.

### Reproduction steps

1. Create new VM
2. Install fresh Ubuntu 20.04 LTS Server 
3. Install Docker (apt get)
4. Install Portainer 
5. Install snipe-it docker container
6. Update .env file
7.
...

### Expected behavior

Expected behavior is that the value stated at MYSQL_PORT_3306_TCP_ADDR in the env file gets populated within the docker container so it doesn't try to connect at localhost. 

### Screenshots
Note; fields look empty, but are actually painted white to mask the information in the cells.

**Logfile**
<img width="698" alt="portainer_error" src="https://user-images.githubusercontent.com/12157118/180883142-fa37a482-3aee-4acf-82b3-ba5585e861ee.png">

**Env file**
<img width="917" alt="portainer_env" src="https://user-images.githubusercontent.com/12157118/180883140-5fa92788-a995-43fd-9e71-838551300564.png">

### Snipe-IT Version

1.25.0

### Operating System

Ubuntu 20.04 Server

### Web Server

Portainer

### PHP Version

7.4

### Operating System

Windows 10 & Windows 11

### Browser

Chrome, Edge

### Error messages

```shell
The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied The exception occurred while attempting to log: User table and settings table DO NOT exist or DO NOT have records in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(550): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->debug() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(142): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(643): Illuminate\Log\Logger->debug() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->debug() #7 /var/www/html/app/Models/Setting.php(124): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/app/Http/Middleware/CheckForSetup.php(21): App\Models\Setting::setupCompleted() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle() #10 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle() #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #19 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #24 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #25 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\Routing\Pipeline->handleException() #10 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle() #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #19 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #24 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #25 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\Routing\Pipeline->handleException() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle() #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #17 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #22 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #23 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\Routing\Pipeline->handleException() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #15 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #20 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #21 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\Routing\Pipeline->handleException() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #12 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #17 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #18 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\Routing\Pipeline->handleException() #10 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #15 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #16 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\Routing\Pipeline->handleException() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #13 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #14 {main} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write() #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle() #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Log\LogManager->error() #7 /var/www/html/app/Exceptions/Handler.php(44): Illuminate\Support\Facades\Facade::__callStatic() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(415): App\Exceptions\Handler->report() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(113): Illuminate\Foundation\Http\Kernel->reportException() #10 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle() #11 {main}
```

### Additional context

- This is a fresh install
- Repoduced multiple times by removing the VM completely and reinstalling it.
- Same error is present when trying to install it without docker/portainer.

**Comment by Nerdy-Technician** [comment]
You need to specify the database name and any credentials required if you point it to the host it wont know what to look for.

for example 

```
DB_Name=snipeit
DB_Host=123.123.123
DB_username=DBname
DB_password=DBpassword
```
