### ISSUE TITLE
500 Server Errors in LDAP connection

### ISSUE THREAD

**Issue by jabellas** [grokability/snipe-it#11618]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrading to the latest version of Snipe it, upgrading to php 8 and latest version of php ldap, get a 500 server error page whenever connecting on a browser that has not saved the authentication on a cookie. Have tested that the server can connect correctly to ldap using the configuration parameters in the LDAP/AD settings of snipe it with ldapsearch on the command line. Whenever I do a test connection to the LDAP server - which is an AD server - I get the following error:

 500 Server Error. Please check your server logs for more information.

### Reproduction steps

1. try to connect to the server or
2.try to test connectivity from snipe it settings
3.
...

### Expected behavior

display login page or successfully test the LDAP connection from the LDAP/AD settings page of snipe it

### Snipe-IT Version

Version v6.0.8 - build 8409 (master) 

### Operating System

 Ubuntu 20.04.4 LTS

### Web Server

Apache2

### PHP Version

PHP Version 8.0.21

### Operating System

Windows

### Browser

Google Chrome

### Version

103.0.5060.134

### Error messages

```shell
No further error than the one described above

No stacktrace

This is the only error: 500 Server Error. Please check your server logs for more information

Output of php -m

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

tail of laravel.log

#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"}

tail of syslog

Aug  4 15:42:01 inventory CRON[1996]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:43:01 inventory CRON[2005]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:44:01 inventory CRON[2014]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:45:01 inventory CRON[2024]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:46:01 inventory CRON[2041]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:47:01 inventory CRON[2052]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:48:01 inventory CRON[2061]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:49:01 inventory CRON[2070]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:50:01 inventory CRON[2080]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)
Aug  4 15:51:01 inventory CRON[2089]: (root) CMD (/usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1)

Tail of Apache2/error.log

[Thu Aug 04 14:52:00.009433 2022] [mpm_prefork:notice] [pid 2332] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Aug 04 14:52:00.009490 2022] [core:notice] [pid 2332] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 04 15:01:25.285766 2022] [mpm_prefork:notice] [pid 2332] AH00169: caught SIGTERM, shutting down
PHP Warning:  Module "ldap" is already loaded in Unknown on line 0
[Thu Aug 04 15:01:25.505699 2022] [mpm_prefork:notice] [pid 2518] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Aug 04 15:01:25.505776 2022] [core:notice] [pid 2518] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 04 15:03:47.567784 2022] [mpm_prefork:notice] [pid 2518] AH00169: caught SIGTERM, shutting down
PHP Warning:  Module "ldap" is already loaded in Unknown on line 0
[Thu Aug 04 15:04:22.365643 2022] [mpm_prefork:notice] [pid 862] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Aug 04 15:04:22.365723 2022] [core:notice] [pid 862] AH00094: Command line: '/usr/sbin/apache2'

tail of other vhost access log


inventory.icaboston.org:80 172.16.8.42 - - [04/Aug/2022:15:16:04 -0400] "GET /login HTTP/1.1" 500 6856 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:36:09 -0400] "POST /api/v1/settings/ldaptestlogin HTTP/1.1" 500 120022 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:40:53 -0400] "POST /admin/ldap HTTP/1.1" 500 1493324 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:41:41 -0400] "GET /admin/ldap HTTP/1.1" 200 42844 "http://inventory.icaboston.org/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:41:41 -0400] "GET /_debugbar/assets/stylesheets?v=1658335695&theme=auto HTTP/1.1" 200 128515 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:41:41 -0400] "GET /_debugbar/assets/javascript?v=1658335695 HTTP/1.1" 200 368067 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:41:57 -0400] "POST /api/v1/settings/ldaptestlogin HTTP/1.1" 500 120022 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:42:22 -0400] "GET /_debugbar/open?max=20&offset=0 HTTP/1.1" 200 2469 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:46:59 -0400] "GET /api/v1/settings/ldaptest HTTP/1.1" 500 120026 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
inventory.icaboston.org:80 192.168.16.131 - - [04/Aug/2022:15:47:17 -0400] "GET /_debugbar/open?max=20&offset=0 HTTP/1.1" 200 2469 "http://inventory.icaboston.org/admin/ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"


192.168.10.47 - - [04/Aug/2022:09:20:44 -0400] "-" 408 0 "-" "-"
::1 - - [04/Aug/2022:09:34:15 -0400] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) (internal dummy connection)"
192.168.16.131 - - [04/Aug/2022:14:39:10 -0400] "GET /test.php HTTP/1.1" 200 23062 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
192.168.16.131 - - [04/Aug/2022:14:39:11 -0400] "GET /favicon.ico HTTP/1.1" 404 489 "http://172.16.8.34/test.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
192.168.16.131 - - [04/Aug/2022:14:52:07 -0400] "GET /test.php HTTP/1.1" 200 23087 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
192.168.16.131 - - [04/Aug/2022:14:52:13 -0400] "GET /test.php HTTP/1.1" 200 23086 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
172.16.8.42 - - [04/Aug/2022:15:10:19 -0400] "-" 408 0 "-" "-"
172.16.8.42 - - [04/Aug/2022:15:15:40 -0400] "-" 408 0 "-" "-"
172.16.8.42 - - [04/Aug/2022:15:16:55 -0400] "-" 408 0 "-" "-"
```

**Comment by uberbrady** [comment]
Check `storage/logs/laravel.log` - anything that 500's should output at least something somewhat useful there.

**Comment by jabellas** [comment]
Interestingly, there are no entries past 7/20/2022?!
[laravel.log](https://github.com/snipe/snipe-it/files/9263271/laravel.log)
 which may be around the time that I started trying to upgrade the software.

**Comment by jabellas** [comment]
Ok, after some extended troubleshooting that allowed me to do some more directed googling ended up fixing the security on /var/www/snipeit/storage to www-data:www-data and 755 recursively and now all is well again.
