### ISSUE TITLE
upgrade to 6.0.10 failed [Class 'Barryvdh\Cors\ServiceProvider' not found]

### ISSUE THREAD

**Issue by jrainone** [grokability/snipe-it#11753]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after upgrading i get error 500.  i enabled debug and get the following error.

(1/1) FatalThrowableErrorClass 'Barryvdh\Cors\ServiceProvider' not found
--
in ProviderRepository.php line 208
at ProviderRepository->createProvider()in ProviderRepository.php line 144
at ProviderRepository->compileManifest()in ProviderRepository.php line 61
at ProviderRepository->load()in Application.php line 561
at Application->registerConfiguredProviders()in RegisterProviders.php line 17
at RegisterProviders->bootstrap()in Application.php line 213
at Application->bootstrapWith()in Kernel.php line 162
at Kernel->bootstrap()in Kernel.php line 146
at Kernel->sendRequestThroughRouter()in Kernel.php line 116
at Kernel->handle()in index.php line 52

### Reproduction steps

1. upgrade PHP
2. upgraded composer
3. ran git pull 
4. ran php upgrade.php 
5. would not load, enabled debug and go the following error
6. ran sudo -u www-data php upgrade.php
7. webpage error remains

### Expected behavior

load up normal snipeIT webpage

### Screenshots

![Capture](https://user-images.githubusercontent.com/106692076/187103766-3c80bc8a-ec8d-418f-afd8-c2cba6ba43ff.PNG)

### Snipe-IT Version

6.0.10

### Operating System

ubuntu 

### Web Server

apache 2 2.1.29

### PHP Version

7.4.30

### Operating System

windows

### Browser

chrome

### Version

 104.0.5112.102

### Error messages

```shell
browser
(1/1) FatalThrowableError
Class 'Barryvdh\Cors\ServiceProvider' not found

in ProviderRepository.php line 208
at ProviderRepository->createProvider()
in ProviderRepository.php line 144
at ProviderRepository->compileManifest()
in ProviderRepository.php line 61
at ProviderRepository->load()
in Application.php line 561
at Application->registerConfiguredProviders()
in RegisterProviders.php line 17
at RegisterProviders->bootstrap()
in Application.php line 213
at Application->bootstrapWith()
in Kernel.php line 162
at Kernel->bootstrap()
in Kernel.php line 146
at Kernel->sendRequestThroughRouter()
in Kernel.php line 116
at Kernel->handle()
in index.php line 52


log file
#0 [internal function]: Swift_Transport_StreamBuffer->{closure}(2, 'stream_socket_c...', '/var/www/snipei...', 272, Array)
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(272): stream_socket_client('10.77.14.90:25', 113, 'No route to hos...', 30, 4, Resource id #844)
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#3 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#4 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(64): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\CleanupHasFailed))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(Spatie\Backup\Notifications\Notifiable), '5526203f-5fb3-4...', Object(Spatie\Backup\Notifications\Notifications\CleanupHasFailed), 'mail')
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Array, Object(Spatie\Backup\Notifications\Notifications\CleanupHasFailed))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send(Array, Object(Spatie\Backup\Notifications\Notifications\CleanupHasFailed))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\CleanupHasFailed))
#13 /var/www/snipeit/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\CleanupHasFailed))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(350): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\CleanupHasFailed))
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Spatie\\Backup\\E...', Array)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(467): Illuminate\Events\Dispatcher->dispatch('Spatie\\Backup\\E...')
#17 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(47): event(Object(Spatie\Backup\Events\CleanupHasFailed))
#18 [internal function]: Spatie\Backup\Commands\CleanupCommand->handle()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#24 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#26 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/snipeit/vendor/symfony/console/Application.php(987): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### Additional context

s this a fresh install or an upgrade? Upgrade
What OS and web server you're running Snipe-IT on: ubuntu/apache
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git pull
Include what you've done so far in the installation, and if you got any error messages along the way. : listed above
Indicate whether or not you've manually edited any data directly in the database- no edits to my knowledge 
Add any other context about the problem here.  tried to upgrade from v4 to v6.

**Comment by jrainone** [comment]
Closing issue, their is permission issues and then a database issue, had to role back and will attempt upgrade later date.
