### ISSUE TITLE
MySQL - Insecure Transports are Prohibited error

### ISSUE THREAD

**Issue by AnestisSi** [grokability/snipe-it#11785]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello,

I have an Azure MySQL database configured to enforce TLS1.2(require_secure_transport). When that option is on the application cannot connect. If I turn it off snipe-it connects successfully. Is snipe-it not using ssl to connect to mysql? Or do I need to add specific options on the .env in order to do it?

### Reproduction steps

1. Create MySQL database 
2. Enable secure transport (Azure enables require_secure_transport by default)

### Expected behavior

Allow secure connections to MySQL

### Snipe-IT Version

v6.0.10

### Operating System

Linux

### Web Server

not sure using docker

### PHP Version

7.4.26

### Error messages

```shell
Illuminate\Database\QueryException: SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited while --require_secure_transport=ON. (SQL: select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1) in file /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 712

#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection-&gt;runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection-&gt;run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection-&gt;select()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Database\Query\Builder-&gt;runSelect()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936): Illuminate\Database\Query\Builder-&gt;Illuminate\Database\Query\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2403): Illuminate\Database\Query\Builder-&gt;onceWithColumns()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(625): Illuminate\Database\Query\Builder-&gt;get()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(609): Illuminate\Database\Eloquent\Builder-&gt;getModels()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(294): Illuminate\Database\Eloquent\Builder-&gt;get()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(53): Illuminate\Database\Eloquent\Builder-&gt;first()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(148): Illuminate\Auth\EloquentUserProvider-&gt;retrieveById()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\Auth\SessionGuard-&gt;user()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(336): Illuminate\Auth\SessionGuard-&gt;check()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Auth\AuthManager-&gt;__call()
#14 /var/www/html/app/Http/Middleware/CheckForDebug.php(21): Illuminate\Support\Facades\Facade::__callStatic()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForDebug-&gt;handle()
#16 /var/www/html/app/Http/Middleware/CheckForSetup.php(32): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForSetup-&gt;handle()
#18 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession-&gt;handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle()
#27 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore-&gt;handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#32 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#33 {main}
```

### Additional context

Is this a fresh install or an upgrade?
fresh install

What OS and web server you're running Snipe-IT on
-

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker

Include what you've done so far in the installation, and if you got any error messages along the way.
normal installation. Run into a small issue with the url of the install because Azure was using proxy which I resolved. And only the Database issue

Indicate whether or not you've manually edited any data directly in the database
no

-

**Comment by n3s0** [comment]
Something that may assist with this. You may need to set .env variables manually in the .env file.

These environment variables are located in the following lines from the [config/database.php](https://github.com/snipe/snipe-it/blob/293e3e02e416b36de36294d4b2ec331213cfab50/config/database.php) file.

```php
'options' => (env('DB_SSL')) ? ((env('DB_SSL_IS_PAAS')) ? [
                PDO::MYSQL_ATTR_SSL_CA                  => env('DB_SSL_CA_PATH'),   // /path/to/ca.pem
            ] : [
                PDO::MYSQL_ATTR_SSL_KEY                 => env('DB_SSL_KEY_PATH'),  // /path/to/key.pem
                PDO::MYSQL_ATTR_SSL_CERT                => env('DB_SSL_CERT_PATH'), // /path/to/cert.pem
                PDO::MYSQL_ATTR_SSL_CA                  => env('DB_SSL_CA_PATH'),   // /path/to/ca.pem
                PDO::MYSQL_ATTR_SSL_CIPHER              => env('DB_SSL_CIPHER'),
            ]) : [],
        ],
```

Try updating your .env file  in the database configuration with the following and see? Note. You may need to make necessary changes to your configuration that reflect configuration needed for your database platform.

DB_SSL=True
DB_SSL_IS_PAAS=True
DB_SSL_CA_PATH='/path/to/ca.pem'
DB_SSL_KEY_PATH='/path/to/key.pem'
DB_SSL_CERT_PATH='/path/to/cert.pem'
DB_SSL_CIPHER='Cipher Name'

Hope this helps!

**Comment by n3s0** [comment]
Hi, did this configuration for the application help solve your issue?

**Comment by doug-fitzmaurice-rowden** [comment]
I ran into a similar problem with Azure's MySQL Flexible servers. 
When I enabled the `DB_SSL_IS_PAAS=True` option I was getting a different error:
```
SQLSTATE[HY000] [2002]  (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = migrations and table_type = 'BASE TABLE')
```
The actual issue was only present in the full laravel log (`/var/www/html/storage/logs/laravel.log`):
```
Peer certificate CN=`abcdef123456.database.azure.com' did not match expected CN=`snipeit.snipeit.private.mysql.database.azure.com'
```

This was because I was trying to connect to the private DNS zone entry as above.
If you hit a similar error make sure you're using the public DNS name, like `snipeit.mysql.database.azure.com`
