### ISSUE TITLE
PHP Fatal error:  Uncaught Error: 

### ISSUE THREAD

**Issue by Pkumar22in** [grokability/snipe-it#12113]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

I have recently upgraded my SnipeIT installation from V5 to latest V6.0.3 using php upgrade.php command. After the process completed, My SnipeIT portal is not coming online. I tried many things but nothing worked. In logs I see below error.

[Tue Nov 15 07:41:45.087085 2022] [php7:error] [pid 2116196] [client 122.186.148.178:52825] PHP Fatal error:  Uncaught Error: Class 'Symfony\\Component\\Debug\\Exception\\FatalThrowableError' not found in /var/www/assets-uat.ekoexcel.org.ng/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:122\nStack trace:\n#0 /var/www/assets-uat.ekoexcel.org.ng/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()\n#1 {main}\n  thrown in /var/www/assets-uat.ekoexcel.org.ng/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php on line 122

Can anyone help please

### Reproduction steps

1.Upgraded the V5 installation using php upgrade.php command to V6.0.3
2.Process completed.
3. Restarted the server
4. SnipeIT doesn't come online now.

### Expected behavior

After upgrade portal should have come back online.

### Snipe-IT Version

V 6.0.3

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Operating System

macOS

### Browser

Chrome

### Error messages

```shell
[Tue Nov 15 07:41:45.087085 2022] [php7:error] [pid 2116196] [client 122.186.148.178:52825] PHP Fatal error:  Uncaught Error: Class 'Symfony\\Component\\Debug\\Exception\\FatalThrowableError' not found in /var/www/assets-uat.ekoexcel.org.ng/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:122\nStack trace:\n#0 /var/www/assets-uat.ekoexcel.org.ng/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()\n#1 {main}\n  thrown in /var/www/assets-uat.ekoexcel.org.ng/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php on line 122
```

**Comment by Pkumar22in** [comment]
this is
