### ISSUE TITLE
/html/snipeit/public/setup" failed (2: No such file or directory),

### ISSUE THREAD

**Issue by hankunlun** [grokability/snipe-it#12234]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

/html/snipeit/public/setup" failed (2: No such file or directory),

### Reproduction steps

1.Just go to Snipe-IT URL in a web browser 
2.404 Not Found
nginx/1.23.2
3.
... cat /usr/local/nginx/logs/error.log 

2022/12/08 16:54:02 [error] 8588#0: *1 open() "/usr/local/nginx/html/snipeit/public/setup" failed (2: No such file or directory), client: 10.100.187.113, server: localhost, request: "GET /setup HTTP/1.1", host: "10.100.181.222

### Expected behavior

2022/12/08 16:54:02 [error] 8588#0: *1 open() "/usr/local/nginx/html/snipeit/public/setup" failed (2: No such file or directory), client: 10.100.187.113, server: localhost, request: "GET /setup HTTP/1.1"

### Screenshots

composer check-platform-reqs
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? 
Checking platform requirements for packages in the vendor dir
composer-runtime-api 2.2.2      success                                       
ext-bcmath           8.1.13     success                                       
ext-ctype            *          success provided by symfony/polyfill-ctype    
ext-curl             8.1.13     success                                       
ext-date             8.1.13     success                                       
ext-dom              20031129   success                                       
ext-fileinfo         8.1.13     success                                       
ext-filter           8.1.13     success                                       
ext-gd               8.1.13     success                                       
ext-hash             8.1.13     success                                       
ext-iconv            *          success provided by symfony/polyfill-iconv    
ext-json             8.1.13     success                                       
ext-libxml           8.1.13     success                                       
ext-mbstring         *          success provided by symfony/polyfill-mbstring 
ext-openssl          8.1.13     success                                       
ext-pcre             8.1.13     success                                       
ext-pdo              8.1.13     success                                       
ext-simplexml        8.1.13     success                                       
ext-sodium           8.1.13     success                                       
ext-tokenizer        8.1.13     success                                       
ext-xml              8.1.13     success                                       
ext-xmlreader        8.1.13     success                                       
ext-xmlwriter        8.1.13     success                                       
ext-zip              1.19.5     success                                       
ext-zlib             8.1.13     success                                       
php                  8.1.13     success                    

### Snipe-IT Version

snipe-it-6.0.13

### Operating System

alma 9

### Web Server

nginx-1.23.2

### PHP Version

php-8.1.13

### Operating System

windows 

### Browser

Chrome,Microsoft Edge Beta

### Error messages

```shell
#0 /usr/local/nginx/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php(32): Symfony\\Component\\HttpFoundation\\Request::create()
#1 /usr/local/nginx/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\SetRequestForConsole->bootstrap()
#2 /usr/local/nginx/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#3 /usr/local/nginx/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#4 /usr/local/nginx/html/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#5 {main}
"} 
[root@localhost logs]#
```

### Additional context

Download the Source
When you download the source, you're going to download a zip file containing all of the Snipe-IT files.

Download the the [latest release from Github](https://github.com/snipe/snipe-it/releases/latest).

**Comment by ccj9874** [comment]
Does that directory exist or no?

**Comment by hankunlun** [comment]
that directory exist

**Comment by hankunlun** [comment]
/html/snipeit/public/index.php exist ,no setup

**Comment by hankunlun** [comment]
localhost snipeit[1988]: No scheduled commands are ready to run.

**Comment by snipe** [comment]
My guess would be that your `APP_URL` is misconfigured in your `.env` file. [Per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings), the APP_URL should be the complete URL to your Snipe-IT installation, *including* the `http://` (or `https://` if you're running over TLS.)

<img width="795" alt="Screen Shot 2022-07-28 at 11 35 47 PM" src="https://user-images.githubusercontent.com/197404/181698021-de470225-4865-4786-bd48-9a9cdf2399d2.png">

**Comment by hankunlun** [comment]
谢谢你的回复，这个系统很好用，我已经解决了这个问题，还是谢谢你的热心帮助

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
