### ISSUE TITLE
500 Server Error on Create/Edit Asset Model

### ISSUE THREAD

**Issue by bremic9188** [grokability/snipe-it#12313]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Same as this: https://github.com/snipe/snipe-it/issues/11203

When going to create a new model or edit an existing one, I receive 500 server error.

Debug mode shows: The /var/www/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/snipeit/resources/views/models/edit.blade.php)

Checked all permissions and they are correct. Performing all the fixes in the thread above doesn't resolve. This just started after updating to latest version.

### Reproduction steps

Create a new Asset Model:

1. Select Settings
2. Select Asset Models
3. Select Create New, "500 Server Error" page displays.

Edit an existing Asset Model:

1. Select Settings
2. Select Asset Models
3. Select an existing asset model, then select Update icon, "500 Server Error" page displays.

### Expected behavior

Can create new or edit existing asset model.

### Snipe-IT Version

6.0.14

### Operating System

CentOS

### Web Server

Apache

### PHP Version

8.0.26

### Operating System

Windows

### Browser

Edge

### Error messages

```shell
The /var/www/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/snipeit/resources/views/models/edit.blade.php)

[previous exception] [object] (Exception(code: 0): The /var/www/snipeit/bootstrap/cache directory must be present and writable. at /var/www/snipeit/vendor/livewire/livewire/src/LivewireComponentsFinder.php:59)
[stacktrace]
#0 /var/www/snipeit/vendor/livewire/livewire/src/LivewireComponentsFinder.php(51): Livewire\\LivewireComponentsFinder->write()
#1 /var/www/snipeit/vendor/livewire/livewire/src/LivewireComponentsFinder.php(38): Livewire\\LivewireComponentsFinder->build()
#2 /var/www/snipeit/vendor/livewire/livewire/src/LivewireComponentsFinder.php(26): Livewire\\LivewireComponentsFinder->getManifest()
#3 /var/www/snipeit/vendor/livewire/livewire/src/LivewireManager.php(66): Livewire\\LivewireComponentsFinder->find()
#4 /var/www/snipeit/vendor/livewire/livewire/src/LivewireManager.php(84): Livewire\\LivewireManager->getClass()
#5 /var/www/snipeit/vendor/livewire/livewire/src/LifecycleManager.php(29): Livewire\\LivewireManager->getInstance()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Livewire\\LifecycleManager::Livewire\\{closure}()
#7 /var/www/snipeit/vendor/livewire/livewire/src/LifecycleManager.php(41): tap()
#8 /var/www/snipeit/vendor/livewire/livewire/src/LivewireManager.php(104): Livewire\\LifecycleManager::fromInitialRequest()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Livewire\\LivewireManager->mount()
#10 /var/www/snipeit/storage/framework/views/9677095b587e4eef590909fd7fdeeb2a40640498.php(31): Illuminate\\Support\\Facades\\Facade::__callStatic()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#14 /var/www/snipeit/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\CompilerEngineForIgnition->evaluatePath()
#16 /var/www/snipeit/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#17 /var/www/snipeit/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\CompilerEngineForIgnition->get()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(820): Illuminate\\Http\\Response->__construct()
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(789): Illuminate\\Routing\\Router::toResponse()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router->prepareResponse()
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#31 /var/www/snipeit/app/Http/Middleware/AssetCountForSidebar.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\AssetCountForSidebar->handle()
#33 /var/www/snipeit/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#35 /var/www/snipeit/app/Http/Middleware/CheckForTwoFactor.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckForTwoFactor->handle()
#37 /var/www/snipeit/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckUserIsActivated->handle()
#39 /var/www/snipeit/app/Http/Middleware/CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckLocale->handle()
#41 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#43 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#51 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#53 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /var/www/snipeit/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\\DisableBrowserCache->handle()
#56 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#58 /var/www/snipeit/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#60 /var/www/snipeit/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\PreventBackHistory->handle()
#62 /var/www/snipeit/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SecurityHeaders->handle()
#64 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#66 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#67 /var/www/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckForDebug->handle()
#69 /var/www/snipeit/app/Http/Middleware/CheckForSetup.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckForSetup->handle()
#71 /var/www/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#73 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#75 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#77 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#78 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#80 /var/www/snipeit/app/Http/Middleware/NoSessionStore.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\NoSessionStore->handle()
#82 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#84 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#85 /var/www/snipeit/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#86 {main}
```

**Comment by snipe** [comment]
The error message is telling you what's wrong. 

`The /var/www/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/snipeit/resources/views/models/edit.blade.php)`

**Comment by bremic9188** [comment]
Yep, it's telling me that but I've confirmed that directory is present and writable. Not sure how to make it more writable.

**Comment by snipe** [comment]
What are the permissions of the directory? Are you running SELinux?  A little more information would be helpful here.

Show me the output of `ls -al /var/www/snipeit/bootstrap`

**Comment by bremic9188** [comment]
We're on CentOS 7

ls -al /var/www/snipeit/bootstrap
total 12
drwxrwxr-x.  3 snipeitapp apache       54 Jan  5 12:50 .
drwxrwxr-x. 18 snipeitapp apache     4096 Jan  5 12:50 ..
-rw-rw-r--.  1 snipeitapp snipeitapp 1602 Jan  5 12:50 app.php
-rw-rw-r--.  1 snipeitapp snipeitapp 1079 Jan  5 12:50 autoload.php
drwxrwxrwx.  2 snipeitapp apache       64 Jan  5 12:50 cache

**Comment by bremic9188** [comment]
The other thread about this mentions livewire-components.php being created in the cache directory during upgrade. That isn't happening for me. Wondering if the absence of that file is causing this? But I'm not sure how to get that file.

**Comment by sonic12w** [comment]
I have the same issue, permission are looking the same:

> [root@snipe-it logs]# ls -al /var/www/html/snipeit/bootstrap/cache
> insgesamt 28
> drwxrwxrwx. 2 snipeitapp apache        64 23. Jan 07:12 .
> drwxr-xr-x. 3 snipeitapp apache        54 23. Jan 07:04 ..
> -rwxrwxr-x. 1 snipeitapp apache        14 23. Jan 07:04 .gitignore
> -rwxrwxr-x. 1 snipeitapp snipeitapp  4089 23. Jan 07:12 packages.php
> -rwxrwxr-x. 1 snipeitapp snipeitapp 18828 23. Jan 07:12 services.php
> [root@snipe-it logs]# 


OS is Rocky Linux 8.7

**Comment by ORTNP** [comment]
Same issue on Ubuntu 22.04.
![image](https://user-images.githubusercontent.com/115308053/214965459-acf4300c-b030-49f6-b95b-94d3e0461a49.png)

**Comment by ORTNP** [comment]
I found a workaround for now.
1. Go to your server's SnipeIT site (e.g., http://www.mysnipeit.com/").
2. Click "Create New" -> "Asset".
3. On the "Create New Asset" page, next to the "Model" field, click on "New".
4. This should bring up the Asset Model creation page.

**Comment by recursiodef** [comment]
Same problem here, i was able to create new models as ORTNP workaround, but still gett 500 error on edit.
Cache folder permission were set to 777 but still having permission error.

Turned out it was SELinux configuration.
**SOLVED** for running these SELinux commands for the **/var/www/html/snipe/bootstrap/cache** directory:

//give the directory a new default context. The part at the end is a regex.
`semanage fcontext -a -t httpd_sys_rw_content_t "/path/to/directory(/.*)?"`

// apply the default context to the directory
`restorecon -R /path/to/directory`

see more on this, here: https://unix.stackexchange.com/questions/116575/selinux-httpd-write-access-to-a-directory

EDIT: running snipeit on local centos8 webserver

**Comment by bremic9188** [comment]
@recursiodef Thank you! That fixed it for me.

**Comment by Supersaki** [comment]
I feel like this is still an issue/bug.

The cache folder had the correct(?) permissions of 755. Changing to 775 'fixed' the issue, which appears to be the creation of the livewire-components.php file.  However, this file is being created with the (in my case) 'apache' user, instead of the specified 'snipeit' user.

root@itinv01 [/var/www/snipeit/bootstrap/cache] #ls -lah
total 36K
drwxrwxr-x. 2 snipeit apache   91 Oct 10 15:41 .
drwxr-xr-x. 3 snipeit apache   51 Sep  6  2018 ..
-rwxrwxr-x. 1 snipeit apache   14 Sep  6  2018 .gitignore
-rw-r--r--. 1 apache  apache  369 Oct 10 15:41 livewire-components.php
-rwxrwxr-x. 1 snipeit apache 4.3K Aug 14 13:34 packages.php
-rwxrwxr-x. 1 snipeit apache  19K Aug 14 13:34 services.php
