### ISSUE TITLE
Install.sh issue on clean Ubuntu

### ISSUE THREAD

**Issue by Hektars** [grokability/snipe-it#12312]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Using ./install.sh file to install the Snipe-IT on clean Ubuntu, after installation when I try to access the setup webpage I always get HTTP Error 500.

### Reproduction steps

1. Installed fresh Ubuntu,
2. Downloaded and started install.sh file,
```  
wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh 
```
4. After installation went into located webpage and received HTTP Error 500 error
5. Went into SSH and typed 3 commands. (Thanks to a member boring10 in Discord)
```
sudo chown -R snipeitapp:www-data /var/www/html/snipeit
sudo usermod -a -G www-data snipeitapp
sudo find /var/www/html/snipeit -type f -exec chmod 664 {} \;
```
6. After that you can enter setup page!

### Expected behavior

Fix the install.sh or snipeit.sh file, so other people don't run into this problem. 

### Snipe-IT Version

v6.0.14 - build 9038 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Google Chrome

### Version

108

### Error messages

```shell
Apache log


[Thu Jan 05 16:14:33.728210 2023] [php7:error] [pid 72270] [client 192.168.100.22:53077] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187

```

Laravel log

```
[2023-01-05 16:12:31] production.ERROR: Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\Filesystem\Filesystem->put()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\Cache\FileStore->put()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\Cache\FileStore->forever()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\Cache\Repository->forever()
#6 /var/www/html {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187
Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\\Cache\\FileStore->put()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\\Cache\\FileStore->forever()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\\Cache\\Repository->forever()
#6 /var/www/html at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187)
[stacktrace]
#0 {main}

```
```


### Additional context

_No response_

**Comment by Hektars** [comment]
Issue fixed
