### ISSUE TITLE
LDAP sync throwing error 500

### ISSUE THREAD

**Issue by Pkumar22in** [grokability/snipe-it#12404]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have 7 installations of Snipe IT and 6 of them are working perfectly now, only 1 installation is having issues while syncing with LDAP server. Rest 6 Snipe IT installation as we integrated with same LDAP server and working fine. There is no issue with credentials as while I do test in LDAP configuration page I get perfect results.

### Reproduction steps

1. Hit the sync button on People page
2. I immediately get error 500 page.  
3. Nothing comes up in debug.
...

### Expected behavior

Expected behaviour is that Synch should have run and I should have been shown the list of synched users.

### Screenshots

<img width="1438" alt="Screenshot 2023-01-24 at 4 43 14 PM" src="https://user-images.githubusercontent.com/94165474/214277503-a9b8a4e6-a5cb-4f75-81cc-2bbd704f04e2.png">
<img width="1392" alt="Screenshot 2023-01-24 at 4 42 57 PM" src="https://user-images.githubusercontent.com/94165474/214277509-1f0a791b-f8a6-490a-b618-3ece20221f49.png">

### Snipe-IT Version

Version v6.0.14 - build 9038 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4

### Operating System

macOS

### Browser

Chrome

### Error messages

```shell
[2023-01-24 06:45:01] production.ERROR: The "-s" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"-s\" option does not exist. at /var/www/assets.edobest.org.ng/vendor/symfony/console/Input/ArgvInput.php:122)
[stacktrace]
#0 /var/www/assets.edobest.org.ng/vendor/symfony/console/Input/ArgvInput.php(104): Symfony\\Component\\Console\\Input\\ArgvInput->parseShortOptionSet()
#1 /var/www/assets.edobest.org.ng/vendor/symfony/console/Input/ArgvInput.php(84): Symfony\\Component\\Console\\Input\\ArgvInput->parseShortOption()
#2 /var/www/assets.edobest.org.ng/vendor/symfony/console/Input/ArgvInput.php(71): Symfony\\Component\\Console\\Input\\ArgvInput->parseToken()
#3 /var/www/assets.edobest.org.ng/vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#4 /var/www/assets.edobest.org.ng/vendor/symfony/console/Command/Command.php(257): Symfony\\Component\\Console\\Input\\Input->bind()
#5 /var/www/assets.edobest.org.ng/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#6 /var/www/assets.edobest.org.ng/vendor/symfony/console/Application.php(1024): Illuminate\\Console\\Command->run()
#7 /var/www/assets.edobest.org.ng/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#8 /var/www/assets.edobest.org.ng/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#9 /var/www/assets.edobest.org.ng/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#10 /var/www/assets.edobest.org.ng/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#11 /var/www/assets.edobest.org.ng/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#12 {main}
"}
```

**Comment by Pkumar22in** [comment]
Reinstallation of composer resolved the issue
