### ISSUE TITLE
General error: 1025 Error on rename - Permissions denied

### ISSUE THREAD

**Issue by mmaatt921** [grokability/snipe-it#12425]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm encountering a permissions issue during the database setup process, specifically on the '/setup/migrate' step. It seems there is a permissions issue somewhere, but I've followed the install guide (as well as other Snipe IT install guides) and have triple checked file permissions and the permissions of my 'snipeit' db user.

I'm using MariaDB 10.0.14 and php version 8.1.14.

Here is the error text:
Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1025 Error on rename of '.\snipeit\#sql-bf0_48' to '.\snipeit\settings' (errno: 13 "Permission denied") (SQL: alter table `settings` add `slack_endpoint` varchar(191) null, add `slack_channel` varchar(191) null, add `slack_botname` varchar(191) null)

I can drop the database and re-create it, but the same error happens again albeit with a different item that produces the error. It seems that the error most commonly effects the assets, users, or settings tables.

### Reproduction steps

1. Navigate to my Snipe IT setup page
2. Click 'Next: Create Database Tables'

### Expected behavior

It's expected that the database will be created and setup will be able to be completed

### Screenshots

![Capture](https://user-images.githubusercontent.com/23066016/215157917-72763268-864b-4679-8439-be6cdf70e17a.PNG)

### Snipe-IT Version

6.0.10

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.1.14

### Error messages

```shell
Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1025 Error on rename of '.\snipeit\#sql-bf0_48' to '.\snipeit\settings' (errno: 13 "Permission denied") (SQL: alter table `settings` add `slack_endpoint` varchar(191) null, add `slack_channel` varchar(191) null, add `slack_botname` varchar(191) null)

Stacktrace:

[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1025 Error on rename of '.\\snipeit\\#sql-bf0_48' to '.\\snipeit\\settings' (errno: 13 \"Permission denied\") at C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:501)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(501): PDOStatement->execute()
#1 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
#3 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(502): Illuminate\\Database\\Connection->run()
#4 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Blueprint.php(109): Illuminate\\Database\\Connection->statement()
#5 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(364): Illuminate\\Database\\Schema\\Blueprint->build()
#6 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(211): Illuminate\\Database\\Schema\\Builder->build()
#7 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Database\\Schema\\Builder->table()
#8 C:\\inetpub\\wwwroot\\snipeit\\database\\migrations\\2015_04_29_234704_add_slack_to_settings.php(19): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(472): AddSlackToSettings->up()
#10 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(394): Illuminate\\Database\\Migrations\\Migrator->runMethod()
#11 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(403): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(202): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#13 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(167): Illuminate\\Database\\Migrations\\Migrator->runUp()
#14 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(112): Illuminate\\Database\\Migrations\\Migrator->runPending()
#15 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\MigrateCommand.php(86): Illuminate\\Database\\Migrations\\Migrator->run()
#16 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(606): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#17 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\MigrateCommand.php(98): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#18 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#19 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call()
#23 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call()
#24 C:\\inetpub\\wwwroot\\snipeit\\vendor\\symfony\\console\\Command\\Command.php(298): Illuminate\\Console\\Command->execute()
#25 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#26 C:\\inetpub\\wwwroot\\snipeit\\vendor\\symfony\\console\\Application.php(1040): Illuminate\\Console\\Command->run()
#27 C:\\inetpub\\wwwroot\\snipeit\\vendor\\symfony\\console\\Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#28 C:\\inetpub\\wwwroot\\snipeit\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#29 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(94): Symfony\\Component\\Console\\Application->run()
#30 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(186): Illuminate\\Console\\Application->run()
#31 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(263): Illuminate\\Console\\Application->call()
#32 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
#33 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Controllers\\SettingsController.php(252): Illuminate\\Support\\Facades\\Facade::__callStatic()
#34 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\SettingsController->getSetupMigrate()
#35 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#36 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#37 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#38 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Route->run()
#39 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#40 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#42 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\AssetCountForSidebar.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\AssetCountForSidebar->handle()
#44 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#46 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckForTwoFactor.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForTwoFactor->handle()
#48 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckUserIsActivated.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckUserIsActivated->handle()
#50 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckLocale->handle()
#52 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#54 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#56 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#58 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#60 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#61 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRoute()
#62 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#63 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#64 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#65 C:\\inetpub\\wwwroot\\snipeit\\vendor\\livewire\\livewire\\src\\DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Livewire\\DisableBrowserCache->handle()
#67 C:\\inetpub\\wwwroot\\snipeit\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#69 C:\\inetpub\\wwwroot\\snipeit\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#71 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\PreventBackHistory.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\PreventBackHistory->handle()
#73 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\SecurityHeaders->handle()
#75 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#77 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#78 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForDebug->handle()
#80 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\CheckForSetup.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\CheckForSetup->handle()
#82 C:\\inetpub\\wwwroot\\snipeit\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#84 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#86 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#88 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#89 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#91 C:\\inetpub\\wwwroot\\snipeit\\app\\Http\\Middleware\\NoSessionStore.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\NoSessionStore->handle()
#93 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#95 C:\\inetpub\\wwwroot\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#96 C:\\inetpub\\wwwroot\\snipeit\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#97 {main}
```

### Additional context

This is a fresh install of SnipeIT that I have installed via git. I've not manually edited any data in the database, as I've not yet been able to get the database up and running!

**Comment by snipe** [comment]
So it sounds like your MySQL user doesn't have ALTER permissions? You'd need to grant your MySQL user ALTER privileges for migrations to run properly.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by gobindc** [comment]
@mmaatt921  did you ever resolve this? I am having the same issue. 
I verified that my DB user does have ALTER permissions as well.
