### ISSUE TITLE
Alerts do not work

### ISSUE THREAD

**Issue by deeepakkumarthakur16** [grokability/snipe-it#12539]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

No Email Alerts Sent Out from Snipe IT

### Reproduction steps

1. Enable Notification on Asset Category
2. Enable Notifications under notification for expiring alerts
3. run cron (/usr/bin/php /var/www/html/snipe/artisan snipeit:expiring-alerts) for expiring alerts
4.
5.
...

### Expected behavior

Email Alerts should be send out to user on check and Snipe it admin on expiring 

### Screenshots

<img width="566" alt="image" src="https://user-images.githubusercontent.com/64971445/220102200-94de069e-38a0-431f-b609-4608eb36d41c.png">

### Snipe-IT Version

 Version v5.1.8 - build 6227

### Operating System

Centos

### Web Server

Nginx

### PHP Version

7.4.32

### Error messages

```shell
No Error

[root@localhost snipe]# tail -f storage/logs/laravel.log
    snipeit:upcoming-audits
    snipeit:user-inventory at /var/www/html/snipe/vendor/symfony/console/Applica                                                                             tion.php:676)
[stacktrace]
#0 /var/www/html/snipe/vendor/symfony/console/Application.php(237): Symfony\\Com                                                                             ponent\\Console\\Application->find()
#1 /var/www/html/snipe/vendor/symfony/console/Application.php(149): Symfony\\Com                                                                             ponent\\Console\\Application->doRun()
#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Console/Applicati                                                                             on.php(93): Symfony\\Component\\Console\\Application->run()
#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Consol                                                                             e/Kernel.php(131): Illuminate\\Console\\Application->run()
#4 /var/www/html/snipe/artisan(35): Illuminate\\Foundation\\Console\\Kernel->han                                                                             dle()
#5 {main}
"}
```

### Additional context

 Fresh Install

**Comment by deeepakkumarthakur16** [comment]
@snipe After some further troubleshooting it start working as there was issue with mail driver. 

But can you please let me know why check-in alert showing 0 Assest and how it fetch assest for alert.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/64971445/220113865-d6e6e14c-267a-4a80-a1f7-1daa79dca09f.png">

**Comment by deeepakkumarthakur16** [comment]
Everything looks working fine. All was missing mail driver.
