### ISSUE TITLE
Backup notification - production.ERROR: InvalidArgumentException: Driver [smtp] not supported

### ISSUE THREAD

**Issue by prokki** [grokability/snipe-it#12775]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am not sure if this is a bug or if I have some inproper settings...

I get an error `Driver [smtp] not supported` every day because of the daily backup job. I wonder because the mail report about expiring assets is sent successfully without an log entry, the mail notification about the backup fails. So i checked the console commands:

No error:
```shell
$ php8.1 artisan snipeit:expiring-alerts
Die Garantie von 6 Assets wird in 30 Tagen auslaufen.
```

Error - see line **Sending notification failed**
```shell
php8.1 artisan backup:run
Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 316 files and directories...
Created zip containing 316 files and directories. Size is 676.58 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Sending notification failed
Backup completed!
```

As you can see, the backups are created successfully. The only part which is not working is the mail notification at the end of the backup script.

It might be a template error or maybe because other mail settings are used for backups? I am unable to get more into details :-(

My `.env` file:
```
[...]
MAIL_DRIVER=smtp
MAIL_HOST=***
MAIL_PORT=587
MAIL_USERNAME=***
MAIL_PASSWORD=***
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=***
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=***
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'
[...]
MAIL_BACKUP_NOTIFICATION_DRIVER=smtp
MAIL_BACKUP_NOTIFICATION_ADDRESS=***
BACKUP_ENV=true
ALLOW_BACKUP_DELETE=false
ALLOW_DATA_PURGE=false
[...]
```

My notification settings
![image](https://user-images.githubusercontent.com/5040666/229313344-055da958-8e31-42f6-841f-efdce6109646.png)

### Reproduction steps

run `php8.1 /var/www/snipeit.assistenz.de/git/artisan backup:run`

### Expected behavior

1. The backup mail should be sent successfully.
2. No error **Sending notification failed** in console command.

### Snipe-IT Version

v6.0.13 - build 8923 (master)

### Operating System

Debian GNU/Linux 10 (buster) 4.19.0-23-amd64 

### Web Server

apache2 2.4.38-3+deb10u9 amd64

### PHP Version

PHP 8.1.14

### Error messages

```shell
The log file `/storage/logs/laravel.log` contains following information:


[2023-04-01 00:00:04] production.ERROR: InvalidArgumentException: Driver [smtp] not supported. in /vendor/laravel/framework/src/Illuminate/Support/Manager.php:109
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(109): Illuminate\Support\Manager->createDriver()
#1 /vendor/laravel/framework/src/Illuminate/Support/Manager.php(80): Illuminate\Notifications\ChannelManager->createDriver()
#2 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\Support\Manager->driver()
#3 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#4 /vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#5 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#6 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow()
#7 /vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#8 /vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send()
#9 /vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify()
#10 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}()
#11 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#12 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\Events\Dispatcher->dispatch()
#13 /vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(47): event()
#14 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\CleanupCommand->handle()
#15 /vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#19 /vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#20 /vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#21 /vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#22 /vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run()
#23 /vendor/symfony/console/Application.php(1024): Spatie\Backup\Commands\BaseCommand->run()
#24 /vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#25 /vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#26 /vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#27 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#28 /artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#29 {main}  
[2023-04-01 00:00:05] production.ERROR: Driver [smtp] not supported. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [smtp] not supported. at /vendor/laravel/framework/src/Illuminate/Support/Manager.php:109)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(109): Illuminate\\Support\\Manager->createDriver()
#1 /vendor/laravel/framework/src/Illuminate/Support/Manager.php(80): Illuminate\\Notifications\\ChannelManager->createDriver()
#2 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Support\\Manager->driver()
#3 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#4 /vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#5 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\\Notifications\\NotificationSender->withLocale()
#6 /vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#7 /vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#8 /vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send()
#9 /vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\\Backup\\Notifications\\Notifiable->notify()
#10 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Spatie\\Backup\\Notifications\\EventHandler->Spatie\\Backup\\Notifications\\{closure}()
#11 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#12 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch()
#13 /vendor/spatie/laravel-backup/src/Commands/CleanupCommand.php(47): event()
#14 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\CleanupCommand->handle()
#15 /vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#19 /vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#20 /vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#21 /vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#22 /vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run()
#23 /vendor/symfony/console/Application.php(1024): Spatie\\Backup\\Commands\\BaseCommand->run()
#24 /vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#25 /vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#26 /vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#27 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#28 /artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#29 {main}
"}
```

**Comment by snipe** [comment]
According to the library's docs, "Out of the box you can use 'mail' and 'slack'." - Can you try using `mail` instead?

**Comment by ivkusan** [comment]
It took me a while to get from ```Driver [smtp] not supported``` to the real error which was a case of wrong mail account credentials for me.

**Comment by snipe** [comment]
Glad you're sorted :)

**Comment by prokki** [comment]
Best man @snipe !
Mail credentials are correct (otherwise the other mails would fail - written in my first post) but the hint to use `mail` instead of `smtp` is the right one. Many thanks

**Comment by snipe** [comment]
You're welcome, though I'm not a man ;)
