### ISSUE TITLE
Backup failed because The dump process failed with exitcode 1 : General error : Access is denied

### ISSUE THREAD

**Issue by beemestd** [grokability/snipe-it#12797]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello, I just testing the new version into my new server, however the Generate Backup was failed with this error message:  Backup failed because The dump process failed with exitcode 1 : General error : Access is denied. Already search from the previous ticket, but still can't process it. 

### Reproduction steps

1. Install New Version into the new server 
2. DB_DUMP_PATH='C:\\Progra~1\\MariaD~1.3\\bin'
3. Fixed permission as per documentation
4. >php artisan backup:run
Starting backup...
Dumping database dbitam...
Determining files to backup...
Zipping 58 files and directories...
Created zip containing 58 files and directories. Size is 30.92 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Backup completed!

### Expected behavior

Backup can be run from CMD and from the portal.

### Snipe-IT Version

Version v6.1.0-pre - build 10030 (develop)

### Operating System

Windows 2016

### Web Server

IIS

### PHP Version

8.0

### Operating System

Windows 2016

### Browser

Edge

### Error messages

```shell
Error Backup failed because The dump process failed with exitcode 1 : General error : Access is denied. . #0 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(260): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(695): array_map() #5 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(263): Illuminate\Support\Collection->map() #6 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(171): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(147): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #10 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #11 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #12 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #13 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call() #14 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call() #15 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Command\Command.php(298): Illuminate\Console\Command->execute() #16 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run() #17 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run() #18 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(1024): Spatie\Backup\Commands\BaseCommand->run() #19 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand() #20 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun() #21 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(94): Symfony\Component\Console\Application->run() #22 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(186): Illuminate\Console\Application->run() #23 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(263): Illuminate\Console\Application->call() #24 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #25 C:\inetpub\wwwroot\snipeit\app\Http\Controllers\SettingsController.php(1096): Illuminate\Support\Facades\Facade::__callStatic() #26 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #27 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #28 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch() #29 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController() #30 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Route->run() #31 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckPermissions.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckPermissions->handle() #34 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle() #36 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle() #38 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\AssetCountForSidebar.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle() #40 C:\inetpub\wwwroot\snipeit\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #42 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle() #44 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle() #46 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckLocale->handle() #48 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #50 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #52 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #53 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle() #54 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #55 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline->then() #56 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router->runRouteWithinStack() #57 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRoute() #58 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router->dispatchToRoute() #59 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch() #60 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #61 C:\inetpub\wwwroot\snipeit\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Livewire\DisableBrowserCache->handle() #63 C:\inetpub\wwwroot\snipeit\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #65 C:\inetpub\wwwroot\snipeit\vendor\fruitcake\laravel-cors\src\HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle() #67 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle() #69 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle() #71 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #73 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() #74 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #75 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle() #76 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #77 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle() #78 C:\inetpub\wwwroot\snipeit\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #79 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle() #80 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #81 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #82 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #83 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #84 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle() #85 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #86 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #87 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #88 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle() #89 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #90 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then() #91 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #92 C:\inetpub\wwwroot\snipeit\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle() #93 {main} Backup failed because: The dump process failed with exitcode 1 : General error : Access is denied. .
```

**Comment by snipe** [comment]
We haven't made any changes to the backup system in quite some time - is it possible your DB or filesystem permissions changed?

**Comment by aquadiode** [comment]
There was an issue https://github.com/snipe/snipe-it/issues/5733 suggesting to check permissions on storage and windows temp folders and having to add the local IIS_IUSRS. 
After fixing dump path, did you run:
composer dump-autoload
php artisan cache:clear 
php artisan config:clear

**Comment by beemestd** [comment]
> We haven't made any changes to the backup system in quite some time - is it possible your DB or filesystem permissions changed?

I've followed all the permission settings from the documentation, although when doing fresh installation , there was an 500 internal error message, after refresh many times in preflight setup, it can go through.  Let me try in another server to do simulate the installation.

**Comment by beemestd** [comment]
> There was an issue #5733 suggesting to check permissions on storage and windows temp folders and having to add the local IIS_IUSRS. After fixing dump path, did you run: composer dump-autoload php artisan cache:clear php artisan config:clear

Yes I did done that.. still got error message.

**Comment by 21Prash** [comment]
What I have found myself in is an error a bit more specific which required me to provide RELOAD permissions. It might be a similar solution to your problem. What I did was to provide permissions explicitly.

1. Log on to the SQL server as root user 
2. GRANT <PRIVILEGE_NAME> ON *.* TO 'username'@'host'; 
[For some reasons, my mysql version required me to allow permission to *.* instead of just one database but in my case its fine as the container I am using just has one database, so you might need to research on granular permission]
3. FLUSH PRIVILEGES;

After this, you might need to start the container/server again (Generally flush command makes it so that we needn't do a restart) and the changes should be reflected.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
