### ISSUE TITLE
Abstractprocessinghandler 

### ISSUE THREAD

**Issue by CLAVALCOLLECTION2** [grokability/snipe-it#12812]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Abstractprocessinghandler doesn't work so help me out 

### Reproduction steps

1.creat a code
2 open code
3.link the code to device 
...

### Expected behavior

Abstractprocessinghandler to function

### Screenshots

at RotatingFileHandler->write(array('message' => 'UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2023-04-11 05:23:43] local.ERROR: UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main} '))
in AbstractProcessingHandler.php line 39
at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2023-04-11 05:23:43] local.ERROR: UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main} '))

### Snipe-IT Version

Githud. Com

### Operating System

Android 

### Web Server

Chrome 

### PHP Version

Php line 39

### Operating System

Chrome 

### Browser

Chrome 

### Version

93

### Device

Android 

### Operating System

Android 8

### Browser

Chrome 

### Version

93

### Error messages

```shell
at RotatingFileHandler->write(array('message' => 'UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2023-04-11 05:23:43] local.ERROR: UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main} '))
in AbstractProcessingHandler.php line 39
at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2023-04-11 05:23:43] local.ERROR: UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main} '))
```

### Additional context

Fresh install. Google play store. Help me solve the problem.

**Comment by snipe** [comment]
I cannot actually parse what the question is here, but this:

```
 The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied
```

needs fixing before anything else. Fix your log permissions and then try asking this question again.
