### ISSUE TITLE
Receiving 403 Forbidden after restart of server

### ISSUE THREAD

**Issue by jonfuego** [grokability/snipe-it#13217]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am suddenly getting a 403 Forbidden when trying to access the app.  No changes have been made, only the server was restarted for VMWare maintenance.  I have check the permissions on the web folders and verified that they are as follows

var/www/snipeit/ 755
var/www/snipeit/storage 775
var/www/snipeit/public/uploads 775

apachectl configtest = Syntax OK

Virtual Host Setup:

<VirtualHost *:80>
  <Directory /var/www/snipeit/public>
      Allow From All
      AllowOverride All
      Options -Indexes
  </Directory>

  DocumentRoot /var/www/snipeit/public
  ServerName <host>.<mydomain>.com
</VirtualHost>

### Reproduction steps

1.Navigate to site
2. Receive 403 Error
3.
...

### Expected behavior

Login page should be presented.

### Snipe-IT Version

~5.3.9

### Operating System

CentOS 7

### Web Server

Apache

### PHP Version

7.3.27

### Error messages

```shell
Stack trace:
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(488): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Recipients\AlertRecipient), Object(App\Notifications\InventoryAlert))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Recipients\AlertRecipient), '9e17452b-a446-4...', Object(App\Notifications\InventoryAlert), 'mail')
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\InventoryAlert))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\InventoryAlert))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\InventoryAlert))
#13 /var/www/snipeit/app/Console/Commands/SendInventoryAlerts.php(55): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\SendInventoryAlerts->handle()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#20 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /var/www/snipeit/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/snipeit/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SendInventoryAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/snipeit/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}  
[2023-06-26 00:00:17] production.ERROR: Failed to authenticate on SMTP server with username "administrator@xxxxx.com" using 1 possible authenticators. Authenticator NTLM returned Expected response code 235 but got code "535", with message "535 5.7.3 Authentication unsuccessful
". {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"administrator@xxxxx.com\" using 1 possible authenticators. Authenticator NTLM returned Expected response code 235 but got code \"535\", with message \"535 5.7.3 Authentication unsuccessful
\". at /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191)
[stacktrace]
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(488): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\Models\\Recipients\\AlertRecipient), Object(App\\Notifications\\InventoryAlert))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\Models\\Recipients\\AlertRecipient), '9e17452b-a446-4...', Object(App\\Notifications\\InventoryAlert), 'mail')
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\\Notifications\\NotificationSender->withLocale(NULL, Object(Closure))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\InventoryAlert))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\InventoryAlert))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Notifications\\ChannelManager->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\InventoryAlert))
#13 /var/www/snipeit/app/Console/Commands/SendInventoryAlerts.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\SendInventoryAlerts->handle()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#20 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /var/www/snipeit/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/snipeit/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\SendInventoryAlerts), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /var/www/snipeit/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /var/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"} 





[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib
```

**Comment by marcusmoore** [comment]
Hi @jonfuego,

The logs you share doesn't seem to show anything helpful in this case but does show that there was an SMTP authentication error when trying to send the `InventoryAlert` notification (most likely from a scheduled job).

As for the 403...is it apache that is displaying the error? Does the page display something like `You don't have permission to access / on this server.`?

**Comment by jonfuego** [comment]
Ya, I did not include the SMTP error, since it was just complaining about an account that does not exist on an alert.

Yes, apache is displaying the error.  It started after a reboot of the server, without any changes made.  Based on the message ("You don't have permission to access / on this server."), I verified the folder permission on the site folder and everything looks ok.

**Comment by marcusmoore** [comment]
Hm...it's hard for me to say what could have happened. I wouldn't expect restarting the server to cause an issue but it seems like something changed on the host right before or after the restart. Is it possible the user running the process has been changed?

**Comment by jonfuego** [comment]
I am not super familiar with CentOS.  How would I find that info?  I am the only one that manages the server and I have not made any changes, but perhaps there was something staged that applied after a restart.

**Comment by jonfuego** [comment]
Do you mean the user running the httpd process?  That would be apache.  I verified that the site folder ownership is apache:apache

![image](https://github.com/snipe/snipe-it/assets/137959893/4d76ddc4-4db8-4a59-8b84-301bddf51781)

![image](https://github.com/snipe/snipe-it/assets/137959893/61135db5-840b-4a43-a783-7b35f3fbd58d)

**Comment by jonfuego** [comment]
Ended up just rebuilding the server and restoring from backup.
