### ISSUE TITLE
Generating Custom Report - Error

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13296]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

@marcusmoore When generating Custom Asset Report. .csv Report comes out missing all assets

<img width="1288" alt="Screenshot 2023-07-12 at 9 53 22 am" src="https://github.com/snipe/snipe-it/assets/114973646/3d534264-96bf-4924-974f-c49f3f8a2917">

### Reproduction steps

1. Custom Asset Report
2. tick all fields
3. Then generate
4. downloaded .csv
5. Opened .csv file (screenshot above)
6. Ran debug mode, Error log attached
...

### Expected behavior

.csv should have all asset information

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd) 

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

8.1.20 

### Error messages

```shell
[2023-07-12 09:50:21] production.ERROR: Error: Call to a member function belongsTo() on null in /home/server/public_html/asset/app/Models/Asset.php:393
Stack trace:
#0 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(539): App\Models\Asset->depreciation()
#1 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(491): Illuminate\Database\Eloquent\Model->getRelationshipFromMethod('depreciation')
#2 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(440): Illuminate\Database\Eloquent\Model->getRelationValue('depreciation')
#3 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2029): Illuminate\Database\Eloquent\Model->getAttribute('depreciation')
#4 /home/server/public_html/asset/app/Http/Controllers/ReportsController.php(822): Illuminate\Database\Eloquent\Model->__get('depreciation')
#5 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(51): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}(Object(Illuminate\Database\Eloquent\Collection), 1)
#6 /home/server/public_html/asset/app/Http/Controllers/ReportsController.php(881): Illuminate\Database\Eloquent\Builder->chunk(20, Object(Closure))
#7 /home/server/public_html/asset/vendor/symfony/http-foundation/StreamedResponse.php(109): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#8 /home/server/public_html/asset/vendor/symfony/http-foundation/Response.php(394): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#9 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Support/HigherOrderTapProxy.php(34): Symfony\Component\HttpFoundation\Response->send()
#10 /home/server/public_html/asset/public/index.php(53): Illuminate\Support\HigherOrderTapProxy->__call('send', Array)
#11 {main}  
[2023-07-12 09:50:21] production.ERROR: Call to a member function belongsTo() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function belongsTo() on null at /home/server/public_html/asset/app/Models/Asset.php:393)
[stacktrace]
#0 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(539): App\\Models\\Asset->depreciation()
#1 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(491): Illuminate\\Database\\Eloquent\\Model->getRelationshipFromMethod('depreciation')
#2 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(440): Illuminate\\Database\\Eloquent\\Model->getRelationValue('depreciation')
#3 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2029): Illuminate\\Database\\Eloquent\\Model->getAttribute('depreciation')
#4 /home/server/public_html/asset/app/Http/Controllers/ReportsController.php(822): Illuminate\\Database\\Eloquent\\Model->__get('depreciation')
#5 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(51): App\\Http\\Controllers\\ReportsController->App\\Http\\Controllers\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#6 /home/server/public_html/asset/app/Http/Controllers/ReportsController.php(881): Illuminate\\Database\\Eloquent\\Builder->chunk(20, Object(Closure))
#7 /home/server/public_html/asset/vendor/symfony/http-foundation/StreamedResponse.php(109): App\\Http\\Controllers\\ReportsController->App\\Http\\Controllers\\{closure}()
#8 /home/server/public_html/asset/vendor/symfony/http-foundation/Response.php(394): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#9 /home/server/public_html/asset/vendor/laravel/framework/src/Illuminate/Support/HigherOrderTapProxy.php(34): Symfony\\Component\\HttpFoundation\\Response->send()
#10 /home/server/public_html/asset/public/index.php(53): Illuminate\\Support\\HigherOrderTapProxy->__call('send', Array)
#11 {main}
"}
```

**Comment by jayavman** [comment]
Hi Initov, 

That updated line creates errors :>

**Comment by inietov** [comment]
> Hi Initov,
> 
> That updated line creates errors :>

Ugh, you're totally right. Give me a moment.

**Comment by inietov** [comment]
@jayavman thanks for your report and your patience, now the error in my branch is gone (I think). You can test it again if you like, but if not we can wait until (if?) it's merged.
