### ISSUE TITLE
HTML 500 before Pre-Flight

### ISSUE THREAD

**Issue by montag-0506** [grokability/snipe-it#13332]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm getting an HTML 500 error before Pre-Flight even though everything is configured as shown in the documentation.
The webserver is configured with 2 virtual hosts, because it hosts another webpage as well.

### Reproduction steps

1. edited .env file
2. edited and activated apache2 config
3. tried starting Pre-Flight and getting HTML Error 500

### Expected behavior

Starting Pre-Flight

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/129391495/83c55d70-d05d-413b-a0a2-5aa89f658478)

### Snipe-IT Version

6.1.2

### Operating System

Ubuntu 22.04.2 LTS

### Web Server

Apache2

### PHP Version

8.1

### Operating System

Windows 10

### Browser

Google Chrome

### Version

114.0.5735.199

### Error messages

```shell
HTML Error 500
```

### Additional context

Installation-method: manual installation via git
Apache2 is configured with 2 virtual hosts

**Comment by snipe** [comment]
Without log errors (Apache and Application logs) I'm not sure how we'd start to help here. This doesn't even look like an application level 500, more like a misconfigured web server.

You can try checking your config by running:

```
$ sudo apachectl configtest
```

**Comment by montag-0506** [comment]
[error.log](https://github.com/snipe/snipe-it/files/12095222/error.log)

Here you have my error.log from the apache server.
I ran the configtest command and it worked.
Only error was AH00558 but thats nothing to worry about

**Comment by snipe** [comment]
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20210902/mysqli (/usr/lib/php/20210902/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/mysqli.so (/usr/lib/php/20210902/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20210902/pdo_mysql (/usr/lib/php/20210902/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_mysql.so (/usr/lib/php/20210902/pdo_mysql.so: undefined symbol: 
```

I think that line might be the issue.

**Comment by montag-0506** [comment]
php-mysql is installed and activated in the php.ini file
still not working

**Comment by montag-0506** [comment]
everytime I try to access the virtual host with Snipe-IT, this shows up in the error.log
```
PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/inventar/storage/framework/views/052a1e5dadd57c668c291879b7449e49e9f44cf5.php): Failed to open stream: Permission denied in /var/www/inventar/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(169): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(55): Illuminate\\View\\Compilers\\BladeCompiler->compile()\n#4 /var/www/inventar/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()\n#5 /var/www/inventar/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()\n#6 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\CompilerEngineForIgnition->get()\n#7 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()\n#8 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()\n#9 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#10 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#11 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()\n#12 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()\n#13 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(585): Illuminate\\Routing\\ResponseFactory->view()\n#14 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#15 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#16 /var/www/inventar/app/Exceptions/Handler.php(133): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): App\\Exceptions\\Handler->render()\n#18 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(173): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#19 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#20 {main}\n  thrown in /var/www/inventar/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187
PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/inventar/storage/framework/views/052a1e5dadd57c668c291879b7449e49e9f44cf5.php): Failed to open stream: Permission denied in /var/www/inventar/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(169): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(55): Illuminate\\View\\Compilers\\BladeCompiler->compile()\n#4 /var/www/inventar/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()\n#5 /var/www/inventar/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()\n#6 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\CompilerEngineForIgnition->get()\n#7 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()\n#8 /var/www/inventar/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()\n#9 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#10 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#11 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()\n#12 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()\n#13 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(585): Illuminate\\Routing\\ResponseFactory->view()\n#14 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#15 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#16 /var/www/inventar/app/Exceptions/Handler.php(133): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): App\\Exceptions\\Handler->render()\n#18 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(173): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#19 /var/www/inventar/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(209): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#20 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#21 {main}\n  thrown in /var/www/inventar/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187
```

**Comment by montag-0506** [comment]
folder-rights are set to the main user of the system

**Comment by snipe** [comment]
That `/var/www/inventar/storage` directory and its subdirectories are clearly not writable. "Failed to open stream: Permission denied"

**Comment by montag-0506** [comment]
I tried root and the main user of the server (inventar) and both didn't work.
Which user should I use?

**Comment by montag-0506** [comment]
changed permission to www-data
now I'm getting 404 Not found because it redirects to srv-inventar-01.FQDN/setup

**Comment by montag-0506** [comment]
mod_rewrite wasn't enabled
