### ISSUE TITLE
The QR Code is generated and showing, but it's not in PDF format

### ISSUE THREAD

**Issue by aldoprogrammer** [grokability/snipe-it#13600]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

So before this, I got a problem which the QR code is not showing, after enabled the `debug `to `true`, then I find out that I should make a folder name **'barcodes'** inside of` public/upload`.

![barcode](https://github.com/snipe/snipe-it/assets/107610584/825b00da-e032-4a49-b8ec-e3ea9be689cb)
It solves the problem which the images of QR Code that not showing before, but when I clicked on the generate label on the left bottom on this path https://peminjaman.com/hardware/14, there is the QR code, but it's not in the PDF like how it expected.
![expected](https://github.com/snipe/snipe-it/assets/107610584/9e2286e9-93bb-455e-bee5-66693442e764)

And the barcode that I got is: 
![result](https://github.com/snipe/snipe-it/assets/107610584/9747caac-0708-46b2-a6fa-36e44e22a98c)

And below is what I see on my `Logs`
```
[2023-09-14 12:51:14] production.ERROR: file_put_contents(/www/wwwroot/peminjaman.com/public/uploads/barcodes/qr-23213213-14.png): Failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/www/wwwroot/peminjaman.com/public/uploads/barcodes/qr-23213213-14.png): Failed to open stream: No such file or directory at /www/wwwroot/peminjaman.com/app/Http/Controllers/Assets/AssetsController.php:495)#15 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#16 /www/wwwroot/peminjaman.com/app/Http/Middleware/CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#18 /www/wwwroot/peminjaman.com/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle()
#20 /www/wwwroot/peminjaman.com/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#22 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#24 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#26 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#28 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /www/wwwroot/peminjaman.comm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#30 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#31 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#32 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#33 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#34 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#35 /www/wwwroot/peminjaman.com/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#37 /www/wwwroot/peminjaman.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#39 /www/wwwroot/peminjaman.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#41 /www/wwwroot/peminjaman.com/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#43 /www/wwwroot/peminjaman.com/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#45 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#47 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#48 /www/wwwroot/peminjaman.com/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#50 /www/wwwroot/peminjaman.com/app/Http/Middleware/CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#52 /www/wwwroot/peminjaman.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#54 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#56 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#58 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#59 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#61 /www/wwwroot/peminjaman.com/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#63 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#65 /www/wwwroot/peminjaman.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#66 /www/wwwroot/peminjaman.com/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#67 {main}  
```

### Addition
I already set my `APP_URL=https://peminjaman.com` in my `.env `file, and I also have cleared the cache of Barcode in the `https://peminjaman.com/admin/barcodes` as it mention that I should clear the cache everytime I changed the barcodes setting.

### Expected behavior

The QR code should be display in PDF as how it expected on the demo web app.

### Snipe-IT Version

v6.1.2 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.0.26

**Comment by jayavman** [comment]
APP_URL=https://peminjaman.com/public

**Comment by snipe** [comment]
`public` shouldn’t be in the APP_URL, per the config docs.

https://snipe-it.readme.io/docs/configuration#required-basic-app-settings

![IMG_0763](https://github.com/snipe/snipe-it/assets/197404/46cd153a-6f33-4ddf-8b75-22b5e00bd36f)


<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#required-basic-app-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>

**Comment by aldoprogrammer** [comment]
I found the solution. So I have to change the Label setting in `admin/setting/labels`.
