### ISSUE TITLE
When using a database from another server, an error occurs during backup

### ISSUE THREAD

**Issue by RealfuRyZ** [grokability/snipe-it#13646]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In version v6.1.2, my system is CentOS7, and I used install.sh for installation. However, I changed the location of the database and used the MySQL database on another server. There is no problem in use, but an error occurs during backup. I checked the debug information, and the program seems to try to connect to the local database through snipe@localhost instead of correctly connecting to the remote database.

### Reproduction steps

1.Click Backup

### Expected behavior

Can correctly backup when using a remote database

### Snipe-IT Version

V6.1.2

### Operating System

CentOS 7

### Web Server

Nginx

### PHP Version

7.4.3

### Operating System

WIndows

### Browser

Edge

### Error messages

```shell
[2023-08-24 11:51:39] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_func()
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1100): Illuminate\Database\Connection->getPdo()
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\Database\Connection->getReadPdo()
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): Illuminate\Database\Connection->getPdoForSelect()
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(44): Illuminate\Database\Connection->select()
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\Database\Schema\MySqlBuilder->hasTable()
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(673): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#15 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(110): Illuminate\Database\Migrations\Migrator->repositoryExists()
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(78): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#17 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(606): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
#18 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(98): Illuminate\Database\Migrations\Migrator->usingConnection()
#19 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#22 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#24 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#25 /var/www/html/snipeit/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#26 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#27 /var/www/html/snipeit/vendor/symfony/console/Application.php(1024): Illuminate\Console\Command->run()
#28 /var/www/html/snipeit/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#29 /var/www/html/snipeit/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#30 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#31 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#32 /var/www/html/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#33 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = migrations and table_type = 'BASE TABLE') in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
Stack trace:
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(44): Illuminate\Database\Connection->select()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\Database\Schema\MySqlBuilder->hasTable()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(673): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(110): Illuminate\Database\Migrations\Migrator->repositoryExists()
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(78): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(606): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(98): Illuminate\Database\Migrations\Migrator->usingConnection()
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#15 /var/www/html/snipeit/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#17 /var/www/html/snipeit/vendor/symfony/console/Application.php(1024): Illuminate\Console\Command->run()
#18 /var/www/html/snipeit/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#19 /var/www/html/snipeit/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#21 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#22 /var/www/html/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#23 {main}
```

**Comment by snipe** [comment]
That might be a limitation of the backup library we're using (spatie backups). It doesn't come up often, so I haven't checked though.

**Comment by RealfuRyZ** [comment]
> That might be a limitation of the backup library we're using (spate backups). It doesn't come up often, so I haven't checked though.

Thank you for your reply! Could you tell me the path of the relevant php file after clicking the backup button on the administrator’s backup interface? I can troubleshoot it myself first.
