### ISSUE TITLE
Exception when running snipeit:ldap-sync in CLI

### ISSUE THREAD

**Issue by mattraggett** [grokability/snipe-it#13890]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When running the php artisan snipeit:ldap-sync in CLI and specifying a location name and a base_dn, the script fails with:

debug.INFO: ErrorException: Undefined variable $search_base in E:\inetpub\itassetmgmt.bloomsbury.com\app\Console\Commands\LdapSync.php:103

### Reproduction steps

1. Run the following in CLI: 

`php artisan snipeit:ldap-sync --location='blah' --base_dn='OU=blah,dc=google,dc=com'`

2. Result:

```
[2023-11-16 12:04:40] debug.INFO: ErrorException: Undefined variable $search_base in \app\Console\Commands\LdapSync.php:104
Stack trace:
#0 \app\Console\Commands\LdapSync.php(104): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\LdapSync->handle()
#2 \vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#4 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#5 \vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call()
#6 \vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call()
#7 \vendor\symfony\console\Command\Command.php(298): Illuminate\Console\Command->execute()
#8 \vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#9 \vendor\symfony\console\Application.php(1024): Illuminate\Console\Command->run()
#10 \vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#11 \vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun()
#12 \vendor\laravel\framework\src\Illuminate\Console\Application.php(94): Symfony\Component\Console\Application->run()
#13 \vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run()
#14 \artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#15 {main}
```

### Expected behavior

There shouldn't be an exception as the command arguments contain a base_dn value.

### Snipe-IT Version

6.2.3

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1.14

### Operating System

Windows

### Browser

n/a

### Version

n/a

### Additional context

Found a fix to the problem. Here is the git diff for it:

```
diff --git a/app/Console/Commands/LdapSync.php b/app/Console/Commands/LdapSync.php
index 1a8521487..ec2e61069 100755
--- a/app/Console/Commands/LdapSync.php
+++ b/app/Console/Commands/LdapSync.php
@@ -83,7 +83,7 @@ class LdapSync extends Command
         $summary = [];

         try {
-            if ( $this->option('location_id') != '') {
+            if (!empty($this->option('location_id'))) {

                 foreach($this->option('location_id') as $location_id){
                     $location_ou= Location::where('id', '=', $location_id)->value('ldap_ou');
```

**Comment by Godmartinz** [comment]
Thanks @mattraggett  for finding the bug and fixing it to! I put it in a PR and gave you a shout out.

**Comment by snipe** [comment]
This has been merged into master.
