### ISSUE TITLE
"Name does not resolve" on fresh install (Kubernetes)

### ISSUE THREAD

**Issue by niekvb** [grokability/snipe-it#14629]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm setting up a fresh installation in Kubernetes using the provided Docker image but am receiving the following exception when running the container: ` SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql
 failed: Name does not resolve`. This seems to be a result of the container trying to execute Laravel DB migrations.

### Reproduction steps

1. Run the equivalent Kubernetes manifests of the docker-compose file to start the container.
2. Observe `stdout` and see the exception popup as described below.

### Expected behavior

Laravel to execute it's DB migrations and start the application.

### Snipe-IT Version

`snipe/snipe-it:v6.3.4-alpine` (Docker image)

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.27

#### From `stdout`:
```shell

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for server.mysql.svc.cluster.local
 failed: Name does not resolve (SQL: select * from information_schema.tables where table_schema = 3rdp__snipeit
 and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +33 vendor frames
  34  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
Configuration cache cleared!
Configuration cache cleared!
Configuration cached successfully!
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.16.137.62. Set the 'ServerName' directive globally to suppress this message
```

#### `cat storage/logs/laravel.log`:
```plaintext
[2024-04-22 14:55:48] production.ERROR: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for server.mysql.svc.cluster.local
 failed: Name does not resolve in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_func()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1100): Illuminate\Database\Connection->getPdo()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\Database\Connection->getReadPdo()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): Illuminate\Database\Connection->getPdoForSelect()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(44): Illuminate\Database\Connection->select()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\Database\Schema\MySqlBuilder->hasTable()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(673): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(110): Illuminate\Database\Migrations\Migrator->repositoryExists()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(78): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(606): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(98): Illuminate\Database\Migrations\Migrator->usingConnection()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#25 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#27 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#28 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#29 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#32 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#33 {main}
```

#### `php -m`:
```plaintext
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
igbinary
json
ldap
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
redis
Reflection
session
SimpleXML
sockets
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zend_test
zip
zlib

[Zend Modules]
```

#### Context:
- This is a fresh install.
- Docker image and project source hasn't been modified.
- Using a MySQL server external to the image, in another k8s namespace linked by an external name.

#### I've tried to:
- Check if environment variables are parsed to the app container correctly. This is the case.
- Check if the MySQL server's hostname is resolved to the correct IP of the container using `nslookup mysql` from within the app container. This is the case.
- Sign in to the MySQL server from within the app container using the `mysql` command. This works flawlessly.
- Check if using another hostname/IP address of the MySQL container resolves the issue. This **isn't** the case.

I'm well aware that this issue might not be related to snipe-it directly and is caused by one of the underlying parts of Laravel or PHP itself but am hoping someone can shed some light on where to look to resolve the issue.

**Comment by snipe** [comment]
Which docker image did you use? We don't really deal with Kubernetes much here, but the name not resolving sounds like a kubernetes/networking issue, not an issue with Snipe-IT specifically.

**Comment by niekvb** [comment]
I'm using `snipe/snipe-it:v6.3.4-alpine`.

> sounds like a kubernetes/networking issue, not an issue with Snipe-IT specifically.

That's what I thought. Being able to connect to the MySQL container from within Snipe-IT's container via `mysql` CLI seems to suggest this is an issue with PDO's DNS resolution in some way.

I'll try digging a bit deeper, thanks for your quick response 🙏🏼

**Comment by niekvb** [comment]
The issue is resolved when setting env `DB_HOST=mysql` which seems logical but odd since the documentation specifies setting `MYSQL_PORT_3306_TCP_ADDR`.

**Comment by niekvb** [comment]
Well, this is embarrassing... I found newline chars in the MySQL env variables which are stored as base64 in the Kubernetes config files. I forgot to add `-n` while using `echo -n "VALUE" | base64` when setting up the config early this morning. 🫥

**Comment by snipe** [comment]
Heh - happens to the best of us :) Thanks for updating the ticket!
