### ISSUE TITLE
Having issue while genreating backup in snipe it  on Xampp server

### ISSUE THREAD

**Issue by Anmolinfo** [grokability/snipe-it#14874]
### Debug mode

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

 Error: Backup failed because The dump process failed with exitcode 1 : General error : '"C:\xampp\mysql/mysqldump"' is not recognized as an internal or external command, operable program or batch file. . #0 C:\xampp\htdocs\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\xampp\htdocs\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\xampp\\htdocs

### Reproduction steps

1.  Goto setting 
2.click on back up
3.it's showing General error
...

### Expected behavior

![Screenshot 2024-06-15 044211](https://github.com/snipe/snipe-it/assets/123134159/20a9cdbe-3336-4b23-ab30-c293a346267c)

### Screenshots

![Screenshot 2024-06-15 044211](https://github.com/snipe/snipe-it/assets/123134159/ca6e835a-59c2-4216-8bb5-430bede84cd5)

### Snipe-IT Version

v6.4.2

### Operating System

Windows

### Web Server

Apache

### PHP Version

 8.1.25 

### Operating System

Windows

### Browser

Google Chrome,

### Version

126.0.6478.61

**Comment by Anmolinfo** [comment]
i'm able to backup my data. i just changed my DB Dump path from 'C:\xampp\mysql\' to 'C:\xampp\mysql\bin'.

it's working
