### ISSUE TITLE
v7.0+ 500 Error on Server Startup When Using SSL

### ISSUE THREAD

**Issue by prboyer** [grokability/snipe-it#14901]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When using a Snipe-IT Docker image > v7.0.0, the application is inaccessible over HTTPS. I am able to access the app as expected via HTTPS on v6.4.2. I am using Let's Encrypt to provide certificates for the application.

### Reproduction steps

1. Set Docker Compose file to use the [v7.0.3 image tag](https://hub.docker.com/layers/snipe/snipe-it/v7.0.3/images/sha256-9fa859bf6c7e11bb85a9152b5cb96e7ac2ecf7d5a3b5b73a5bd33d28428dd9a7?context=explore)
2. Set `APP_URL=https://snipe.contoso.com`
3. Start containerized Snipe instance by running `docker-compose up -d`
4. Navigate to `https://snipe.contoso.com` in browser
5. 500 error presented in browser

### Expected behavior

1. Set Docker Compose file to use the [v7.0.3 image tag](https://hub.docker.com/layers/snipe/snipe-it/v7.0.3/images/sha256-9fa859bf6c7e11bb85a9152b5cb96e7ac2ecf7d5a3b5b73a5bd33d28428dd9a7?context=explore)
2. Set `APP_URL=https://snipe.contoso.com`
3. Start containerized Snipe instance by running `docker-compose up -d`
4. Navigate to `https://snipe.contoso.com` in browser
5. Snipe application is served to user. Proceed with setting up new Snipe instance via the wizard 

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/6655042/7b35468b-1456-4f22-8706-a955e0feff90)

### Snipe-IT Version

7.0.3

### Operating System

Docker (Ubuntu)

### Web Server

Apache 2.4.52

### PHP Version

8.1.2

### Operating System

Windows 11 23H2 (22631.3593)

### Browser

Microsoft Edge

### Version

126.0.2592.61 (Official build) (64-bit) 

### Error messages

```shell
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://snipe.contoso.com/.env

GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://wsb-as-snipe-01.wsb.wisc.edu/.env in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1252): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1218): Illuminate\Http\Client\PendingRequest->Illuminate\Http\Client\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1204): Illuminate\Http\Client\PendingRequest->Illuminate\Http\Client\{closure}()
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): Illuminate\Http\Client\PendingRequest->Illuminate\Http\Client\{closure}()
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(38): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#13 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\HandlerStack->__invoke()
#14 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(169): GuzzleHttp\Client->transfer()
#15 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Client->requestAsync()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1049): GuzzleHttp\Client->request()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(894): Illuminate\Http\Client\PendingRequest->sendRequest()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\Http\Client\PendingRequest->Illuminate\Http\Client\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(934): retry()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(771): Illuminate\Http\Client\PendingRequest->send()
#21 /var/www/html/app/Http/Controllers/SettingsController.php(140): Illuminate\Http\Client\PendingRequest->get()
#22 /var/www/html/app/Http/Controllers/SettingsController.php(76): App\Http\Controllers\SettingsController->dotEnvFileIsExposed()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\SettingsController->getSetupIndex()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\AuthenticateSession->handle()
#31 /var/www/html/app/Http/Middleware/AssetCountForSidebar.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\AssetCountForSidebar->handle()
#33 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#35 /var/www/html/app/Http/Middleware/CheckForTwoFactor.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForTwoFactor->handle()
#37 /var/www/html/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckUserIsActivated->handle()
#39 /var/www/html/app/Http/Middleware/CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckLocale->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\Pipeline\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#54 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\DisableBrowserCache->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle()
#58 /var/www/html/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\PreventBackHistory->handle()
#60 /var/www/html/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\SecurityHeaders->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#65 /var/www/html/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForDebug->handle()
#67 /var/www/html/app/Http/Middleware/CheckForSetup.php(32): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForSetup->handle()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle()
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#76 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\NoSessionStore->handle()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#81 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#82 {main}



[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
json
ldap
libxml
mbstring
mcrypt
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

Docker installation on a fresh Ubuntu 22.04 LTS server.

**Comment by prboyer** [comment]
I had previously commented in #14878 , but I think this is something unrelated (despite it also throwing a 500 error).

**Comment by prboyer** [comment]
Here are other things that I've tried (only changing one variable at a time) with no success:
1. Updated my Docker Compose file to use v7.0.4. 
2. Change the name of the environment file from `snipe.env` --> `.env`
3. Enabling `APP_FORCE_TLS=true` in the environment file
4. Enabling `APP_FORCE_TLS=true` in the environment file and setting the `APP_URL` to HTTP (instead of HTTPS)

**Comment by shiny-sand** [comment]
Thanks, "APP_FORCE_TLS=true" resolved this issue for me. In case it helps, here is my compose file. 

`---
version: "2.1"
services:
  snipe-it:
    hostname: snipeit.example.com
    image: lscr.io/linuxserver/snipe-it:latest
     container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - APP_ENV=production
      - APP_URL=https://snipeit.example.com
      - APP_DEBUG=false
      - APP_LOG_LEVEL=warning
      - APP_FORCE_TLS=true
      - APP_KEY=base64:**********
      - APP_TIMEZONE=Europe/Copenhagen
      - APP_LOCALE=en
      - MYSQL_PORT_3306_TCP_ADDR=192.168.*.*
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=******
      - MAIL_PORT_465_TCP_ADDR=smtp.example.com
      - MAIL_PORT_465_TCP_PORT=465
      - MAIL_ENV_FROM_ADDR=snipeit@example.com
      - MAIL_ENV_FROM_NAME=SnipeIT example.com
      - MAIL_ENV_ENCRYPTION=SSL
      - MAIL_ENV_USERNAME=me@example.com
      - MAIL_ENV_PASSWORD=****
      - APP_TRUSTED_PROXIES=192.168.*.*
      - ALLOW_IFRAMING=true
      - PHP_UPLOAD_LIMIT=100      
     
    volumes:
      - /localfolder:/config
      - /localfolder/backups/:/snipeit_backup
    ports:
      - 8087:80
    restart: unless-stopped`

**Comment by prboyer** [comment]
> Thanks, "APP_FORCE_TLS=true" resolved this issue for me. In case it helps, here is my compose file.
> 
> ## `
> version: "2.1" services: snipe-it: hostname: snipeit.example.com image: lscr.io/linuxserver/snipe-it:latest container_name: snipe-it environment: - PUID=1000 - PGID=1000 - APP_ENV=production - APP_URL=https://snipeit.example.com - APP_DEBUG=false - APP_LOG_LEVEL=warning - APP_FORCE_TLS=true - APP_KEY=base64:********** - APP_TIMEZONE=Europe/Copenhagen - APP_LOCALE=en - MYSQL_PORT_3306_TCP_ADDR=192.168._._ - MYSQL_PORT_3306_TCP_PORT=3306 - MYSQL_DATABASE=snipeit - MYSQL_USER=snipeit - MYSQL_PASSWORD=****** - MAIL_PORT_465_TCP_ADDR=smtp.example.com - MAIL_PORT_465_TCP_PORT=465 - MAIL_ENV_FROM_ADDR=[snipeit@example.com](mailto:snipeit@example.com) - MAIL_ENV_FROM_NAME=SnipeIT example.com - MAIL_ENV_ENCRYPTION=SSL - MAIL_ENV_USERNAME=[me@example.com](mailto:me@example.com) - MAIL_ENV_PASSWORD=**** - APP_TRUSTED_PROXIES=192.168._._ - ALLOW_IFRAMING=true - PHP_UPLOAD_LIMIT=100
> 
> ```
> volumes:
>   - /localfolder:/config
>   - /localfolder/backups/:/snipeit_backup
> ports:
>   - 8087:80
> restart: unless-stopped 
> ```
> 
> `

It looks like you are using a different Docker image than the [official Snipe-IT image](https://hub.docker.com/r/snipe/snipe-it/). However, looking at [the image you used](https://hub.docker.com/layers/linuxserver/snipe-it/7.0.3/images/sha256-36dd50b8c5f367ae99a58d55290b8bef680161f6823ccbe35734221fd04aa46e?context=explore) it appears to just be a fork of @snipe's image anyway, so it really shouldn't matter.

For the sake of complete-ness, here is my compose file:
```yaml
version: "3.2"

services:
  snipeit:
    container_name: snipe-app
    image: snipe/snipe-it:v7.0.3
    env_file:
      - ./snipe.env
    environment:
      - DB_PASSWORD=/run/secrets/db_password
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - webroot:/var/www/html/public
    - ./certbot/conf/live/${CERTBOT_HOST}/cert.pem:/var/lib/snipeit/ssl/snipeit-ssl.crt
    - ./certbot/conf/live/${CERTBOT_HOST}/privkey.pem:/var/lib/snipeit/ssl/snipeit-ssl.key
    depends_on:
      - mysql
      - redis
    networks:
    - snipeit-backend
    secrets:
    - db_password

  mysql:
    container_name: snipe-db
    image: mysql:8.4
    env_file:
      - ./snipe.env
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
      - MYSQL_PASSWORD=/run/secrets/db_password
    volumes:
      - sql-vol:/var/lib/mysql
    expose:
      - "3306"
    networks:
    - snipeit-backend
    secrets:
    - db_password
    - db_root_password

  redis:
    image: redis:6.2.5-buster
    networks:
    - snipeit-backend

  certbot:
    image: certbot/certbot:latest
    volumes:
    - webroot:/var/www/html
    - certbot:/etc/letsencrypt

volumes:
  sql-vol:
    driver: "local"
    driver_opts:
      type: none
      device: "./data"
      o: bind
  webroot:
    driver: "local"
    driver_opts:
      type: none
      device: "./www"
      o: bind
  certbot:
    driver: "local"
    driver_opts:
      type: none
      device: "./certbot/conf"
      o: bind

networks:
  snipeit-backend: {}

secrets:
  db_password:
    file: ./secrets/db_password
  db_root_password:
    file: ./secrets/db_root_password
```

**Comment by prboyer** [comment]
### **Resolved**
After thinking on this for some time, I Googled the error and [this post on StackOverflow](https://stackoverflow.com/a/24618403) lead me in the right direction. Understanding that it was a certificate issue, this post lead me to think about if the Let's Encrypt Root CA was trusted by the Snipe-IT container.

This lead me to review [Certbot's documentation](https://eff-certbot.readthedocs.io/en/latest/using.html#where-are-my-certificates), I thought I'd start by testing what would happen if I used the `fullchain.pem` certificate instead of `cert.pem`. Surely, this should take care of any CA validation issues since the trusted root would be included in the certificate chain (rather than trusting that the Root CA's cert is cached in the app's container). Sure enough, this resolved the SSL issue! 

This checks out with what the Certbot website cites in relation to Apache
> This is what Apache needs for [SSLCertificateKeyFile](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatekeyfile), and Nginx for [ssl_certificate_key](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate_key).

Validated that this fix applies to v7.0.3 - v7.0.6

**Comment by snipe** [comment]
Great to hear! And thanks so much for the detailed playback. I’m certain other folks will benefit from this. 🙏

**Comment by Salahzaar** [comment]
Hi, same error for here with manual installation on VM:
- Debian 12
- Nginx
- Mariadb
- php 8.2

I've generated a fullchain certificate as usual with my own CA:
```bash
FQDN=snipe-it.domain.com
cat certs/${FQDN}.cert.pem certs/ca.cert.pem > certs/${FQDN}-fullchain.cert.pem
```
/etc/nginx/sites-availables/snipe-it:
```bash
...
ssl_certificate /etc/ssl/certs/snipe-it.domain.com-fullchain.cert.pem;
ssl_certificate_key /etc/ssl/private/snipe-it.domain.com.key.pem;
...
```
So i didn't understand why i've got this error.

**Solution**:
Add your CA key to /etc/ssl/certs/ca-certificates.crt
```bash
cat ca.cert.pem >> /etc/ssl/certs/ca-certificates.crt
```

**Comment by prboyer** [comment]
@szpx did you rename your certificates? I discovered that Snipe-IT is hard coded to check for two file names:
1. `snipeit-ssl.crt`
2. `snipeit-ssl.key`
At least that's been my experience from trying to serve the site using Docker. If you're running behind Nginix as a reverse proxy, you've got some more flexibility.
