### ISSUE TITLE
Pre Flight Setup page not loading (Similar to #14326)

### ISSUE THREAD

**Issue by fowlerc74** [grokability/snipe-it#15142]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am having issues getting the Pre Flight Setup page to show up. Currently when trying to navigate to the page I just get a loading icon in the tab and nothing else happens. I replaced index.php with one that just had phpinfo() and it displayed correctly, so I don't think that it is an issue with my server configuration. Any help is greatly appreciated!

### Reproduction steps

1. Follow the installation documentation using git clone.
2. Attempt to open the preflight setup page.

### Expected behavior

The preflight setup page should show up.

### Snipe-IT Version

7.0.9

### Operating System

Ubuntu server

### Web Server

Apache

### PHP Version

8.3.6

### Operating System

Windows

### Browser

Chrome and Firefox

### Error messages

```shell
No errors in browser's console since I can't even get the page to open.
Apache Logs:
[Tue Jul 23 12:26:55.574222 2024] [mpm_prefork:notice] [pid 12725] AH00163: Apache/2.4.58 (Ubuntu) configured -- resuming normal operations
[Tue Jul 23 12:26:55.574236 2024] [mpm_prefork:info] [pid 12725] AH00164: Server built: 2024-07-17T18:55:23
[Tue Jul 23 12:26:55.574250 2024] [core:notice] [pid 12725] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 23 12:26:55.574255 2024] [core:debug] [pid 12725] log.c(1597): AH02639: Using SO_REUSEPORT: yes (1)
[Tue Jul 23 12:26:55.574259 2024] [mpm_prefork:debug] [pid 12725] prefork.c(970): AH00165: Accept mutex: none (default: pthread)
[Tue Jul 23 12:26:55.575018 2024] [watchdog:debug] [pid 12729] mod_watchdog.c(559): AH02980: Watchdog: nothing configured?
[Tue Jul 23 12:26:55.575824 2024] [watchdog:debug] [pid 12730] mod_watchdog.c(559): AH02980: Watchdog: nothing configured?
[Tue Jul 23 12:26:55.576352 2024] [watchdog:debug] [pid 12731] mod_watchdog.c(559): AH02980: Watchdog: nothing configured?
[Tue Jul 23 12:27:01.370137 2024] [authz_core:debug] [pid 12727] mod_authz_core.c(815): [client 74.118.238.169:46095] AH01626: authorization result of Require all granted: granted
[Tue Jul 23 12:27:01.370210 2024] [authz_core:debug] [pid 12727] mod_authz_core.c(815): [client 74.118.238.169:46095] AH01626: authorization result of <RequireAny>: granted
[Tue Jul 23 12:27:01.370353 2024] [authz_core:debug] [pid 12727] mod_authz_core.c(815): [client 74.118.238.169:46095] AH01626: authorization result of Require all granted: granted
[Tue Jul 23 12:27:01.370360 2024] [authz_core:debug] [pid 12727] mod_authz_core.c(815): [client 74.118.238.169:46095] AH01626: authorization result of <RequireAny>: granted
[Tue Jul 23 12:27:01.585084 2024] [watchdog:debug] [pid 12733] mod_watchdog.c(559): AH02980: Watchdog: nothing configured?
[Tue Jul 23 12:27:01.693710 2024] [php:info] [pid 12727] [client 74.118.238.169:46095] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/snipeit/app/Models/License.php on line 188
[Tue Jul 23 12:27:01.693771 2024] [php:info] [pid 12727] [client 74.118.238.169:46095] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/snipeit/app/Models/License.php on line 220
[Tue Jul 23 12:31:02.109326 2024] [authz_core:debug] [pid 12728] mod_authz_core.c(815): [client 74.118.238.169:52864] AH01626: authorization result of Require all granted: granted
[Tue Jul 23 12:31:02.109378 2024] [authz_core:debug] [pid 12728] mod_authz_core.c(815): [client 74.118.238.169:52864] AH01626: authorization result of <RequireAny>: granted

storage/logs:
[2024-07-22 14:15:01] production.ERROR: file_put_contents(/var/www/snipeit/storage/framework/sessions/aMtrfIJHp9PHRBoCvwc0tikvUGsZiJMbjJ7srR1O): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/snipeit/storage/framework/sessions/aMtrfIJHp9PHRBoCvwc0tikvUGsZiJMbjJ7srR1O): Failed to open stream: Permission denied at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:204)
[stacktrace]
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(204): file_put_contents()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(90): Illuminate\\Filesystem\\Filesystem->put()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Store.php(172): Illuminate\\Session\\FileSessionHandler->write()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\\Session\\Store->save()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(130): Illuminate\\Session\\Middleware\\StartSession->saveSession()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#11 /var/www/snipeit/app/Http/Middleware/NoSessionStore.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\NoSessionStore->handle()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#16 /var/www/snipeit/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#17 {main}
"} 
This was happening when I was trying to get it to work yesterday but after changing permissions in storage I stopped getting this message.

$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

Fresh Install
Ubuntu Server and Apache2
Manual installation (git clone)
I've followed the installation directions as closely as possible and included the error messages I got. I had some issues configuring the web server but I'm pretty sure I have fixed those.
Also, I went into the code and changed the ${...} to {$...} at those two spots that were in the logs and it did not make a difference so I changed it back to how it was.

**Comment by fowlerc74** [comment]
Tried running a php development server on localhost to see if I could narrow down the problem. I changed the app url in .env to be http://localhost:8000.

`/var/www/snipeit/public$ php -S localhost:8000
[Tue Jul 23 15:16:08 2024] PHP 8.3.6 Development Server (http://localhost:8000) started
[Tue Jul 23 15:16:11 2024] 127.0.0.1:57900 Accepted
[Tue Jul 23 15:16:11 2024] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/snipeit/app/Models/License.php on line 188
[Tue Jul 23 15:16:11 2024] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/snipeit/app/Models/License.php on line 220
^C^C[Tue Jul 23 15:16:22 2024] 127.0.0.1:57900 [302]: GET /
[Tue Jul 23 15:16:22 2024] 127.0.0.1:57900 Closing`

I used curl on the same machine to make a request to localhost:8000 and it accepted the request, gave me the same PHP Deprecated message I was getting in the logs, and then hanging. The response was not sent as long as I waited, so I hit control c to stop the server. After hitting control c a second time, the response was sent and then the server closed. 

curl localhost:8000
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='http://localhost:8000/setup'" />

        <title>Redirecting to http://localhost:8000/setup</title>
    </head>
    <body>
        Redirecting to <a href="http://localhost:8000/setup">http://localhost:8000/setup</a>.
    </body>

I tried to curl localhost:8000/setup and it wouldn't give me a response after any amount of time, even after trying to stop the server with control c. I ended up having to use kill to stop the server. 

I have no clue why it is hanging before sending the response. I don't know php / laravel programming so I don't know where to look in the code to narrow down the issue any further.

Edit: After running it again it turns out I do get a response from localhost:8000, but only after 4 minutes. The response always comes exactly at 4 minutes as well. I didn't get a response from localhost:setup after letting it run for over 15 minutes.

**Comment by snipe** [comment]
I think this might have been addressed in https://github.com/snipe/snipe-it/pull/15147 ?

**Comment by fowlerc74** [comment]
Thank you for responding! I did a git pull and when I ran it again I got these errors.

[2024-07-24 08:50:02] production.ERROR: Exception: The /var/www/snipeit/bootstrap/cache directory must be present and writable. in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(131): Illuminate\Foundation\PackageManifest->write()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(107): Illuminate\Foundation\PackageManifest->build()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(90): Illuminate\Foundation\PackageManifest->getManifest()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(79): Illuminate\Foundation\PackageManifest->config()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#9 /var/www/snipeit/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#10 {main}  
[2024-07-24 08:50:02] production.ERROR: The /var/www/snipeit/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/www/snipeit/bootstrap/cache directory must be present and writable. at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178)
[stacktrace]
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(131): Illuminate\\Foundation\\PackageManifest->write()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(107): Illuminate\\Foundation\\PackageManifest->build()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(90): Illuminate\\Foundation\\PackageManifest->getManifest()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(79): Illuminate\\Foundation\\PackageManifest->config()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#9 /var/www/snipeit/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#10 {main}
"} 
[2024-07-24 08:50:02] production.ERROR: ReflectionException: Class "session" does not exist in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:912
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\Foundation\Application->make()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\Container\Container->resolveClass()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\Container\Container->resolveDependencies()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\Foundation\Application->make()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\Foundation\Http\Kernel->terminateMiddleware()
#14 /var/www/snipeit/public/index.php(55): Illuminate\Foundation\Http\Kernel->terminate()
#15 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [session] does not exist. in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:914
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\Foundation\Application->make()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\Container\Container->resolveClass()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\Container\Container->resolveDependencies()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\Foundation\Application->make()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\Foundation\Http\Kernel->terminateMiddleware()
#13 /var/www/snipeit/public/index.php(55): Illuminate\Foundation\Http\Kernel->terminate()
#14 {main}  
[2024-07-24 08:50:02] production.ERROR: Target class [session] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [session] does not exist. at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:914)
[stacktrace]
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\\Container\\Container->resolve()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\\Container\\Container->make()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\\Container\\Container->resolve()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\\Container\\Container->make()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#13 /var/www/snipeit/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#14 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"session\" does not exist at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:912)
[stacktrace]
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct()
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\\Container\\Container->resolve()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\\Container\\Container->make()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\\Container\\Container->resolve()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\\Container\\Container->make()
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#14 /var/www/snipeit/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#15 {main}
"} 

I changed the permissions of the bootstrap/cache directory and the errors went away, but it just went back to hanging. I am not using https if that makes a difference.

**Comment by snipe** [comment]
> The /var/www/snipeit/bootstrap/cache directory must be present and writable. 

That's a different issue. That directory needs to be, well, present and writable.

**Comment by snipe** [comment]
> The response always comes exactly at 4 minutes as well. I didn't get a response from localhost:setup after letting it run for over 15 minutes.

Huh. So it's timing out when it's doing the env check.

@uberbrady any thoughts on this?

**Comment by snipe** [comment]
Hi there - I know this is a pretty old issue, but I wanted to check and see if you ever got this resolved? If so, can you please close the ticket? If not, can you update us on what version of Snipe-IT you're currently using, so we can see if it's still an issue on latest?

:) Thanks!

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
