### ISSUE TITLE
Backup error using by browser.

### ISSUE THREAD

**Issue by trongbn92** [grokability/snipe-it#15475]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Because my programming skills are not good. So I want to ask how to fix the error problem when backing up the database.
I have already authorized IUSR and IIS_.
Please help how to fix the error when I back up: "Can't create TCP/IP socket (10106) when trying to connect"

Many thanks!!!

### Reproduction steps

1. Turn on XAMPP
2. Start snipe server by .BAT 
"@echo off
set snipe_it_dir=c:\xampp\htdocs\snipe-it
cd %snipe_it_dir%
php artisan key:generate
php artisan serve
4. Open snipe by browser
5. setting -> make backup
6. See error
...

### Expected behavior

I hope no more errors when backup

### Screenshots

![image](https://github.com/user-attachments/assets/0affd7fc-325b-4cb3-98ea-989d3d9afa3c)

![image](https://github.com/user-attachments/assets/b400f379-df73-42f4-a7a4-8beadbc30acb)

### Snipe-IT Version

v7.0.11 build 14904 (g6c0cf9447)

### Operating System

Windows

### Web Server

XAMPP

### PHP Version

8.2.12

### Operating System

Windows

### Browser

Google Chrome (CocCoc)

### Error messages

```shell
Error: Backup failed because: The dump process failed with a none successful exitcode. Exitcode ======== 2: Misuse of shell builtins Output ====== <no output> Error Output ============ mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106)" when trying to connect . #0 C:\xampp\htdocs\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(194): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\xampp\htdocs\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(161): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\xampp\\htdocs
```

**Comment by sprengdu** [comment]
I have exactly the same problem. After upgrading from v7.0.13 to v7.1.15.

**Comment by snipe** [comment]
This has been documented 100 times. I’m going to close this for now, but if you’re still having issues, feel free to reopen.
