### ISSUE TITLE
Multiple Clients are not showing

### ISSUE THREAD

**Issue by adityakiran55** [grokability/snipe-it#15484]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have around 14 Clients in that i have recently added one client which was not showing while assign the assets to that client
![Screenshot 2024-09-10 222246](https://github.com/user-attachments/assets/ede85970-3858-41a5-8af8-a1633013e747)

### Reproduction steps

1.Windows 11 with Localhost with XAMPP Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12
2.Database client version: libmysql - mysqlnd 8.2.12 
3.
...

### Expected behavior

It should all clients but latest clients was not showing 

### Screenshots

![Screenshot 2024-09-10 222246](https://github.com/user-attachments/assets/1d7ab950-1196-49e5-96eb-af687b32e87b)
![Screenshot 2024-09-10 223210](https://github.com/user-attachments/assets/65e43d32-d94f-4f16-a585-dceb3bd8a868)
![Screenshot 2024-09-10 223228](https://github.com/user-attachments/assets/9e9f5fe9-db05-4de5-87e4-ada526980e58)

### Snipe-IT Version

Version v7.0.11 - build 14904 (master)

### Operating System

Windows 11

### Web Server

Apache

### PHP Version

8.2

### Operating System

Windows

### Browser

Chrome, Firefox

### Version

130

### Error messages

```shell
"[object] (InvalidArgumentException(code: 0): Database connection [] not configured. at C:\\xampp\\htdocs\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php:196)
Stack trace:
#0 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(159): Illuminate\Database\DatabaseManager->configuration('')
#1 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(101): Illuminate\Database\DatabaseManager->makeConnection('')
#2 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseServiceProvider.php(74): Illuminate\Database\DatabaseManager->connection()
#3 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(908): Illuminate\Database\DatabaseServiceProvider->Illuminate\Database\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(795): Illuminate\Container\Container->build(Object(Closure))
#5 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(961): Illuminate\Container\Container->resolve('db.schema', Array, true)
#6 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(731): Illuminate\Foundation\Application->resolve('db.schema', Array)
#7 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(946): Illuminate\Container\Container->make('db.schema', Array)
#8 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(1454): Illuminate\Foundation\Application->make('db.schema')
#9 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(240): Illuminate\Container\Container->offsetGet('db.schema')
#10 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Support\Facades\Facade::resolveFacadeInstance('db.schema')
#11 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(349): Illuminate\Support\Facades\Facade::getFacadeRoot()
#12 C:\xampp\htdocs\snipe-it\app\Providers\AppServiceProvider.php(68): Illuminate\Support\Facades\Facade::__callStatic('defaultStringLe...', Array)
#13 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Providers\AppServiceProvider->boot(Object(Illuminate\Routing\UrlGenerator))
#14 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#16 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#17 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#18 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1034): Illuminate\Container\Container->call(Array)
#19 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1015): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#20 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 35)
#21 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1014): array_walk(Array, Object(Closure))
#22 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#23 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(263): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#24 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith(Array)
#25 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#26 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\snipe-it\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#28 {main}
```

**Comment by snipe** [comment]
I'm not sure what you mean by "clients" here. I assume that's a custom field? What does Department have to do with this?

> "[object] (InvalidArgumentException(code: 0): Database connection [] not configured. at C:\\xampp\\htdocs\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php:196)
Stack trace:

**Comment by adityakiran55** [comment]
We are using Clients as Departments When ever i add department it is not showing Department While assign assets.
Please refer the screenshots are attached so that you can understand the Issue.
My problem is i have hosted in Local Machine i cant take help from Outside Team as it was blocked by Firewall.

![1](https://github.com/user-attachments/assets/abecf2d6-0cec-4d89-9cdd-8fafd664ce50)
![2](https://github.com/user-attachments/assets/3644526d-50bd-4138-ac16-3669dcaf76a6)

**Comment by adityakiran55** [comment]
> I'm not sure what you mean by "clients" here. I assume that's a custom field? What does Department have to do with this?
> 
> > "[object] (InvalidArgumentException(code: 0): Database connection [] not configured. at C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:196)
> > Stack trace:

The issue remained same
Please support
