### ISSUE TITLE
Server 500 Error when trying to view random users

### ISSUE THREAD

**Issue by portcityair** [grokability/snipe-it#15543]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Good afternoon,

We migrated to a new server and successfully moved over our existing snipe-it installation with a restored backup. Nearly everything is working as it should, except for a strange exception where a handful of users (selected from either checked-out assets or the People menu on the sidebar) will return a 500 Server Error after ~30 seconds of attempting to load. Some users will load right away without issue, while others will error. The affected users does not change, meaning it's always the same users that will throw the error. I've ensured that /storage and all subdirectories have been chown'd and chmod'd to the www-data user and 755. We also recently enabled use of SSL after upgrading the install to the latest version, which is working as it should. Other than that there have been no changes from the previous instance on the old host. 

We're running a local server running Ubuntu 24.04 LTS. We only use this server to host snipe-it.

### Reproduction steps

1. Click an assigned user via checked-out asset.
2. Click on a user via People sidebar menu item.
3. ~30 second load time will return a 500 | Server Error 

### Expected behavior

Load the user page of the selected user.

### Snipe-IT Version

v7.0.12 build 15249 (g713bb104e)

### Operating System

Ubuntu 24.04 LTS

### Web Server

Apache2

### PHP Version

8.3.6

### Operating System

Windows 11

### Browser

Chrome

### Version

128.0.6613.138

### Error messages

```shell
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

--------------------------------


Next Illuminate\View\ViewException: Call to undefined function App\Presenters\mb_strimwidth() (View: /var/www/tech.portcityair.com/snipe-it/resources/views/users/view.blade.php) in /var/www/tech.portcityair.com/snipe-it/app/Presenters/LicensePresenter.php:325
Stack trace:
#0 /var/www/tech.portcityair.com/snipe-it/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(58): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->handleViewException()
#2 /var/www/tech.portcityair.com/snipe-it/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\View\Engines\PhpEngine->evaluatePath()
#3 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->evaluatePath()
#4 /var/www/tech.portcityair.com/snipe-it/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\View\Engines\CompilerEngine->get()
#5 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(207): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->get()
#6 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#7 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#8 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()
#9 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()
#10 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(918): Illuminate\Http\Response->__construct()
#11 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\Routing\Router::toResponse()
#12 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Routing\Router->prepareResponse()
#13 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#14 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#16 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\AuthenticateSession->handle()
#18 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Auth\Middleware\Authenticate->handle()
#20 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/AssetCountForSidebar.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\AssetCountForSidebar->handle()
#22 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#24 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForTwoFactor->handle()
#26 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckUserIsActivated->handle()
#28 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckLocale->handle()
#30 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#32 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#34 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#36 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then()
#38 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#39 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#40 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#41 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#42 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#43 /var/www/tech.portcityair.com/snipe-it/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#45 /var/www/tech.portcityair.com/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#47 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle()
#49 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\PreventBackHistory->handle()
#51 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\SecurityHeaders->handle()
#53 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#55 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#56 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#58 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#59 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForDebug->handle()
#61 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\CheckForSetup->handle()
#63 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#65 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#67 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle()
#68 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#70 /var/www/tech.portcityair.com/snipe-it/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#71 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\NoSessionStore->handle()
#72 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#73 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#74 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#75 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#76 /var/www/tech.portcityair.com/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#77 /var/www/tech.portcityair.com/snipe-it/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#78 {main}  
[2024-09-23 13:54:08] production.ERROR: Symfony\Component\ErrorHandler\Error\FatalError: Maximum execution time of 30 seconds exceeded in /var/www/tech.portcityair.com/snipe-it/vendor/symfony/polyfill-mbstring/Mbstring.php:667
Stack trace:
#0 {main}  
[2024-09-23 13:54:08] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":261,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/tech.portcityair.com/snipe-it/vendor/symfony/polyfill-mbstring/Mbstring.php:667)
[stacktrace]
#0 {main}
"}
```

**Comment by portcityair** [comment]
I managed to get this resolved pretty easily, the answer was right in front of me in the logs. The new server did not have php-mbstring package installed. After installing it and restarting apache, all users are now loading normally!

**Comment by portcityair** [comment]
For future users encountering this issue on Ubuntu, this is the command to install this package:

`sudo apt install php-mbstring`

which will return the following:

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following additional packages will be installed:
>   php8.3-mbstring
> The following NEW packages will be installed:
>   php-mbstring php8.3-mbstring
> 0 upgraded, 2 newly installed, 0 to remove and 9 not upgraded.
> Need to get 513 kB of archives.
> After this operation, 1,250 kB of additional disk space will be used.
> Do you want to continue? [Y/n]
> Get:1 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64 php8.3-mbstring amd64 8.3.6-0ubuntu0.24.04.1 [512 kB]
> Get:2 http://us.archive.ubuntu.com/ubuntu noble/universe amd64 php-mbstring all 2:8.3+93ubuntu2 [1,848 B]
> Fetched 513 kB in 1s (875 kB/s)
> Selecting previously unselected package php8.3-mbstring.
> (Reading database ... 177203 files and directories currently installed.)
> Preparing to unpack .../php8.3-mbstring_8.3.6-0ubuntu0.24.04.1_amd64.deb ...
> Unpacking php8.3-mbstring (8.3.6-0ubuntu0.24.04.1) ...
> Selecting previously unselected package php-mbstring.
> Preparing to unpack .../php-mbstring_2%3a8.3+93ubuntu2_all.deb ...
> Unpacking php-mbstring (2:8.3+93ubuntu2) ...
> Setting up php8.3-mbstring (8.3.6-0ubuntu0.24.04.1) ...
> 
> Creating config file /etc/php/8.3/mods-available/mbstring.ini with new version
> Setting up php-mbstring (2:8.3+93ubuntu2) ...
> Processing triggers for php8.3-fpm (8.3.6-0ubuntu0.24.04.1) ...
> NOTICE: Not enabling PHP 8.3 FPM by default.
> NOTICE: To enable PHP 8.3 FPM in Apache2 do:
> NOTICE: a2enmod proxy_fcgi setenvif
> NOTICE: a2enconf php8.3-fpm
> NOTICE: You are seeing this message because you have apache2 package installed.
> Processing triggers for libapache2-mod-php8.3 (8.3.6-0ubuntu0.24.04.1) ...
> Processing triggers for php8.3-cli (8.3.6-0ubuntu0.24.04.1) ...
