### ISSUE TITLE
Check-in/Check-out email notification not working for CC account. 

### ISSUE THREAD

**Issue by deeepakkumarthakur16** [grokability/snipe-it#15776]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After Updating to recent version of snipe it my check-in/check-out email notification not working for CC (admin) account.

### Reproduction steps

1. Enable Alert under notification settings
2. add cc email address and save the settings
3. Check-in/check-out assets to user
4. Email notification to user is working fine but didn't working for cc account
5. Checked SMTP logs in SMTP SMTP Server didn't receive any email to CC account

### Expected behavior

When any assets check-in/check-out to user email should trigger to user and copy of that email notification should trigger to admin (CC) account as well.  

### Screenshots

<img width="577" alt="image" src="https://github.com/user-attachments/assets/38d43678-670a-469b-81fe-f659eeef255c">

### Snipe-IT Version

Version v7.0.13 

### Operating System

Centos 9

### Web Server

Nginx

### PHP Version

v8.1.27

### Error messages

```shell
[2024-10-18 19:16:23] production.ERROR: syntax error, unexpected token "{", expecting "function" or "const" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected token \"{\", expecting \"function\" or \"const\" at /var/www/html/snipe/app/Models/License.php:662)
Stack trace:
#0 /var/www/html/snipe/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#1 /var/www/html/snipe/app/Providers/AppServiceProvider.php(74): Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\AppServiceProvider->boot()
#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#6 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#7 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1034): Illuminate\Container\Container->call()
#8 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1015): Illuminate\Foundation\Application->bootProvider()
#9 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#10 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1016): array_walk()
#11 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#12 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#13 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#14 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#15 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#16 /var/www/html/snipe/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#17 {main}  

errorlaravel.log
[2024-10-18 19:16:23] production.ERROR: ParseError: syntax error, unexpected token "{", expecting "function" or "const" in /var/www/html/snipe/app/Models/License.php:662
[stacktrace]
#0 /var/www/html/snipe/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#1 /var/www/html/snipe/app/Providers/AppServiceProvider.php(74): Composer\\Autoload\\ClassLoader->loadClass()
#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\AppServiceProvider->boot()
#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1034): Illuminate\\Container\\Container->call()
#8 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1015): Illuminate\\Foundation\\Application->bootProvider()
#9 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#10 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1016): array_walk()
#11 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#12 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#13 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#14 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#15 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#16 /var/www/html/snipe/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#17 {main}
"} 

errorlaravel.log
[2024-10-18 19:15:47] production.ERROR: syntax error, unexpected token "{", expecting "function" or "const" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected token \"{\", expecting \"function\" or \"const\" at /var/www/html/snipe/app/Models/License.php:662)
Stack trace:
#0 /var/www/html/snipe/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#1 /var/www/html/snipe/app/Providers/AppServiceProvider.php(74): Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\AppServiceProvider->boot()
#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#6 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#7 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1034): Illuminate\Container\Container->call()
#8 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1015): Illuminate\Foundation\Application->bootProvider()
#9 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#10 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1016): array_walk()
#11 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#12 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#13 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#14 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#15 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#16 /var/www/html/snipe/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#17 {main}  

errorlaravel.log
[2024-10-18 19:15:47] production.ERROR: ParseError: syntax error, unexpected token "{", expecting "function" or "const" in /var/www/html/snipe/app/Models/License.php:662
[stacktrace]
#0 /var/www/html/snipe/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#1 /var/www/html/snipe/app/Providers/AppServiceProvider.php(74): Composer\\Autoload\\ClassLoader->loadClass()
#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\AppServiceProvider->boot()
#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1034): Illuminate\\Container\\Container->call()
#8 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1015): Illuminate\\Foundation\\Application->bootProvider()
#9 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#10 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1016): array_walk()
#11 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#12 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#13 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#14 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#15 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#16 /var/www/html/snipe/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#17 {main}
"} 

errorlaravel.log
[2024-10-18 19:15:26] production.ERROR: syntax error, unexpected token "else", expecting "function" or "const" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected token \"else\", expecting \"function\" or \"const\" at /var/www/html/snipe/app/Models/License.php:662)
Stack trace:
#0 /var/www/html/snipe/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#1 /var/www/html/snipe/app/Providers/AppServiceProvider.php(74): Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\AppServiceProvider->boot()
#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#6 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#7 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1034): Illuminate\Container\Container->call()
#8 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1015): Illuminate\Foundation\Application->bootProvider()
#9 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#10 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1016): array_walk()
#11 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#12 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#13 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#14 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#15 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#16 /var/www/html/snipe/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#17 {main}  

errorlaravel.log
[2024-10-18 19:15:26] production.ERROR: ParseError: syntax error, unexpected token "else", expecting "function" or "const" in /var/www/html/snipe/app/Models/License.php:662"}
```

**Comment by deeepakkumarthakur16** [comment]
Issues fixed in latest build Snipe-IT v7.0.13 - build 15666
