### ISSUE TITLE
500 Error after update to 7.1.14

### ISSUE THREAD

**Issue by jbairenky** [grokability/snipe-it#15849]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have tried to manually upgrade to Snipe IT version 7.1.14, but once the process completed, all I get now is HTTP 500 Internal Server Error. Below is the exception details that appears in debug mode:

The stream or file "C:\inetpub\wwwroot\snipeit\storage\logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Exception: The C:\inetpub\wwwroot\snipeit\bootstrap\cache directory must be present and writable. in C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php:178
Stack trace:
#0 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(131): Illuminate\Foundation\PackageManifest->write()
#1 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(107): Illuminate\Foundation\PackageManifest->build()
#2 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(90): Illuminate\Foundation\PackageManifest->getManifest()
#3 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(79): Illuminate\Foundation\PackageManifest->config()
#4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#5 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(263): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#6 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#7 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#8 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#9 C:\inetpub\wwwroot\snipeit\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#10 {main}

### Reproduction steps

1. Upgrade to Snipe IT version 7.1.14 manually
2. Restart site
3. Load url, see 500 Error

### Expected behavior

App loads with no exceptions, upgraded to new release

### Screenshots

![image](https://github.com/user-attachments/assets/4da3e0c0-ae6a-4d96-ab14-b036f2099a5e)

### Snipe-IT Version

7.1.14

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.2.25

### Operating System

Windown

### Browser

Google Chrome

### Error messages

```shell
The stream or file "C:\inetpub\wwwroot\snipeit\storage\logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Exception: The C:\inetpub\wwwroot\snipeit\bootstrap\cache directory must be present and writable. in C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php:178
Stack trace:
#0 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(131): Illuminate\Foundation\PackageManifest->write()
#1 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(107): Illuminate\Foundation\PackageManifest->build()
#2 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(90): Illuminate\Foundation\PackageManifest->getManifest()
#3 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php(79): Illuminate\Foundation\PackageManifest->config()
#4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#5 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(263): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#6 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#7 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#8 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#9 C:\inetpub\wwwroot\snipeit\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#10 {main}
```

### Additional context

Upgrade on Windows Server IIS
Manual installation
Full installation, had to update PHP and Composer.
Installation gave these warnings:

Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.

Warning: Ambiguous class resolution, "League\Flysystem\AwsS3V3\AwsS3V3Adapter" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-aws-s3-v3\AwsS3V3Adapter.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\AwsS3V3\AwsS3V3Adapter.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\AwsS3V3\AwsS3V3AdapterTest" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-aws-s3-v3\AwsS3V3AdapterTest.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\AwsS3V3\AwsS3V3AdapterTest.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\AwsS3V3\PortableVisibilityConverter" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-aws-s3-v3\PortableVisibilityConverter.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\AwsS3V3\PortableVisibilityConverter.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\AwsS3V3\S3ClientStub" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-aws-s3-v3\S3ClientStub.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\AwsS3V3\S3ClientStub.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\AwsS3V3\VisibilityConverter" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-aws-s3-v3\VisibilityConverter.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\AwsS3V3\VisibilityConverter.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\Local\FallbackMimeTypeDetector" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-local\FallbackMimeTypeDetector.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\Local\FallbackMimeTypeDetector.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\Local\LocalFilesystemAdapter" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-local\LocalFilesystemAdapter.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\Local\LocalFilesystemAdapter.php", the first will be used.
Warning: Ambiguous class resolution, "League\Flysystem\Local\LocalFilesystemAdapterTest" was found in both "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem-local\LocalFilesystemAdapterTest.php" and "C:/inetpub/wwwroot/snipeit/vendor/league/flysystem/src\Local\LocalFilesystemAdapterTest.php", the first will be used.
Class ParsedownTest located in C:/inetpub/wwwroot/snipeit/vendor/erusev/parsedown\test\ParsedownTest.php does not comply with psr-0 autoloading standard. Skipping.

**Comment by jbairenky** [comment]
I tried viewing it again after assigning some additional permissions, but now I get the following:

Error:
Class "ZipArchive" not found

  at C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\config\backup.php:133
  at require()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:138)
  at Illuminate\Support\ServiceProvider->mergeConfigFrom()
     (C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-package-tools\src\PackageServiceProvider.php:33)
  at Spatie\LaravelPackageTools\PackageServiceProvider->register()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:794)
  at Illuminate\Foundation\Application->register()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:75)
  at Illuminate\Foundation\ProviderRepository->load()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:771)
  at Illuminate\Foundation\Application->registerConfiguredProviders()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php:17)
  at Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:263)
  at Illuminate\Foundation\Application->bootstrapWith()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:186)
  at Illuminate\Foundation\Http\Kernel->bootstrap()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:170)
  at Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
     (C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:144)
  at Illuminate\Foundation\Http\Kernel->handle()
     (C:\inetpub\wwwroot\snipeit\public\index.php:51)
