### ISSUE TITLE
Error when trying to create a Snipe-IT backup for migration

### ISSUE THREAD

**Issue by AwkwardFabian** [grokability/snipe-it#15873]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When the "Generate Backup" button is pressed, it gives me a "general error" error message and does not make a backup.

### Reproduction steps

1. Click admin panel and go in "Backups"
2. Click "Generate backup" button
3. Returns error message and no backup is made
...

### Expected behavior

A backup to be created for migration. 

### Screenshots

![erreur snipe IT](https://github.com/user-attachments/assets/0eb4a136-19af-4397-8963-5593d971f281)

 

### Snipe-IT Version

v7.0.13

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.3.10

### Error messages

```shell
Browser console
Error with Feature-Policy header: Unrecognized feature: 'document-domain'.Understand this warningAI
backups:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">

Error: Backup failed because: The dump process failed with a none successful exitcode. Exitcode ======== 1: General error Output ====== <no output> Error Output ============ <no output>. #0 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\DbDumper.php(194): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\inetpub\wwwroot\snipeit\vendor\spatie\db-dumper\src\Databases\MySql.php(161): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(284): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(600): array_map() #5 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(778): Illuminate\Support\Arr::map() #6 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(249): Illuminate\Support\Collection->map() #7 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(189): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #8 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(163): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #9 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(65): Spatie\Backup\Tasks\Backup\BackupJob->run() #10 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #11 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #12 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #13 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod() #14 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call() #15 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(211): Illuminate\Container\Container->call() #16 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Command\Command.php(326): Illuminate\Console\Command->execute() #17 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(180): Symfony\Component\Console\Command\Command->run() #18 C:\inetpub\wwwroot\snipeit\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(28): Illuminate\Console\Command->run() #19 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Concerns\CallsCommands.php(67): Spatie\Backup\Commands\BaseCommand->run() #20 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Concerns\CallsCommands.php(28): Illuminate\Console\Command->runCommand() #21 C:\inetpub\wwwroot\snipeit\app\Console\Commands\SystemBackup.php(48): Illuminate\Console\Command->call() #22 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SystemBackup->handle() #23 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #24 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #25 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod() #26 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call() #27 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(211): Illuminate\Container\Container->call() #28 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Command\Command.php(326): Illuminate\Console\Command->execute() #29 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(180): Symfony\Component\Console\Command\Command->run() #30 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(1096): Illuminate\Console\Command->run() #31 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(324): Symfony\Component\Console\Application->doRunCommand() #32 C:\inetpub\wwwroot\snipeit\vendor\symfony\console\Application.php(175): Symfony\Component\Console\Application->doRun() #33 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(162): Symfony\Component\Console\Application->run() #34 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(400): Illuminate\Console\Application->call() #35 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(355): Illuminate\Foundation\Console\Kernel->call() #36 C:\inetpub\wwwroot\snipeit\app\Http\Controllers\SettingsController.php(1084): Illuminate\Support\Facades\Facade::__callStatic() #37 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #38 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction() #39 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch() #40 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController() #41 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(806): Illuminate\Routing\Route->run() #42 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #43 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckPermissions.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #44 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\CheckPermissions->handle() #45 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #46 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle() #47 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #48 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Session\Middleware\AuthenticateSession->handle() #49 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #50 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Auth\Middleware\Authenticate->handle() #51 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\AssetCountForSidebar.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #52 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\AssetCountForSidebar->handle() #53 C:\inetpub\wwwroot\snipeit\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #54 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #55 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #56 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\CheckForTwoFactor->handle() #57 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\CheckUserIsActivated->handle() #59 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckLocale.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\CheckLocale->handle() #61 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #63 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #65 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle() #67 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(805): Illuminate\Pipeline\Pipeline->then() #69 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(784): Illuminate\Routing\Router->runRouteWithinStack() #70 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(748): Illuminate\Routing\Router->runRoute() #71 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(737): Illuminate\Routing\Router->dispatchToRoute() #72 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(200): Illuminate\Routing\Router->dispatch() #73 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #74 C:\inetpub\wwwroot\snipeit\vendor\livewire\livewire\src\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #75 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle() #76 C:\inetpub\wwwroot\snipeit\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #77 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #78 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #79 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle() #80 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #81 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\PreventBackHistory->handle() #82 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #83 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\SecurityHeaders->handle() #84 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #85 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #86 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() #87 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #88 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\CheckForDebug->handle() #89 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #90 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\CheckForSetup->handle() #91 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #92 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #93 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #94 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest() #95 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle() #96 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #97 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle() #98 C:\inetpub\wwwroot\snipeit\app\Http\Middleware\NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #99 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): App\Http\Middleware\NoSessionStore->handle() #100 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #101 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(175): Illuminate\Pipeline\Pipeline->then() #102 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #103 C:\inetpub\wwwroot\snipeit\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle() #104 {main} Backup failed because: The dump process failed with a none successful exitcode. Exitcode ======== 1: General error Output ====== <no output> Error Output ============ <no output>.

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
random
readline
Reflection
session
SimpleXML
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
```

### Additional context

fresh install, windows 11 on IIS, manual install

**Comment by Kanishka-Deshan** [comment]
Follow these steps:

**Grant IIS_IUSR Modify Access:**

- Navigate to the C:\Windows\Temp folder.
- Right-click on the folder, select Properties, go to the Security tab, and click Edit.
- Add the IIS_IUSR user and ensure it has **Modify** permissions.

**Set the Correct DB Dump Path:**

- Confirm the database dump path is correctly set. You can retrieve the short path of the MariaDB binary folder using the following command in Command Prompt:
```shell
cmd /c for %A in ("C:\Program Files\MariaDB 11.4\bin") do @echo %~sA
``` 
- Use the output as the database dump path in your Snipe-IT configuration.


**Grant IIS_IUSR Modify Access to the Storage Folder:**

- Navigate to the storage folder in your Snipe-IT project directory.
- Right-click on the folder, select Properties, go to the Security tab, and click Edit.
- Add the IIS_IUSR user and grant it Modify permissions.

Refer windows configurations in snipe-it documentation for more.
[https://snipe-it.readme.io/docs/windowsiis](url)

**Comment by snipe** [comment]
@AwkwardFabian any luck?

**Comment by Rajat-Imme** [comment]
I have hosted snipe it on Linux AWS ec2 instance using docker. Same issue!!

**Comment by snipe** [comment]
@Rajat-Imme Make sure the path to mysqldump is correct in your env file.

**Comment by Rajat-Imme** [comment]
Yes I have resolved the issue

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
