### ISSUE TITLE
Database is created but still it shows "Unknown Database"

### ISSUE THREAD

**Issue by abhijitrajkhowa27** [grokability/snipe-it#7691]
#### Expected Behavior (or desired behavior if a feature request)
(what you expect to happen goes here)

The snipe-it Pre-Flight set-up page should appear.
-----

#### Actual Behavior

(what actually happens goes here)
Whoops, looks like something went wrong. Unknown database 'assetmanagement' (SQL: select * from information_schema.tables where table_schema = assetmanagement and table_name = users).

The database is created and I have cross-verified the credentials in .env file. I have checked the privilages for the user and it has all privilages.

![image](https://user-images.githubusercontent.com/8834876/71614814-f2cf7f00-2bd3-11ea-841c-ebf0a808ae19.png)

![image](https://user-images.githubusercontent.com/8834876/71614870-34602a00-2bd4-11ea-9a62-793eee89216d.png)

![image](https://user-images.githubusercontent.com/8834876/71614930-77ba9880-2bd4-11ea-8b48-a114e95721c6.png)

However, the issue disappears if I replace the db name to an already pre-configured db and replace the username to root. With this setup I am able to see the Pre-flight screen, but not confident as I require a different db for my org.

![image](https://user-images.githubusercontent.com/8834876/71615001-db44c600-2bd4-11ea-9747-d66b964ac6a0.png)

![image](https://user-images.githubusercontent.com/8834876/71615009-ea2b7880-2bd4-11ea-9eac-c9419c9af79e.png)

Kindly help! I have tried all the troubleshooting that is possible. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - **Yes**
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - **Yes**

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - **Fresh installation** 
- Version of Snipe-IT you're running - **Latest pull from Github**
- Version of PHP you're running - **7.3.12**
- Version of MySQL/MariaDB you're running - **Mysql 5.7.28**
- What OS and web server you're running Snipe-IT on - **Wampserver 3.2.0 (Base OS Windows 10 64 bit)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Manual from GitHub**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error- 

(3/3) QueryExceptionSQLSTATE[HY000] [1049] Unknown database 'assetmanagement' (SQL: select * from information_schema.tables where table_schema = assetmanagement and table_name = users)
--
in Connection.php line 664
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'), object(Closure))in Connection.php line 624
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'), object(Closure))in Connection.php line 333
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

(2/3) PDOExceptionSQLSTATE[HY000] [1049] Unknown database 'assetmanagement'
--
in PDOConnection.php line 31
at PDOConnection->__construct('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', 'root', '', array(0, 2, 0, false, false))in Connector.php line 64
at Connector->createPdoConnection('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', 'root', '', array(0, 2, 0, false, false))in Connector.php line 43
at Connector->createConnection('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'assetmanagement', 'username' => 'root', 'password' => '', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump' => array('dump_binary_path' => 'C:\\wamp64\\bin\\mysql\\mysql8.0.18\\bin', 'use_single_transaction', 'timeout' => 300), 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'assetmanagement', 'username' => 'root', 'password' => '', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump' => array('dump_binary_path' => 'C:\\wamp64\\bin\\mysql\\mysql8.0.18\\bin', 'use_single_transaction', 'timeout' => 300), 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 915
at Connection->getPdo()in Connection.php line 940
at Connection->getReadPdo()in Connection.php line 399
at Connection->getPdoForSelect(true)in Connection.php line 325
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'))in Connection.php line 657
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'), object(Closure))in Connection.php line 624
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'), object(Closure))in Connection.php line 333
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

(1/3) PDOExceptionSQLSTATE[HY000] [1049] Unknown database 'assetmanagement'
--
in PDOConnection.php line 27
at PDO->__construct('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', 'root', '', array(0, 2, 0, false, false))in PDOConnection.php line 27
at PDOConnection->__construct('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', 'root', '', array(0, 2, 0, false, false))in Connector.php line 64
at Connector->createPdoConnection('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', 'root', '', array(0, 2, 0, false, false))in Connector.php line 43
at Connector->createConnection('mysql:host=127.0.0.1;port=3306;dbname=assetmanagement', array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'assetmanagement', 'username' => 'root', 'password' => '', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump' => array('dump_binary_path' => 'C:\\wamp64\\bin\\mysql\\mysql8.0.18\\bin', 'use_single_transaction', 'timeout' => 300), 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'assetmanagement', 'username' => 'root', 'password' => '', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump' => array('dump_binary_path' => 'C:\\wamp64\\bin\\mysql\\mysql8.0.18\\bin', 'use_single_transaction', 'timeout' => 300), 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 915
at Connection->getPdo()in Connection.php line 940
at Connection->getReadPdo()in Connection.php line 399
at Connection->getPdoForSelect(true)in Connection.php line 325
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'))in Connection.php line 657
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'), object(Closure))in Connection.php line 624
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'), object(Closure))in Connection.php line 333
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('assetmanagement', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **Snipe IT Pre-Flight page**
- If a stacktrace is provided in the error, include that too. - **Pasted error above.**
- Any errors that appear in your browser's error console. - **Not Available**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **Not Sure**
- Include any additional information you can find in `storage/logs` and your webserver's logs. -

- **Wampserver trace report** -
File created by Wampserver install
[31-Dec-2019 10:46:26 Asia/Calcutta] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'itadmin'@'localhost' (using password: YES) in C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#1 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#2 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'itadmin', 'Support4', Array)
#3 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->creat in C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664
[31-Dec-2019 10:46:27 Asia/Calcutta] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'itadmin'@'localhost' (using password: YES) in C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#1 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#2 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'itadmin', 'Support4', Array)
#3 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->creat in C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664
[31-Dec-2019 10:48:53 Asia/Calcutta] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'itadmin'@'localhost' (using password: YES) in C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#1 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#2 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'itadmin', 'Support4', Array)
#3 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->creat in C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664
[31-Dec-2019 10:48:53 Asia/Calcutta] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'itadmin'@'localhost' (using password: YES) in C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#1 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#2 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'itadmin', 'Support4', Array)
#3 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->creat in C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664
[31-Dec-2019 10:51:09 Asia/Calcutta] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'itadmin'@'localhost' (using password: YES) in C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#1 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#2 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'itadmin', 'Support4', Array)
#3 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->creat in C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664
[31-Dec-2019 10:51:09 Asia/Calcutta] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'itadmin'@'localhost' (using password: YES) in C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 C:\wamp64\www\GAIITAssetManagement\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#1 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'itadmin', 'Support4', Array)
#2 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'itadmin', 'Support4', Array)
#3 C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->creat in C:\wamp64\www\GAIITAssetManagement\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664

- Include what you've done so far in the installation, and if you got any error messages along the way. 
**1. Installed WampServer**
**2. Installed Composer**
**3. Created Db, edited the .env files.**
**4. Edited the httpd-vhots conf files.**
**5. Installed the dependencies using composer.**
**6. Generated the application key.**
**7. Restarted WAMP server.**

- Indicate whether or not you've manually edited any data directly in the database - **Initailly didn't edit later on tried users table under the db as the error points to users table.**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by abhijitrajkhowa27** [comment]
This is still relevant. Any input on this will be highly appreciated. @snipe

**Comment by GzaGator** [comment]
I am having the same issue. Snipe-IT will not see my created users or my created databases, but if I put in root and a preconfigured db it will go to the preflight page. Otherwise I get the unknown database error.

**Comment by abhijitrajkhowa27** [comment]
This is still relevant

**Comment by abhishekshingadiya** [comment]
I get this issue too
I created DB but not working with 
```
try
{
	
	$dbh = new PDO("mysql:host=".DB_HOST.";dbname=".DB_NAME,DB_USER, DB_PASS,array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8'"));
}
catch (PDOException $e)
{
	exit("Error: " . $e->getMessage());
}
```

**Comment by abhijitrajkhowa27** [comment]
yes

**Comment by horlakay** [comment]
pymysql would not see my database in wamp

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
