### ISSUE TITLE
Error on running an asset import through the command line

### ISSUE THREAD

**Issue by peter-russell** [grokability/snipe-it#7783]
#### Expected Behavior (or desired behavior if a feature request)

After running an asset import through the command line, the assets should be imported into Snipe IT.

-----

#### Actual Behavior

After running the command `php artisan snipeit:import pathtoassets.csv`, the following error appears:

![image](https://user-images.githubusercontent.com/6551599/73618017-79b2c400-4678-11ea-9d44-96cb12d93efb.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

**- Is this a fresh install or an upgrade?** 
Fresh.
**- Version of Snipe-IT you're running**
4.8.0
**- Version of PHP you're running**
7.4.1
**- Version of MySQL/MariaDB you're running**
MariaDB 10.0.36
**- What OS and web server you're running Snipe-IT on**
Windows Server 2016, IIS
**- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)**
Manual installation
**- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error**
N/A
**- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error**
Not on a specific Snipe IT page, although I am on the command line in the Snipe IT root directory.
**- If a stacktrace is provided in the error, include that too.**
```
Exception trace:
  at C:\inetpub\wwwroot\snipe-it\vendor\neitanod\forceutf8\src\ForceUTF8\Encoding.php:196
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at C:\inetpub\wwwroot\snipe-it\vendor\composer\ClassLoader.php:444
 include() at C:\inetpub\wwwroot\snipe-it\vendor\composer\ClassLoader.php:444
 Composer\Autoload\includeFile() at C:\inetpub\wwwroot\snipe-it\vendor\composer\ClassLoader.php:322
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at C:\inetpub\wwwroot\snipe-it\app\Importer\Importer.php:189
 App\Importer\Importer->findCsvMatch() at C:\inetpub\wwwroot\snipe-it\app\Importer\ItemImporter.php:29
 App\Importer\ItemImporter->handle() at C:\inetpub\wwwroot\snipe-it\app\Importer\AssetImporter.php:24
 App\Importer\AssetImporter->handle() at C:\inetpub\wwwroot\snipe-it\app\Importer\Importer.php:132
 App\Importer\Importer->App\Importer\{closure}() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:327
 Illuminate\Database\DatabaseManager->__call() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at C:\inetpub\wwwroot\snipe-it\app\Importer\Importer.php:139
 App\Importer\Importer->import() at C:\inetpub\wwwroot\snipe-it\app\Console\Commands\ObjectImportCommand.php:83
 App\Console\Commands\ObjectImportCommand->handle() at n/a:n/a
 call_user_func_array() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:549
 Illuminate\Container\Container->call() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:183
 Illuminate\Console\Command->execute() at C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php:255
 Symfony\Component\Console\Command\Command->run() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:170
 Illuminate\Console\Command->run() at C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:982
 Symfony\Component\Console\Application->doRunCommand() at C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:255
 Symfony\Component\Console\Application->doRun() at C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:148
 Symfony\Component\Console\Application->run() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php:88
 Illuminate\Console\Application->run() at C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at C:\inetpub\wwwroot\snipe-it\artisan:35
```
**- Any errors that appear in your browser's error console.**
Not from the browser, but the command line:
![image](https://user-images.githubusercontent.com/6551599/73618017-79b2c400-4678-11ea-9d44-96cb12d93efb.png)
**- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.**
N/A
**- Include any additional information you can find in `storage/logs` and your webserver's logs.**
This was in importer.log:
```
[2020-02-03 11:22:02] production.ERROR: ErrorException: Array and string offset access syntax with curly braces is deprecated in C:\inetpub\wwwroot\snipe-it\vendor\neitanod\forceutf8\src\ForceUTF8\Encoding.php:196
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\composer\ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\inetpub\wwwroot\snipe-it\vendor\composer\ClassLoader.php(444): include()
#2 C:\inetpub\wwwroot\snipe-it\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 C:\inetpub\wwwroot\snipe-it\app\Importer\Importer.php(189): spl_autoload_call()
#5 C:\inetpub\wwwroot\snipe-it\app\Importer\ItemImporter.php(29): App\Importer\Importer->findCsvMatch()
#6 C:\inetpub\wwwroot\snipe-it\app\Importer\AssetImporter.php(24): App\Importer\ItemImporter->handle()
#7 C:\inetpub\wwwroot\snipe-it\app\Importer\Importer.php(132): App\Importer\AssetImporter->handle()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(29): App\Importer\Importer->App\Importer\{closure}()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(327): Illuminate\Database\Connection->transaction()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): Illuminate\Database\DatabaseManager->__call()
#11 C:\inetpub\wwwroot\snipe-it\app\Importer\Importer.php(139): Illuminate\Support\Facades\Facade::__callStatic()
#12 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\ObjectImportCommand.php(83): App\Importer\Importer->import()
#13 [internal function]: App\Console\Commands\ObjectImportCommand->handle()
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array()
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call()
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call()
#19 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(170): Symfony\Component\Console\Command\Command->run()
#21 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(982): Illuminate\Console\Command->run()
#22 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(255): Symfony\Component\Console\Application->doRunCommand()
#23 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun()
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(88): Symfony\Component\Console\Application->run()
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(121): Illuminate\Console\Application->run()
#26 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#27 {main}  
[2020-02-03 11:22:02] production.ERROR: Array and string offset access syntax with curly braces is deprecated {"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at C:\\inetpub\\wwwroot\\snipe-it\\vendor\
eitanod\\forceutf8\\src\\ForceUTF8\\Encoding.php:196)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\composer\\ClassLoader.php(444): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\composer\\ClassLoader.php(444): include()
#2 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 C:\\inetpub\\wwwroot\\snipe-it\\app\\Importer\\Importer.php(189): spl_autoload_call()
#5 C:\\inetpub\\wwwroot\\snipe-it\\app\\Importer\\ItemImporter.php(29): App\\Importer\\Importer->findCsvMatch()
#6 C:\\inetpub\\wwwroot\\snipe-it\\app\\Importer\\AssetImporter.php(24): App\\Importer\\ItemImporter->handle()
#7 C:\\inetpub\\wwwroot\\snipe-it\\app\\Importer\\Importer.php(132): App\\Importer\\AssetImporter->handle()
#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(29): App\\Importer\\Importer->App\\Importer\\{closure}()
#9 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(327): Illuminate\\Database\\Connection->transaction()
#10 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Database\\DatabaseManager->__call()
#11 C:\\inetpub\\wwwroot\\snipe-it\\app\\Importer\\Importer.php(139): Illuminate\\Support\\Facades\\Facade::__callStatic()
#12 C:\\inetpub\\wwwroot\\snipe-it\\app\\Console\\Commands\\ObjectImportCommand.php(83): App\\Importer\\Importer->import()
#13 [internal function]: App\\Console\\Commands\\ObjectImportCommand->handle()
#14 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array()
#15 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call()
#18 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call()
#19 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute()
#20 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#21 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\symfony\\console\\Application.php(982): Illuminate\\Console\\Command->run()
#22 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\symfony\\console\\Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#23 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\symfony\\console\\Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#24 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(88): Symfony\\Component\\Console\\Application->run()
#25 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(121): Illuminate\\Console\\Application->run()
#26 C:\\inetpub\\wwwroot\\snipe-it\\artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
"}
```
**- Include what you've done so far in the installation, and if you got any error messages along the way.**
Snipe IT is fully installed.
**- Indicate whether or not you've manually edited any data directly in the database**
No data has been manually edited in the database.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by aheady1234** [comment]
I was able to fix my issue. by replacing the {} with [] at line 196 thru 200 in the encoding file found here.
C:\inetpub\wwwroot\snipe-it\vendor\neitanod\forceutf8\src\ForceUTF8\Encoding.php. below is what my file looks like now.

$c1 = $text[$i];
        if($c1>="\xc0"){ //Should be converted to UTF8, if it's not UTF8 already
          $c2 = $i+1 >= $max? "\x00" : $text[$i+1];
          $c3 = $i+2 >= $max? "\x00" : $text[$i+2];
          $c4 = $i+3 >= $max? "\x00" : $text[$i+3];



This is what it was:
$c1 = $text{$i};
        if($c1>="\xc0"){ //Should be converted to UTF8, if it's not UTF8 already
          $c2 = $i+1 >= $max? "\x00" : $text{$i+1};
          $c3 = $i+2 >= $max? "\x00" : $text{$i+2};
          $c4 = $i+3 >= $max? "\x00" : $text{$i+3};

After I made the changes it now imports in without issue, both from command line and from the GUI

**Comment by peter-russell** [comment]
This worked! Thanks so much.
