### ISSUE TITLE
How to create multiple instances of Snipe-IT on one Windows Server host.

### ISSUE THREAD

**Issue by SirajQu** [grokability/snipe-it#7873]
**Server (please complete the following information):**
- Snipe-IT Version v4.6.18
- OS: Windows Server 2012
- Web Server: [IIS]
- PHP Version 7.0.33

**Is your feature request related to a problem? Please describe.**
Hi,
I want to install multiple instance of Snipe-IT on the Windows server that I'm using now and I have on it one Snipe-IT and I would like to install the second one which I tried to do the following but it didn't work with me:

- Created another MariaDB data base and user.
- Copied the the content of Snipe-IT folder into another folder named(Snipe-IT-2) inside the path C:\inetpub\wwwroot
- .env file has been edited with the new database and user, app key has been regenerated inside the path of the new folder (Snipe-IT-2), APP_URL is the same IP of the Windows server, COOKIE_NAME has been changed to another name as I have read article the snipe it site that should be given unique name in case of running multiple instances.
- In the IIS Manager I have created another website and selected the path of the second Snipe-IT instance (Snipe-IT-2).
- The Binding of the second instance has been entered the same (port 80)
the only different is specifying the host name: the first one is set as "asset.websitename.com"
and on the second one I put"bsasset.websitename.com"
- I have added the second hostname on our DNS server and linked with IP of the server.

But after doing all of the above still when I open the hostname basset.websitename.com it redirect me to the first Snipe-IT instance.
please tell me if there something I'm missing or I should do something on the URL Rewite.

**Comment by SirajQu** [comment]
Now it worked after I run php artisan config:clear ; php artisan config:cache
but now it give me this error Whoops, looks like something went wrong.

And this is the debug:
`

(1/1) UnexpectedValueExceptionThe stream or file "C:\inetpub\wwwroot\bsasset\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
--
in StreamHandler.php line 107
at StreamHandler->write(array('message' => 'UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\bsasset\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(707): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\bsasset\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\bsasset\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2020-03-04 19:44:38] production.ERROR: UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\bsasset\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(707): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\bsasset\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\bsasset\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in AbstractProcessingHandler.php line 39
at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\bsasset\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(707): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\bsasset\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\bsasset\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2020-03-04 19:44:38] production.ERROR: UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\bsasset\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\bsasset\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(707): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\bsasset\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\bsasset\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\bsasset\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in Logger.php line 344
at Logger->addRecord(400, object(UnexpectedValueException), array())in Logger.php line 707
at Logger->error(object(UnexpectedValueException), array())in Writer.php line 203
at Writer->writeLog('error', object(UnexpectedValueException), array())in Writer.php line 114
at Writer->error(object(UnexpectedValueException))in Facade.php line 221
at Facade::__callStatic('error', array(object(UnexpectedValueException)))in Handler.php line 39
at Handler->report(object(UnexpectedValueException))in HandleExceptions.php line 81
at HandleExceptions->handleException(object(UnexpectedValueException))

`

Although I have granted permission to IIS on the folder of Storage and WWW

**Comment by SirajQu** [comment]
Resolved after clearing the CACHE and Confing also there was problem in permission of IUSR in the folder: Storage, CACHE
