### ISSUE TITLE
Backup Issue IIS/Windows

### ISSUE THREAD

**Issue by namarie23** [grokability/snipe-it#7946]
#### Expected Behavior (or desired behavior if a feature request)

Back up Snipe IT using web GUI

-----

#### Actual Behavior
The DB_Dump_Path appears to be correct but have tried it a couple ways, using:
cmd /c for %A in ("C:\Program Files\MariaDB 10.5\bin") do @echo % ~ sA

**getting** C:\PROGRA ~  1\MARIAD ~ 1.5\bin and c**hanging it to** C:\\PROGRA ~ 1\\MARIAD ~ 1.5\\bin
**and using** 
D:\Program Files\MariaDB 10.5\bin (Maria DB was originally installed on the D drive, copied it to the C drive)
**C and D Temp folders have IIS_IUSRS and IUSR modify permissions, cleared artisan cache, restarted server, and its not fixing the error (full error attached)**
[error.txt](https://github.com/snipe/snipe-it/files/4446651/error.txt)
 **Screen cap below (successful install is from running php artisan backup:run in CMD)**
![image](https://user-images.githubusercontent.com/63315323/78710846-e3df2380-78ca-11ea-903b-3e08ace383f7.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **fresh**
- Version of Snipe-IT you're running: v4.7.8 build 4170 (g4fe689dc5)
- Version of PHP you're running 7.3.12
- Version of MySQL/MariaDB you're running MariaDB 10.5
- What OS and web server you're running Snipe-IT on: Windows 10 Server 2016, IIS 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:  Error: Backup failed because The dump process failed with exitcode 1 : General error : . #0 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(148): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\wwwr
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /admin/backups clicking "generate backup button"
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. : No, disabled
- Include any additional information you can find in `storage/logs` and your webserver's logs. Storage log attached. 
[laravel.storagelog.txt](https://github.com/snipe/snipe-it/files/4446661/laravel.storagelog.txt)

- Include what you've done so far in the installation, and if you got any error messages along the way. Followed the guide, no errors before this.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by namarie23** [comment]
Any update on this?

**Comment by namarie23** [comment]
Any feedback is appreciated @snipe

**Comment by namarie23** [comment]
I gave up on this.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
