### ISSUE TITLE
Install.sh installation on Ubuntu 18.04 - blank web page

### ISSUE THREAD

**Issue by iqrait** [grokability/snipe-it#8022]
#### Expected Behavior (or desired behavior if a feature request)

Installed via installer script on a fresh Ubuntu 18.04 vps. 
-----

#### Actual Behavior

Seems to complete the installation with a couple of deprecation notices & asks to Open the URL but it loads a blank page. The A record of the FQDN is correct.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of PHP you're running
PHP 7.2.24
- Version of MySQL/MariaDB you're running
MariaDB 10.1.44
- What OS and web server you're running Snipe-IT on
ubuntu 18.04 - apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs. 
apache error log
[Tue May 05 15:25:25.432361 2020] [php7:error] [pid 928] [client xxxxxxxxxxxxx] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40

- Include what you've done so far in the installation, and if you got any error messages along the way.
install.sh success just deprecation errors
- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by iqrait** [comment]
I rebuilt the VPS & ran it again exactly the same way & this time it worked with no dependencies errors & the preflght was visible & I completed it. 

Very strange - I did nothing different - same server image, same cloudinit?
