### ISSUE TITLE
Unable to send email using Office 365 crednetials

### ISSUE THREAD

**Issue by pavanandhukuri** [grokability/snipe-it#8136]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to send email using office 365 account. Following are the settings from my .env file. 
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=dhprojects@dhdigital.co.in
MAIL_PASSWORD=xxx
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=dhprojects@dhdigital.co.in
MAIL_FROM_NAME=dhprojects@dhdigital.co.in
MAIL_REPLYTO_ADDR=dhprojects@dhdigital.co.in
MAIL_REPLYTO_NAME=SnipeIT
MAIL_BACKUP_NOTIFICATION_ADDRESS=xxx@dhdigital.co.in

**Expected behavior**
Expected behavior is that the email should be delivered.

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.2 - build 4352 (master)
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 
PHP 7.2.31 (cli) (built: Jun  9 2020 08:18:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 83

**Error Messages**
I see the following error in storage/logs/laravel.log

[2020-06-15 06:05:22] production.ERROR: Connection could not be established with host smtp.office365.com :stream_socket_client(): unable to connect to tcp://smtp.office365.com:587 (Permission denied) {"userId":1,"email":"xxx@dhdigital.co.in","exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host smtp.office365.com :stream_socket_client(): unable to connect to tcp://smtp.office365.com:587 (Permission denied) at /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269)
[stacktrace]
#0 [internal function]: Swift_Transport_StreamBuffer->{closure}(2, 'stream_socket_c...', '/var/www/snipei...', 272, Array)
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(272): stream_socket_client('tcp://smtp.offi...', 13, 'Permission deni...', 30, 4, Resource id #765)
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#3 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#4 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(64): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
.......

**Additional context**
- Is this a fresh install or an upgrade? - Fresh
- What OS and web server you're running Snipe-IT on - CentOS, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.- NA
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by pavanandhukuri** [comment]
It was happening because of selinux enforcing policy in CentOS.. Fixed after I disabled it.
