### ISSUE TITLE
Cant import assets with custom fields

### ISSUE THREAD

**Issue by seekerOK** [grokability/snipe-it#8266]
Please confirm you have done the following before posting your bug report:
[x] I have enabled debug mode
[ x] I have read checked the Common Issues page
Describe the bug
creating a csv to import assets with custom fields wont import the custom fields values , the asset get created ok but the custom fields appears empty. 

To Reproduce
create a custom field , assign to the asset model
create a csv based on the one downloaded from your page 
fill the desired columns
add the custom field column exactly as it was created
import the file 
select that is an asset import
all the headers appear match except the custom one that I have to do it manually 
the preview looks good but when i processed the file the custom field appears empty

Expected behavior
the custom field get filled

Server (please complete the following information):

Snipe-IT Version 4.9.4
OS: [Ubuntu18.04]
Web Server: [Apache II]
PHP Version 7.2.32
Desktop (please complete the following information):

OS: [Windows]
Browser [chrome]
Version [84]
Error Messages

tail -f /var/www/snipeit/storage/logs/laravel.log
#97 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#98 /var/www/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#101 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#102 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#103 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#104 /var/www/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#105 {main}
"}

Additional context

Is this a fresh install or an upgrade? fresh

**Comment by seekerOK** [comment]
enabling debug doesnt shed any more info on the logs

**Comment by seekerOK** [comment]
any advice ?
