### ISSUE TITLE
Cannot login after upgrade GIT

### ISSUE THREAD

**Issue by dennislittle** [grokability/snipe-it#8306]
#### Expected Behavior (or desired behavior if a feature request)

Should login. If i type a wrong password it shows the error that the username and password is wrong
-----

#### Actual Behavior

Refresh of the site. We had one user that was logged in before the upgrade if he refreshes his page Snipe is working and he sees the new version number.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode Yes
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  **Upgrade**
- Version of Snipe-IT you're running  **v4.9.4**
- Version of PHP you're running **7.2.11**
- Version of MySQL/MariaDB you're running **5.7**
- What OS and web server you're running Snipe-IT on **Windows 2012 R2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **PHP update**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No Error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Login page**
- If a stacktrace is provided in the error, include that too. 
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **NO**
- Include any additional information you can find in `storage/logs` and your webserver's logs.

[2020-08-07 14:33:29] production.ERROR: include(C:\inetpub\wwwroot\snipe\vendor\composer/../schuppo/password-strength/src/Schuppo/PasswordStrength/PasswordStrengthServiceProvider.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(C:\\inetpub\\wwwroot\\snipe\\vendor\\composer/../schuppo/password-strength/src/Schuppo/PasswordStrength/PasswordStrengthServiceProvider.php): failed to open stream: No such file or directory at C:\\inetpub\\wwwroot\\snipe\\vendor\\composer\\ClassLoader.php:444)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\snipe\\vendor\\composer\\ClassLoader.php(444): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(C:\\\\inet...', 'C:\\\\inetpub\\\\wwwr...', 444, Array)
#1 C:\\inetpub\\wwwroot\\snipe\\vendor\\composer\\ClassLoader.php(444): include()
#2 C:\\inetpub\\wwwroot\\snipe\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\inetpub\\\\wwwr...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Schuppo\\\\Passwor...')
#4 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(635): spl_autoload_call('Schuppo\\\\Passwor...')
#5 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(582): Illuminate\\Foundation\\Application->resolveProvider('Schuppo\\\\Passwor...')
#6 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php(75): Illuminate\\Foundation\\Application->register('Schuppo\\\\Passwor...')
#7 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#8 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#9 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#10 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#11 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#12 C:\\inetpub\\wwwroot\\snipe\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#13 C:\\inetpub\\wwwroot\\snipe\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#14 {main}
"} 

- Include what you've done so far in the installation, and if you got any error messages along the way.

Tried a manual update 
Changed the default location for PHP
Upgraded composer
Ran all the common command line things

- Indicate whether or not you've manually edited any data directly in the database **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by dennislittle** [comment]
We found the issue. Secure cookie was enabled.
