### ISSUE TITLE
Add Raspberry Pi OS support to the install script

### ISSUE THREAD

**Issue by jackmalcom** [grokability/snipe-it#8342]
The title is fairly self explanatory, running `./install.sh` gives the following output on Raspberry Pi OS:

```
       _____       _                  __________
      / ___/____  (_)___  ___        /  _/_  __/
      \__ \/ __ \/ / __ \/ _ \______ / /  / /
     ___/ / / / / / /_/ /  __/_____// /  / /
    /____/_/ /_/_/ .___/\___/     /___/ /_/
                /_/


  Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer was unable to determine your OS. Exiting for safety.
```

Raspberry Pi OS is Debian based so it should work with very minimal modification.

**Comment by snipe** [comment]
We'd be open to accepting a PR on this, but we do not have any Pis to test anything on.

**Comment by n3s0** [comment]
If this is still relevant I would be happy to assist with testing. Would upload any logs or data you guys need.

**Comment by snipe** [comment]
I know people have installed this on a Raspberry Pi just using the standard install process. Again, I'd be willing to take a PR on this, but so far no one has offered one.

**Comment by n3s0** [comment]
I'll test this on the latest version of Raspbian and get back to you. Looks like a PR request has already been applied.

- [Added code to snipeit.sh for Raspbian 9.4 install (https://github.com/snipe/snipe-it/pull/5980)](https://github.com/snipe/snipe-it/commit/5c820dd7b8a9187072073d778bbaf20d72269ff0)

**Comment by n3s0** [comment]
I've tested this on the following board model.

```
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.15.32-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022
[    0.000000] random: fast init done
[    0.000000] Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000001ec00000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000] percpu: Embedded 28 pages/cpu s77144 r8192 d29352 u114688
[    0.000000] pcpu-alloc: s77144 r8192 d29352 u114688 alloc=28*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: ARM erratum 843419
[    0.000000] CPU features: detected: ARM erratum 845719

```

Script was run on Raspberry Pi OS. Which is just Debian 11.

Looks like it works. I installed it with a mariadb and apache2 already installed. Script detected it with no issue.

Upon running the install.sh script it downloaded the snipeit.sh script and went through its normal operation and did the needful. 

Some issues presented themselves as shown in the apache error.log output below.

```
[Fri Sep 09 23:03:32.275115 2022] [php7:error] [pid 47356] [client 192.168.0.33:35006] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187
[Fri Sep 09 23:03:32.284765 2022] [php7:error] [pid 47356] [client 192.168.0.33:35006] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipeit/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(187): file_put_contents()\n#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(200): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(363): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 187
```

There were some issues with the storage, vendor, and cache directories. But, this was fixed by updating the permissions of those directories.

Script works really well. There are just some things after the fact that may need to be done like checking the typical file and directory permissions of laravel's storage, logs, and cache files/directories so they have the necessary permissions.

Can certainly do another run of the script in the afternoon tomorrow. Just thought I'd post my findings.
