### ISSUE TITLE
"Uncaught PDOException" during installation

### ISSUE THREAD

**Issue by colingoodman** [grokability/snipe-it#8349]
I am conducting a test (fresh + manual) install on an Ubuntu machine using an Apache web-server and MySQL db. 

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
While attempting to view the pre-flight page, an "Uncaught PDOException" error occurs. I see a page with a red header detailing the exception. Exceptions are below.

**To Reproduce**
Load Snipe-IT webpage during pre-flight step of the installation process.

I have verified via `php -m` that PDO, PDO_mysql, and other dependencies are installed.
 
**Server (please complete the following information):**
 - Snipe-IT Version 4.9.4 (latest)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 79

**Error Messages**

*Error message in Snipe logs:*
`PHP Fatal error:  Uncaught PDOException: could not find driver in /snipe/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27\nStack trace:\n#0 /snipe/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=[host], 'snipe_user', [password], Array)\n#1 /snipe/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=[host], 'snipe_user', [password], Array)\n#2 /snipe/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=[host], 'snipe_user', [password], Array)\n#3 /snipe/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=[host], Array, Array)\n#4 /snipe/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySq in /snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664`

*Information from exception webpage:* 
(1/3) PDOException could not find driver in PDOConnection.php line 27
(2/3) PDOException could not find driver in PDOConnection.php line 31
(3/3) QueryException could not find driver (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users) in Connection.php line 664

Let me know if additional information for troubleshooting is necessary. I appreciate any help!

**Comment by colingoodman** [comment]
Determined that the extensions I had installed were for the wrong version of PHP. I installed the correct versions and have solved the issue.
