### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by chandtech89** [grokability/snipe-it#8420]
I was trying to login into snipe IT but unable to login. It doesn't throw any error, only page get refreshed.
Initially it is working fine.

 I have enabled debug mode 

Log:
production.ERROR: Failed to authenticate on SMTP server with username "YOURUSERNAME" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 334 but got code "530", with message "530 Must issue a STARTTLS command first
#89 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#90 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle()
#91 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#92 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#93 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#94 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#95 /var/www/html/snipe/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#96 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Cors\HandlePreflight->handle()
#97 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#98 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#99 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then()
#100 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#101 /var/www/html/snipe/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#102 {main}  

no, I am facing this suddenly - Is this a fresh install or an upgrade? 
PHP 7.4.3 - Version of PHP you're running
mariadb 10.4 - Version of MySQL/MariaDB you're running
centos 8 - What OS and web server you're running Snipe-IT on
manual installation - What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
yes - WITH DEBUG TURNED ON, if you're getting an error in your browser,
login page - What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
No- Any errors that appear in your browser's error console.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Check your .env and make sure your cookie session values make sense for your setup. The COOKIE_DOMAIN should be set to the domain name you're hosting it on, and SECURE_COOKIES should only be set to true if you're running over https.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
