### ISSUE TITLE
Pre-flight looking for database tables, when none should exist yet

### ISSUE THREAD

**Issue by adagioajanes** [grokability/snipe-it#8526]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Pre-flight is looking for the users table, when there should not be a users table in existence yet.

This was done using a development build that was not released. However, it was requested (#8513)  that I test something else using the latest development build (commit 36436f7)

**To Reproduce**
1. Setup a fresh snipe-it instance based on commit 36436f7 in the develop branch
2. Configure environment
3. `composer install`
4. Attempt to access pre-flight

**Expected behavior**
Pre-flight should load, and should not expect any database tables to exist yet.

**Screenshots**
![image](https://user-images.githubusercontent.com/38761237/96297921-a2d57380-0fbf-11eb-96b7-eeb5987f4136.png)

**Server (please complete the following information):**
 - Snipe-IT Version: develop branch commit 36436f7
 - OS: Windows
 - Web Server: Azure App Service
 - PHP Version: 7.3.22

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge (chromium based)
 - Version: latest

**Error Messages**
```
[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.users' doesn't exist at D:\\home\\site\\wwwroot\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:64)
[stacktrace]
#0 D:\\home\\site\\wwwroot\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php(64): PDO->prepare('select * from `...', Array)
#1 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(331): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')
#2 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#3 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#4 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(338): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#5 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2149): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#6 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#7 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#8 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#9 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(537): Illuminate\\Database\\Query\\Builder->get(Array)
#10 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(521): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#11 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#12 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\EloquentUserProvider.php(68): Illuminate\\Database\\Eloquent\\Builder->first()
#13 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\SessionGuard.php(177): Illuminate\\Auth\\EloquentUserProvider->retrieveByToken('1', 'hobMcxIFmzL04sV...')
#14 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\SessionGuard.php(147): Illuminate\\Auth\\SessionGuard->userFromRecaller(Object(Illuminate\\Auth\\Recaller))
#15 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\AuthManager.php(54): Illuminate\\Auth\\SessionGuard->user()
#16 [internal function]: Illuminate\\Auth\\AuthManager->Illuminate\\Auth\\{closure}(NULL)
#17 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\AuthServiceProvider.php(84): call_user_func(Object(Closure), NULL)
#18 [internal function]: Illuminate\\Auth\\AuthServiceProvider->Illuminate\\Auth\\{closure}(NULL)
#19 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Request.php(522): call_user_func(Object(Closure), NULL)
#20 D:\\home\\site\\wwwroot\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(82): Illuminate\\Http\\Request->user(NULL)
#21 D:\\home\\site\\wwwroot\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(70): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->requestShouldReceiveFreshToken(Object(Illuminate\\Http\\Request))
#22 D:\\home\\site\\wwwroot\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(52): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->shouldReceiveFreshToken(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#23 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 D:\\home\\site\\wwwroot\\app\\Http\\Middleware\\CheckForTwoFactor.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForTwoFactor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 D:\\home\\site\\wwwroot\\app\\Http\\Middleware\\CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 D:\\home\\site\\wwwroot\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 D:\\home\\site\\wwwroot\\app\\Http\\Middleware\\SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 D:\\home\\site\\wwwroot\\app\\Http\\Middleware\\CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 D:\\home\\site\\wwwroot\\app\\Http\\Middleware\\CheckForSetup.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 D:\\home\\site\\wwwroot\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 D:\\home\\site\\wwwroot\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#63 D:\\home\\site\\wwwroot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#64 D:\\home\\site\\wwwroot\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#65 {main}
"} 
```

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What OS and web server you're running Snipe-IT on: Azure App Service Windows Based
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- Include what you've done so far in the installation, and if you got any error messages along the way: See above
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by snipe** [comment]
This should be fixed on develop
