### ISSUE TITLE
Can't display correct Admin settings after upgraded v5.0.7

### ISSUE THREAD

**Issue by dhkivan** [grokability/snipe-it#8793]
After upgraded v5.0.7, I can't change any settings in Admin Setting, nothing to be changed in webpage after modified and clicked Save, but double checked in mysql, the settings have been changed. And also can't change back the same value, e.g. now is showed ABC company in Site Name, I have changed to BCD company, in browser is still showed ABC company, but mysql has been changed to BCD company. Then I changed back to ABC company in browser, no change in browser and mysql. What's wrong.

I have deleted the cache in browsers and tried to use different account, but it is same.

By they way, all records can't be showed in IE, Chrome is no problem.
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What's in your app logs? Also can you confirm that your password minimum length requirement is 8 or higher?

**Comment by dhkivan** [comment]
The password is more than 8 char

and here is the log, but seems not related?

2020-11-27 01:00:02] production.ERROR: Class 'App\Console\Commands\AlertRecipient' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Console\\Commands\\AlertRecipient' not found at /var/www/snipe-it/app/Console/Commands/SendExpectedCheckinAlerts.php:59)
Stack trace:
#0 [internal function]: App\Console\Commands\SendExpectedCheckinAlerts->App\Console\Commands\{closure}()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#2 /var/www/snipe-it/app/Console/Commands/SendExpectedCheckinAlerts.php(60): Illuminate\Support\Collection->map()
#3 [internal function]: App\Console\Commands\SendExpectedCheckinAlerts->handle()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#7 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#9 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#10 /var/www/snipe-it/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#11 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#12 /var/www/snipe-it/vendor/symfony/console/Application.php(1001): Illuminate\Console\Command->run()
#13 /var/www/snipe-it/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/snipe-it/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#15 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#16 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run()
#17 /var/www/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#18 {main}  

[2020-11-27 01:00:02] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Console\Commands\AlertRecipient' not found in /var/www/snipe-it/app/Console/Commands/SendExpectedCheckinAlerts.php:59
[stacktrace]
#0 [internal function]: App\\Console\\Commands\\SendExpectedCheckinAlerts->App\\Console\\Commands\\{closure}()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#2 /var/www/snipe-it/app/Console/Commands/SendExpectedCheckinAlerts.php(60): Illuminate\\Support\\Collection->map()
#3 [internal function]: App\\Console\\Commands\\SendExpectedCheckinAlerts->handle()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#9 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#10 /var/www/snipe-it/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#11 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#12 /var/www/snipe-it/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run()
#13 /var/www/snipe-it/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /var/www/snipe-it/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#15 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#16 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#17 /var/www/snipe-it/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#18 {main}
"}

**Comment by dhkivan** [comment]
After upgraded to v5.0.10, I can't enable debug mode.

**Comment by snipe** [comment]
Are you still seeing this issue? This ticket is pretty old, and I'd like to close it if it's been resolved in more recent versions of Snipe-IT.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
