### ISSUE TITLE
Yet another gmail test email problem

### ISSUE THREAD

**Issue by pathfndr** [grokability/snipe-it#8868]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When sending a test email from the setup landing page I receive the error: 
Mail could not be sent.
Error: undefined

**To Reproduce**
1. Setup landing page
2. Click on send test email
3. See error

**Expected behavior**
A test email to be delivered to my gmail account

**Screenshots**
contents of .env file
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=ehrsnipeit@gmail.com
MAIL_PASSWORD='MYPASSWORD'
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=ehrsnipeit@gmail.com
MAIL_FROM_NAME='SnipeIT'
MAIL_REPLYTO_ADDR=fae@gmail.com
MAIL_REPLYTO_NAME='SnipeIT'
MAIL_AUTO_EMBED_METHOD='attachment'

I have confirmed I have "Access to less secure apps" turned on in the gmail account
I have tried the displayunlockcapitcha link in the account.
I have run php artisan config:clear
I have tried various " and ' combinations in .env file
I have scoured the other issues related to gmail but could not find reference to the error noted below.
**Server (please complete the following information):**
 - Snipe-IT Version 5.0.10
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.4.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows server 2012R2
 - Browser [e.g. chrome, safari] Firefox 83.  Also tried Chrome

**Smartphone (please complete the following information):**

**Error Messages**
[2020-12-05 03:36:04] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class name must be a valid object or a string in /var/www/html/snipeit/storage/framework/views/4e39205bc7c01ed3327193a5d8f9692f0d6e33b4.php:54
Stack trace:
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include()
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(143): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(82): Illuminate\View\View->render()
#6 /var/www/html/snipeit/storage/framework/views/faa4c51c73b218fdf1efa864aae6e1f5b65b84f9.php(8): Illuminate\View\Factory->renderComponent()
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/html/s...')
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(143): Illuminate\View\Engines\CompilerEngine->get()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(64): Illuminate\View\View->render()
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(101): Illuminate\Mail\Markdown->render()
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView()
#15 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(146): Illuminate\Notifications\Channels\MailChannel->send()
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(105): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#17 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#18 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(107): Illuminate\Notifications\NotificationSender->withLocale()
#19 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow()
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#21 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send()
#22 /var/www/html/snipeit/app/Http/Controllers/SettingsController.php(1207): App\Models\User->notify()
#23 [internal function]: App\Http\Controllers\SettingsController->ajaxTestEmail()
#24 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#25 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#26 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#27 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#28 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#29 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#30 /var/www/html/snipeit/app/Http/Middleware/AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle()
#32 /var/www/html/snipeit/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#34 /var/www/html/snipeit/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle()
#36 /var/www/html/snipeit/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckLocale->handle()
#38 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#40 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#42 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#44 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
#46 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#47 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#48 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
#49 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch()
#50 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#51 /var/www/html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#53 /var/www/html/snipeit/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle()
#55 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#57 /var/www/html/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle()
#59 /var/www/html/snipeit/app/Http/Middleware/CheckForSetup.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle()
#61 /var/www/html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
#63 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#65 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#67 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#69 /var/www/html/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle()
#71 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#73 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#74 /var/www/html/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#75 {main}
**Additional context**
- Is this a fresh install or an upgrade? Fresh Install 
- What OS and web server you're running Snipe-IT on see above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
  I received error messages about permission on the ./storage directory when first running setup.  Some sub directories were owned by root.  I changed the owner to www-data and the group to www-data and it resolved the problem.
- Indicate whether or not you've manually edited any data directly in the database - NO

**Comment by jovibroz** [comment]
My best guess is that you will need to create an app password for Snipe-IT in your google account.

Google Account -> Security -> App password (Google Login section)
Choose a name for you app password and hit "create"
Write it down and then copy it into your .env replacing your normal password.

See if it helps :)

**Comment by pathfndr** [comment]
Jovibroz - Thanks but that didn't work.  I activated 2-step verification.  Created a 16 character app password.  Copied it into the .env  in the mail_password section and ran sudo php artisan config:clear.  Same error :(

**Comment by jovibroz** [comment]
Ah too bad.. I'm not enough skilled to trouble shoot this kind of error but I've had many errors before I was up and running nicely :) What ubuntu version? Seems like some dependency are not configured correctly to me.. the noob :)

**Comment by pathfndr** [comment]
> Ah too bad.. I'm not enough skilled to trouble shoot this kind of error but I've had many errors before I was up and running nicely :) What ubuntu version? Seems like some dependency are not configured correctly to me.. the noob :)

I'm going to check that actually.  That's what I was thinking too.

**Comment by djmixman** [comment]
Any luck solving this issue? I'm running into the same problem with a docker install.

**Comment by pathfndr** [comment]
Nope. We installed postfix locally, pointed snipe-it to localhost and used
the same gmail smtp account to send via postfix and got it to work that
way.
