### ISSUE TITLE
Can't Attach and Save an Image to an Asset Model on the /models/# page?   500 Error

### ISSUE THREAD

**Issue by brockdrew** [grokability/snipe-it#8998]
#### Expected Behavior (or desired behavior if a feature request)

I upload an image to http://snipe-it.com/models/2/edit  in Update Asset Model,  I got here from Actions  > Edit Model on the models page. 
A .JPG is uploaded as the Image of an Asset Model.

-----

#### Actual Behavior

500 error is returned by Snipe IT, not the browser.  

Title: Server Error

500 | Server Error

Image is never saved to the model! 
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 4.7.8 didnt work, i just upgraded to 5.0.12 and it didnt work either.  Chrome/Firefox
- Version of Snipe-IT you're running 5.0.12
- Version of PHP you're running  7.2.24
- Version of MySQL/MariaDB you're running 10.3
- What OS and web server you're running Snipe-IT on   Centos 8  ,  Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)   git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - its the same error with debug mode turned on
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error http://snipe.com/models/2
- If a stacktrace is provided in the error, include that too.  POST - 500 INTERNAL SERVER ERROR
- Any errors that appear in your browser's error console. POST - 500 INTERNAL SERVER ERROR
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  No! it works fine on the demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.

[snipeit@icrd-inventory logs]$ tail -f laravel.log
#29 /opt/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /opt/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 /opt/snipeit/vendor/symfony/console/Application.php(969): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /opt/snipeit/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Passport\\Console\\InstallCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /opt/snipeit/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /opt/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /opt/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /opt/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 {main}
"}

- Include what you've done so far in the installation, and if you got any error messages along the way.   i upgraded using the apache user and your upgrade.php today
- Indicate whether or not you've manually edited any data directly in the database   no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Hi there - I know this is a pretty old issue, but I wanted to check and see if you ever got this resolved? If so, can you please close the ticket? If not, can you update us on what version of Snipe-IT you're currently using, so we can see if it's still an issue on latest?

:) Thanks!

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
