### ISSUE TITLE
Application not works after upgrade 

### ISSUE THREAD

**Issue by LetArch** [grokability/snipe-it#9045]
Hello! I tryied to upgrade just php upgrade.php - not work. Old version app not started now ((
Tryied to start fresh install - not work.
**Screenshot**
Log httpd:
![image](https://user-images.githubusercontent.com/3818210/105687864-63011f00-5f12-11eb-8097-e7d282bb8174.png)

**Server **
 - Snipe-IT 5.0.12
 - OS: CentOS 7
 - Web Server: Apache, IIS
 - PHP Version 7.3.26

**Desktop **
 - OS: win10
 - Browser chrome
 - Version 87

**Error Messages**
`[Mon Jan 25 15:51:03.448957 2021] [php7:error] [pid 28274] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/snipe-it/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: No such file or directory in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/snipe-...', 133, Array)\n#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/snipe-...', '9999999999N;', 2)\n#2 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/snipe-...', '9999999999N;', true)\n#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(138): Illuminate\\Cache\\FileStore->put('snipeit_app_set...', NULL, 0)\n#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->foreve in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133`

**Comment by LetArch** [comment]
Solved it issue, when fresh install via install.sh. Thanks for it!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
