### ISSUE TITLE
No matching records found

### ISSUE THREAD

**Issue by sfrielink** [grokability/snipe-it#9091]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**After entering a new company or person in a brand new installation of Snipe-it, the website returns the message "No matching records found"**

**To Reproduce**
**1. Go to 'Settings'
2. Click on 'Companies'
3. Click on Create New
4. Enter company information
5. Click Save
6. Message = Success: Company created successfully
6. Companies Listing = No matching records found**

**Expected behavior**
**Expected to see the name of the company I just entered.**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  - **v5.0.12 build 5705 (gf1d0d1bfe)** 
 - OS: **Windows Server 2016**
 - Web Server: **IIS**
 - PHP Version: **7.3.26**
 - Chrome Browser

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:

**Unauthenticated.                                                                              Illuminate\Auth\AuthenticationException
C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php#81**

 ***/
    protected function unauthenticated($request, array $guards)
    {
            throw new AuthenticationException(
                'Unauthenticated.', $guards, $this->redirectTo($request)
        );
    }**

#0 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(67): Illuminate\Auth\Middleware\Authenticate->unauthenticated(Object(Illuminate\Http\Request), Array)
#1 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(41): Illuminate\Auth\Middleware\Authenticate->authenticate(Object(Illuminate\Http\Request), Array)
#2 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#3 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#4 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#7 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#8 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#10 C:\inetpub\wwwroot\Snipe-IT\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\inetpub\wwwroot\Snipe-IT\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\inetpub\wwwroot\Snipe-IT\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\inetpub\wwwroot\Snipe-IT\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\Snipe-IT\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#34 {main}

**-** Include the output from `php -m` (this should display what modules you have enabled.)

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Additional context**
- Is this a fresh install or an upgrade? **Fresh install**
- What OS and web server you're running Snipe-IT on  **Windows Server 2016, IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- Include what you've done so far in the installation, and if you got any error messages along the way.  **Tried to do as many things as I could find as suggested in the on-line help and the numerous Snipe-it issues.  Thought the PHP version might be the problem, so went from 8.0 to 7.4 and then 7.3 based on one issue I looked at.  Performed updates of PHP and Composer many times.**
- Indicate whether or not you've manually edited any data directly in the database - **I have not manually edited any data in the database, however I can see that the company data that I entered was present in the database, it is just not rendering in the web app.**

Add any other context about the problem here. - **This seems that it should be a simple problem but after many hours I cannot solve it.  Obviously the "unauthenticated" error message is a good clue, but my limited .Net programming skills are not up to the challenge.  Help would be most appreciated.**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by sfrielink** [comment]
After waiting for a while I checked back in with the Snipe-IT home page and saw that there was a new version out, 5.5.1.  I figured it couldn't hurt to try upgrading.  I also switched over from a manual install to the Git install.  Not sure why, but once I completed the upgrade the problem was fixed.  Hope this helps someone else with a similar problem.
