### ISSUE TITLE
Expected checkin artisan job fails

### ISSUE THREAD

**Issue by Minor-Kontor** [grokability/snipe-it#9116]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
`/var/www/snipe-it/artisan snipeit:expected-checkin` fails with error message

**To Reproduce**
1. Open shell
2. Enter `sudo -u www-data /usr/bin/php /var/www/snipe-it/artisan snipeit:expected-checkin`
3. See error

**Expected behavior**
Should not fail and send reminder emails for expected checkin items.

**Server (please complete the following information):**
 - 5.1.0
 - OS: debian
 - Web Server: apache2
 - PHP 7.3

**Desktop:**
 - Not applicable

**Smartphone:**
 - Not applicable

**Error Messages**
```
# sudo -u www-data /usr/bin/php /var/www/snipe-it/artisan snipeit:expected-checkin
2021-02-16 14:45:04 is deadline
6 assets

In UrlGenerationException.php line 17:

  Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. (View: /var/www/snipe-it/resourc
  es/views/notifications/markdown/report-expected-checkins.blade.php)


In UrlGenerationException.php line 17:

  Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}].
```

**Additional context**
- Upgrade from 4.x
- Installed via install.sh (AFAIR)
- No manual database edits

**Comment by kno005** [comment]
I am also getting the same. Expected checkin email notifications are failing to go out.

From console:
```
C:\inetpub\wwwroot\snipe-it>php artisan snipeit:expected-checkin
2021-02-24 07:43:14 is deadline
9 assets

In UrlGenerationException.php line 17:

  Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. (View: C:\inetpub\wwwroot\snipe-it\resources\views\notifications\markdown\report-expected-checkins.blade.php)


In UrlGenerationException.php line 17:

  Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}].

```


From Laravel.log

```
[2021-02-17 00:00:29] production.ERROR: Illuminate\Routing\Exceptions\UrlGenerationException: Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\RouteUrlGenerator.php(91): Illuminate\Routing\Exceptions\UrlGenerationException::forMissingParameters(Object(Illuminate\Routing\Route))
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(436): Illuminate\Routing\RouteUrlGenerator->to(Object(Illuminate\Routing\Route), Array, true)
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(417): Illuminate\Routing\UrlGenerator->toRoute(Object(Illuminate\Routing\Route), Array, true)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(777): Illuminate\Routing\UrlGenerator->route('hardware.show', Array, true)
#4 C:\inetpub\wwwroot\snipe-it\storage\framework\views\e74bee1533e301bf8f348aab54a8eb9d466fd997.php(13): route('hardware.show', Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('C:\\inetpub\\wwwr...')
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Markdown.php(64): Illuminate\View\View->render()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(101): Illuminate\Mail\Markdown->render('notifications.m...', Array)
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView(Object(Illuminate\Notifications\Messages\MailMessage))
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Recipients\AlertRecipient), Object(App\Notifications\ExpectedCheckinAdminNotification))
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Recipients\AlertRecipient), 'c3fb9fff-696b-4...', Object(App\Notifications\ExpectedCheckinAdminNotification), 'mail')
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#20 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpectedCheckinAlerts.php(62): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SendExpectedCheckinAlerts->handle()
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call(Array)
#27 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SendExpectedCheckinAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}

Next Illuminate\View\ViewException: Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. (View: C:\inetpub\wwwroot\snipe-it\resources\views\notifications\markdown\report-expected-checkins.blade.php) in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Illuminate\Routing\Exceptions\UrlGenerationException), 0)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Markdown.php(64): Illuminate\View\View->render()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(101): Illuminate\Mail\Markdown->render('notifications.m...', Array)
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView(Object(Illuminate\Notifications\Messages\MailMessage))
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Recipients\AlertRecipient), Object(App\Notifications\ExpectedCheckinAdminNotification))
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Recipients\AlertRecipient), 'c3fb9fff-696b-4...', Object(App\Notifications\ExpectedCheckinAdminNotification), 'mail')
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#15 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpectedCheckinAlerts.php(62): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SendExpectedCheckinAlerts->handle()
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call(Array)
#22 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SendExpectedCheckinAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}  
[2021-02-17 07:43:15] production.ERROR: Illuminate\Routing\Exceptions\UrlGenerationException: Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\RouteUrlGenerator.php(91): Illuminate\Routing\Exceptions\UrlGenerationException::forMissingParameters(Object(Illuminate\Routing\Route))
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(436): Illuminate\Routing\RouteUrlGenerator->to(Object(Illuminate\Routing\Route), Array, true)
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(417): Illuminate\Routing\UrlGenerator->toRoute(Object(Illuminate\Routing\Route), Array, true)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(777): Illuminate\Routing\UrlGenerator->route('hardware.show', Array, true)
#4 C:\inetpub\wwwroot\snipe-it\storage\framework\views\e74bee1533e301bf8f348aab54a8eb9d466fd997.php(13): route('hardware.show', Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('C:\\inetpub\\wwwr...')
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Markdown.php(64): Illuminate\View\View->render()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(101): Illuminate\Mail\Markdown->render('notifications.m...', Array)
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView(Object(Illuminate\Notifications\Messages\MailMessage))
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Recipients\AlertRecipient), Object(App\Notifications\ExpectedCheckinAdminNotification))
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Recipients\AlertRecipient), '5c5cdfaa-5cfd-4...', Object(App\Notifications\ExpectedCheckinAdminNotification), 'mail')
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#20 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpectedCheckinAlerts.php(62): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SendExpectedCheckinAlerts->handle()
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call(Array)
#27 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SendExpectedCheckinAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}

Next Illuminate\View\ViewException: Missing required parameters for [Route: hardware.show] [URI: hardware/{hardware}]. (View: C:\inetpub\wwwroot\snipe-it\resources\views\notifications\markdown\report-expected-checkins.blade.php) in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Illuminate\Routing\Exceptions\UrlGenerationException), 0)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Markdown.php(64): Illuminate\View\View->render()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(101): Illuminate\Mail\Markdown->render('notifications.m...', Array)
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView(Object(Illuminate\Notifications\Messages\MailMessage))
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Recipients\AlertRecipient), Object(App\Notifications\ExpectedCheckinAdminNotification))
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Recipients\AlertRecipient), '5c5cdfaa-5cfd-4...', Object(App\Notifications\ExpectedCheckinAdminNotification), 'mail')
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\ExpectedCheckinAdminNotification))
#15 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\SendExpectedCheckinAlerts.php(62): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\SendExpectedCheckinAlerts->handle()
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call(Array)
#22 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SendExpectedCheckinAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}  

```

**Comment by kno005** [comment]
It appears to be working for the user emails. It is just the Admin emails that are failing.

**Comment by snipe** [comment]
This is now fixed on develop and will be in the next release

**Comment by kno005** [comment]
> This is now fixed on develop and will be in the next release

You rock, thanks!

**Comment by Minor-Kontor** [comment]
Thanks!
