### ISSUE TITLE
Sending notification emails through google smtp relay fails

### ISSUE THREAD

**Issue by henningkessler** [grokability/snipe-it#9140]
**Describe the bug**
after upgrading to 5.0.11 or 5.1.1 snipe-it stopped mailing me notifications about expiring assets and such events.
When I ran the command from the CLI I get:
```
snipe@snipeit[17:14][/usr/local/www/snipeit]: /usr/local/bin/php /usr/local/www/snipeit/artisan snipeit:inventory-alerts
There is 1 item that is below minimum inventory or will soon be low.

In AbstractSmtpTransport.php line 448:
                                                        
  Expected response code 250 but got an empty response  
                                                        
```

Funny fact is that sending test emails still works ;-).

From the laravel.log
```
[2021-02-15 17:14:36] production.ERROR: Expected response code 250 but got an empty response {"exception":"[object] (Swift_TransportException(code: 0): Expected response code 250 but got an empty response at /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:448)
[stacktrace]
#0 /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(345): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('HELO [127.0.0.1...', Array, Array, false, NULL)
#2 /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(368): Swift_Transport_EsmtpTransport->executeCommand('HELO [127.0.0.1...', Array)
#3 /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->doHeloCommand()
#4 /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#5 /usr/local/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#6 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(488): Swift_Mailer->send(Object(Swift_Message), Array)
#7 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#8 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
#9 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\Models\\Recipients\\AlertRecipient), Object(App\\Notifications\\InventoryAlert))
#10 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\Models\\Recipients\\AlertRecipient), '7ffe9b0f-517a-4...', Object(App\\Notifications\\InventoryAlert), 'mail')
#11 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#12 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\\Notifications\\NotificationSender->withLocale(NULL, Object(Closure))
#13 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\InventoryAlert))
#14 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\InventoryAlert))
#15 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Notifications\\ChannelManager->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\InventoryAlert))
#16 /usr/local/www/snipeit/app/Console/Commands/SendInventoryAlerts.php(55): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#17 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\SendInventoryAlerts->handle()
#18 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#20 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#23 /usr/local/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#25 /usr/local/www/snipeit/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /usr/local/www/snipeit/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\SendInventoryAlerts), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /usr/local/www/snipeit/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /usr/local/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /usr/local/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 {main}
"} 
```

Email setting from .env:
```
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.gmail.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=it@domain.de
MAIL_FROM_NAME='Asset-XX'
MAIL_REPLYTO_ADDR=it@domain.de
MAIL_REPLYTO_NAME='Asset-XX'
```

**Expected behavior**
Email should be send

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.1 
 - OS: FreeBSD 12.2p2
 - Web Server: NGINX
 - PHP Version: 7.4.13

**Comment by frapbod** [comment]
@henningkessler Did you ever figure out how to fix this? We use google smtp and are running into the exact same error.

**Comment by henningkessler** [comment]
No, instead I created a specific account for this kind of stuff, which is a sad solution…

**Comment by s-b-e-n-s-o-n** [comment]
The relay doesn't like 127.0.0.1 for the HELO command after a bit apparently.

I added:

`'local_domain' => env('MAIL_HOST'),`

To:

`/path/to/snipe-it/config/mail.php`

Which resolved this issue for both cron jobs and manual runs for me.
