### ISSUE TITLE
Back ups failing

### ISSUE THREAD

**Issue by LeeSharman** [grokability/snipe-it#9213]
#### Expected Behavior (or desired behavior if a feature request)

Backup of database

-----

#### Actual Behavior

Get a General error the system cannot find the path specified

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running 5.1.1 build 5811
- Version of PHP you're running 7.4.13
- Version of MySQL/MariaDB you're running 10.5
- What OS and web server you're running Snipe-IT on  Server 2019 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. . #0 C:\Snipe-IT\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\Snipe-IT\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(252): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Support\Collection.php(638): array_map() #5 C:\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(255): Illuminate\Support\Collection->map() #6 C:\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(169): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 C:\Snipe-IT\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(145): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 C:\Snipe-IT\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle() #10 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #11 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #12 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #13 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call() #14 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call() #15 C:\Snipe-IT\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute() #16 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run() #17 C:\Snipe-IT\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run() #18 C:\Snipe-IT\vendor\symfony\console\Application.php(1009): Spatie\Backup\Commands\BaseCommand->run() #19 C:\Snipe-IT\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand() #20 C:\Snipe-IT\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun() #21 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run() #22 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Console\Application.php(185): Illuminate\Console\Application->run() #23 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(273): Illuminate\Console\Application->call() #24 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #25 C:\Snipe-IT\app\Http\Controllers\SettingsController.php(1057): Illuminate\Support\Facades\Facade::__callStatic() #26 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\SettingsController->postBackups() #27 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #28 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch() #29 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController() #30 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run() #31 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 C:\Snipe-IT\app\Http\Middleware\CheckPermissions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckPermissions->handle() #34 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle() #36 C:\Snipe-IT\app\Http\Middleware\AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle() #38 C:\Snipe-IT\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 C:\Snipe-IT\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle() #42 C:\Snipe-IT\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckLocale->handle() #44 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #46 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #48 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #50 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute() #54 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 C:\Snipe-IT\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #59 C:\Snipe-IT\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle() #61 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #63 C:\Snipe-IT\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle() #65 C:\Snipe-IT\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle() #67 C:\Snipe-IT\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #69 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #71 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #73 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #75 C:\Snipe-IT\app\Http\Middleware\NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #76 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle() #77 C:\Snipe-IT\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #78 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle() #79 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #80 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #81 C:\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #82 C:\Snipe-IT\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle() #83 {main} Backup failed because: The dump process failed with exitcode 1 : General error : The system cannot find the path specified. .
- 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  Backups
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. Set permissions for IIS_IUSRS on Temp folder,Storage folder,Public Folder etc
DB_DUMP_PATH='C:\\PROGRA~1\\MariaDB~1.5\\bin'
- Indicate whether or not you've manually edited any data directly in the database no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by LeeSharman** [comment]
I have manged to rectify this. In my .env file the path to the database dump folder was incorrect even though i had followed the instructions. I cross referenced an old install we had and changed. The back up runs fine now.
Path was C:\\PROGRA~1MariaDB~10.5\\bin  changed to 'C:\\PROGRA~1\\MARIAD~1.5\\bin' and now works
