### ISSUE TITLE
just installation issue 

### ISSUE THREAD

**Issue by fayazivolve** [grokability/snipe-it#9228]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]  
 - centos 
 - Web Server: [e.g. Apache, IIS]
 - apache 
 - PHP Version 
 7.4
**Desktop (please complete the following information):**
 - chorme

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

Error: 

[Mon Mar 01 15:38:21.721070 2021] [php7:error] [pid 31802] [client 172.16.0.153:55217] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipe/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: No such file or directory in /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()\n#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html/snipe in /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Mon Mar 01 15:38:21.723025 2021] [php7:error] [pid 31802] [client 172.16.0.153:55217] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/snipe/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: No such file or directory in /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()\n#2 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html/snipe in /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133

looking someone who guide me properlly

**Comment by fayazivolve** [comment]
Is this a fresh install or an upgrade?
fresh 
What OS and web server you're running Snipe-IT on
centos 7
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual 
Include what you've done so far in the installation, and if you got any error messages along the way.
complete isntallation but facing thisissue afer installation . 
Indicate whether or not you've manually edited any data directly in the database
no

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
