### ISSUE TITLE
LDAP Login Test - 500 Server Error

### ISSUE THREAD

**Issue by sonicnkt** [grokability/snipe-it#9273]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X]  I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Im trying to configure ldap sync and authentication with snipe-it-
My configuration seems to work fine and sync is working without issues, but i can't get ldap authentication working.

The Test LDAP Login Function in snipe-it shows `500 Server Error` with correct credentials. Incorrect ones report `Unable to validate user credentials!` so authentication seems to be working

My LDAP server logs only show that the user had bind succes and did a search request for (uid=test_user). 
My config does not seem to be the issue here.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5454622/110628370-398b1280-81a3-11eb-925e-4fec3655d42e.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.3 build 5862 (gc3871c98d)
 - OS: Docker, Debian Host

**Error Messages**
```
[2021-03-10 11:28:10] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to App\Services\LdapAd::isLdapSync() must be an instance of Adldap\Models\User, instance of Adldap\Models\Entry given, called in /var/www/html/app/Services/LdapAd.php on line 141 in /var/www/html/app/Services/LdapAd.php:299
Stack trace:
#0 /var/www/html/app/Services/LdapAd.php(141): App\Services\LdapAd->isLdapSync(Object(Adldap\Models\Entry))
#1 /var/www/html/app/Http/Controllers/Api/SettingsController.php(140): App\Services\LdapAd->ldapLogin('test_user', 'password123456')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Api\SettingsController->ldaptestlogin(Object(Illuminate\Http\Request), Object(App\Services\LdapAd))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('ldaptestlogin', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\SettingsController), 'ldaptestlogin')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/html/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/html/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/html/app/Http/Middleware/CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/html/app/Http/Middleware/NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /var/www/html/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}

``` 

**Additional context**
- This is running in a test environment with no real domain (just ip/port) and no ssl certificate
- Ldap connection is unencrypted
- was running 5.1.2 before (this was a fresh install) and then updated to 5.1.3. Issue happended on both version.

**Comment by snipe** [comment]
@uberbrady can you take a look when you get a moment?

**Comment by sonicnkt** [comment]
Im using [glauth](https://github.com/glauth/glauth) as ldap server so this should be easy to test but i cant get it to work...

**Comment by snipe** [comment]
Is this still happening with the latest version?

**Comment by sonicnkt** [comment]
> Is this still happening with the latest version?

Just updated my test docker environment to 5.1.4 and i am still having  the same issue.
Sync works but login test result in 500 error.

LDAP output looks fine,  bind success with the supplied credentials and Search OK.

**Comment by sonicnkt** [comment]
Just updated to 5.1.5. Had some issues with the db but after running the migrate script those were fixed. 

Sadly the "500 error" issue still persist and im getting the same error in `laravel.log`. 

This is the debug output of the ldap server (glauth):
```
16:56:32.876516 Bind ▶ DEBU 08a Bind request: bindDN: cn=search,ou=svcaccts,dc=example,dc=com, BaseDN: dc=example,dc=com, source: 172.20.0.3:50332
16:56:32.876611 Bind ▶ DEBU 08b Bind success as cn=search,ou=svcaccts,dc=example,dc=com from 172.20.0.3:50332
16:56:32.877134 Bind ▶ DEBU 08c Bind request: bindDN: cn=monty,ou=people,dc=example,dc=com, BaseDN: dc=example,dc=com, source: 172.20.0.3:50332
16:56:32.877179 Bind ▶ DEBU 08d Bind success as cn=monty,ou=people,dc=example,dc=com from 172.20.0.3:50332
16:56:32.877550 Bind ▶ DEBU 08e Bind request: bindDN: cn=search,ou=svcaccts,dc=example,dc=com, BaseDN: dc=example,dc=com, source: 172.20.0.3:50332
16:56:32.877590 Bind ▶ DEBU 08f Bind success as cn=search,ou=svcaccts,dc=example,dc=com from 172.20.0.3:50332
16:56:32.878206 Search ▶ DEBU 090 Search request as cn=search,ou=svcaccts,dc=example,dc=com from 172.20.0.3:50332 for (cn=monty)
16:56:32.878324 Search ▶ DEBU 091 AP: Search OK: (cn=monty)
```
search = ldap bind user
monty = my ldap test user who should be able to login

**Comment by tophitter** [comment]
I had the same issue, I've managed to get this working for now but not sure what the best fix would be for this but will provide what the issue was and what I did to fix it.

What i found to be the issue was the way the user DN is created it takes the Query input and the base DN and append them together but this would only work if added the full base DN to the user group no a parent DN to pick up all sub-accounts in other subgroups

e.g If your DN's is are simlier to these
cn=TestAccount1ou=Users,ou=SomeGroup,l=HQ,dc=test,dc=domain,dc=com
cn=TestAccount2ou=Users,ou=SomeGroup2,l=HQ,dc=test,dc=domain,dc=com
cn=TestAccount3ou=Users,ou=SomeGroup,l=2ndOffice,dc=test,dc=domain,dc=com

then the auto-generated bind in the system end up been "cn= dc=test,dc=domain,dc=com" which is not correct so will not allow login

the quick fix was to have the LDAP lookup the user and get the DN and use that as the login 

in file \app\Services\LdapAd.php in function ldapLogin

jsut before the line 
`        if (($this->ldap) && ($this->ldap->auth()->attempt($login_username, $password, $bind_as_user) === false)) {
`
I added 
```
//Tmp fix find user
  $search = $this->ldap->search()->where('uid','=',$login_username)->get();
  if(count($search) == 1){
      /** @var Entry $_tempUser */
      $_tempUser = $search[0];
      
      //Strip the cn= as this is auto added in the Auth call
      $login_username = ltrim($_tempUser->getDn(),"cn=");
      
      //Strip of the the base DN set as this is auto added in the auth caller
      if(isset($this->ldapConfig['base_dn']) && !empty($this->ldapConfig['base_dn'])) {
          $login_username = str_replace(",{$this->ldapConfig['base_dn']}", "",$login_username);
      }
  }
```

not sure what the best way this should be done, but i just need this to work at the time to allow staff to login again

**Comment by sonicnkt** [comment]
Not sure if this will fix my issue as i dont have any additional Groups or HQs like in your example.
If this was the issue it should show up in the ldap logs that a user could not bind...

Tho i will try to it on my setup just to make sure and report back again. Have to fix this with a docker setup so i have to mount the php file outside the container....

**Comment by sonicnkt** [comment]
Ok tried your fix but it did nothing for me. 
the Issue is with these lines of code in 

``` php
        // Should we sync the logged in user
        Log::debug('Attempting to find user in LDAP directory');
        $record = $this->ldap->search()->findBy($this->ldapSettings['ldap_username_field'], $username);
        if($record) {
            if ($this->isLdapSync($record)) {
                $this->syncUserLdapLogin($record, $password);
            }
        }
        else {
            throw new Exception('Unable to find user in LDAP directory!');
        }
``` 

`$record` is the user if want to login with `cn=monty,ou=people,dc=example,dc=com` but the functions `isLdapSync` can't handle this: 

```
[2021-05-31 09:18:37] production.ERROR: Argument 1 passed to App\Services\LdapAd::isLdapSync() must be an instance of Adldap\Models\User, instance of Adldap\Models\Entry given, called in /var/www/html/app/Services/LdapAd.php on line 148 {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Services\\LdapAd::isLdapSync() must be an instance of Adldap\\Models\\User, instance of Adldap\\Models\\Entry given, called in /var/www/html/app/Services/LdapAd.php on line 148 at /var/www/html/app/Services/LdapAd.php:308)
```
 
I have no experience with php but as far is i understand it this code/function should add the users to the local db if its not available yet. 

I then removed this code completely and got rid of the error but of course now it wont find the user in the local db and reports this back.
Manually running a ldap sync fixes this and now ldap login works without any flaws.

I can live with this for now as i just have to add a cron job that syncs the users from time to time but i really wonder why the original code wont work for me.

----

This was done using Version 5.1.5.

**Comment by ClaudioHoffmann** [comment]
Encountered the same issue, and narrowed it down to the name of the objectclass for user entries, at least in my case.

Typically, you'd specify the objectclass of user entries in the LDAP query filter. But in its attempt to simplify LDAP usage, Adldap2 additionally requires them to conform to a well-known schema. With Snipe-IT's additional distinction between regular LDAP and Active Directory, the library then expects user entries to either use the `inetorgperson` (from OpenLDAP) or `person` (from Active Directory) objectclass, and fails with this type error for anything else.

@uberbrady already realized that this design limits the typical flexibility expected from an LDAP implementation:

https://github.com/snipe/snipe-it/blob/b78e610ce3b4295fb4c56659976a5d5d26eeb6da/app/Services/LdapAdConfiguration.php#L167
https://github.com/snipe/snipe-it/blob/b78e610ce3b4295fb4c56659976a5d5d26eeb6da/app/Services/LdapAdConfiguration.php#L202

Without changing libraries, a workaround would be to add a new *User objectclass* input field to the settings page, and then implement a custom schema class, like this:

```php
class WorkaroundSchema extends \Adldap\Schemas\OpenLDAP
{
    protected string $objectClassPerson;

    public function __construct(string $objectClassPerson)
    {
      $this->objectClassPerson = $objectClassPerson;
    }

    public function objectClassPerson()
    {
        return $this->objectClassPerson;
    }
}

**Comment by uberbrady** [comment]
Snipe-IT v6 completely removes AdLdap2, which might help. We're hoping to have an RC (Release Candidate) out this week maybe?

**Comment by ClaudioHoffmann** [comment]
As of Snipe-IT v6.0.1, LDAP login works fine with custom schemas. This issue can probably be closed now.

**Comment by uberbrady** [comment]
That sounds great, thank you!
