### ISSUE TITLE
Assets Import History - SQL error 1054

### ISSUE THREAD

**Issue by aranar-pro** [grokability/snipe-it#9294]
#### Please confirm you have done the following before posting your bug report:

- [y] I have enabled debug mode 
- [y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
 500 error when selecting or searching by asset tag for any item that has been assigned to a user by Asset Import History.  Item does not appear checked out.  Item cannot be deleted (trashcan greyed out).

**To Reproduce**
1. Create a valid user: e.g. 'Jane' 'smith' 'jsmith@example.com'
2. Create valid Item with Asset tag e.g. '999999'
3. Create valid Asset History with Asset Tag, Checkout Date, Checkin Date, Name
e.g. 999999, 2014-05-12,2015-01-01,Jane Smith
4. Once history successfully imports, search for asset '999999' OR go to People, select "Jane Smith", History, and select imported item.
5.  500 server error from SQL query.

**Expected behavior**
Asset view should load (in either case).

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.12 and 5.1.3
 - OS: Windows Server 2019
 - Web Server: IIS 10
 - PHP Version 7.4

**Error Messages**
```
- SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.' in 'where clause' (SQL: select * from `assets` where `assets`.`` = 212 limit 1) (View: C:\inetpub\wwwroot\snipe-it\resources\views\hardware\view.blade.php)
- [2021-03-12 08:33:18] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.' in 'where clause' in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:64
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(64): PDO->prepare()
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): Doctrine\DBAL\Driver\PDOConnection->prepare()
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(338): Illuminate\Database\Connection->run()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2149): Illuminate\Database\Connection->select()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2137): Illuminate\Database\Query\Builder->runSelect()
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2609): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2138): Illuminate\Database\Query\Builder->onceWithColumns()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(537): Illuminate\Database\Query\Builder->get()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(521): Illuminate\Database\Eloquent\Builder->getModels()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Concerns\BuildsQueries.php(143): Illuminate\Database\Eloquent\Builder->get()
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsTo.php(83): Illuminate\Database\Eloquent\Builder->first()
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(429): Illuminate\Database\Eloquent\Relations\BelongsTo->getResults()
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(401): Illuminate\Database\Eloquent\Model->getRelationshipFromMethod()
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(333): Illuminate\Database\Eloquent\Model->getRelationValue()
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1527): Illuminate\Database\Eloquent\Model->getAttribute()
#17 C:\inetpub\wwwroot\snipe-it\storage\framework\views\c23e1f397081f08a96f5b7244cfad1110445da61.php(206): Illuminate\Database\Eloquent\Model->__get()
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('C:\\inetpub\\wwwr...')
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get()
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Http\Response.php(42): Illuminate\View\View->render()
#24 C:\inetpub\wwwroot\snipe-it\vendor\symfony\http-foundation\Response.php(205): Illuminate\Http\Response->setContent()
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(749): Symfony\Component\HttpFoundation\Response->__construct()
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Router::toResponse()
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Router->prepareResponse()
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#29 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle()
#31 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle()
#33 C:\inetpub\wwwroot\snipe-it\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#35 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle()
#37 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckLocale->handle()
#39 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#41 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#43 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#45 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then()
#47 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#48 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute()
#49 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
#50 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch()
#51 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#52 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#54 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle()
#56 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#58 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle()
#60 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle()
#62 C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
#64 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#66 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#68 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#69 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#70 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#71 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle()
#72 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#73 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#74 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#75 C:\inetpub\wwwroot\snipe-it\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#76 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.' in 'where clause' in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:66
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): Doctrine\DBAL\Driver\PDOConnection->prepare()
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(338): Illuminate\Database\Connection->run()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2149): Illuminate\Database\Connection->select()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2137): Illuminate\Database\Query\Builder->runSelect()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2609): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2138): Illuminate\Database\Query\Builder->onceWithColumns()
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(537): Illuminate\Database\Query\Builder->get()
#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(521): Illuminate\Database\Eloquent\Builder->getModels()
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Concerns\BuildsQueries.php(143): Illuminate\Database\Eloquent\Builder->get()
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsTo.php(83): Illuminate\Database\Eloquent\Builder->first()
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(429): Illuminate\Database\Eloquent\Relations\BelongsTo->getResults()
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(401): Illuminate\Database\Eloquent\Model->getRelationshipFromMethod()
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(333): Illuminate\Database\Eloquent\Model->getRelationValue()
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1527): Illuminate\Database\Eloquent\Model->getAttribute()
#16 C:\inetpub\wwwroot\snipe-it\storage\framework\views\c23e1f397081f08a96f5b7244cfad1110445da61.php(206): Illuminate\Database\Eloquent\Model->__get()
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('C:\\inetpub\\wwwr...')
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\CompilerEngine->get()
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Http\Response.php(42): Illuminate\View\View->render()
#23 C:\inetpub\wwwroot\snipe-it\vendor\symfony\http-foundation\Response.php(205): Illuminate\Http\Response->setContent()
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(749): Symfony\Component\HttpFoundation\Response->__construct()
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Router::toResponse()
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Router->prepareResponse()
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle()
#30 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle()
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#34 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle()
#36 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckLocale->handle()
#38 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#40 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#42 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#44 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then()
#46 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#47 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute()
#48 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
#49 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch()
#50 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#51 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#53 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle()
#55 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#57 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle()
#59 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle()
#61 C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
#63 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#65 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#67 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#69 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle()
#71 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#73 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#74 C:\inetpub\wwwroot\snipe-it\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#75 {main}

```
- Any errors that appear in your browser's error console.
- Get https://example.com/hardware/999 500 999:1
(actual URL and item ID removed).
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
History import is disabled on demo.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- See above.
- Include the output from `php -m` (this should display what modules you have enabled.)
```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
SPL
standard
tidy
tokenizer
wincache
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]

```
**Additional context**
- Is this a fresh install or an upgrade? 
Issue occurred on fresh install of 5.0.12 and persists in 5.1.3 (php upgrade.php).

- What OS and web server you're running Snipe-IT on
Windows Server 2019, php/IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual, upgraded to git install, no issues reported.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Loaded users through LDAP sync, SAML enabled.  Using mail attribute as username.

- Indicate whether or not you've manually edited any data directly in the database
no

- Deleting user and checkin all items, then restore user does make the object selectable again, this isn't practical because then history is incorrect.  It wouldn't be practical to manually fix all item states and associate users that were affected with history import.
- Comparing two objects in database (phpmyadmin), the only difference seems to be Assigned_to column.
- On Assets> Import History, assets that match to users populate the assigned_to column. Might relate to issue #9159
- I might try changing all assigned to columns back to null as suggested in above post, but I wanted to post this before making any changes to DB.

**Comment by aranar-pro** [comment]
`update assets set assigned_to=NULL where assigned_to IS NOT NULL;`
has got me up and running again as a workaround.  I might just record a few notes about the Asset Import History here if that's helpful.  
- Objects that have not been checked in (checkin date = null) are not displaying as currently checked out.
- Import history by first/last name doesn't work well with our username format e.g. jsmith23 or xx99yy (is "import by username" an option?). I'm going to test a workaround by formatting name as "j smith23" and see what happens.
Realizing this is my first bug report on Snipe-IT so just want to say "thank you" for the great project! :)

**Comment by aranar-pro** [comment]
Okay, so the issue seems to be that the importer doesn't seem to catch checkin date, assigned the user ID without assigning an assigned_type, and so it was left in limbo.
I'm setting up a fork and see if I can't help along the importer. I'm thinking:
1. checkin date should distinguish between expected and actual (so it can distinguish outstanding items from history)
2. assigned_type must be populated.  I'm fuzzy on the difference between App\Model\Users and \Assets but is it safe to assume if the import is checking for items assigned to users we can assign App\Model\Users and just warn that it's a limit of the importer?
3. allow items to be matched to raw user input.
I can scan the requested features and see if there are other Asset history import features being requested.
