### ISSUE TITLE
production.ERROR: SQLSTATE[28000] [1045] Access denied for user

### ISSUE THREAD

**Issue by x3inspire** [grokability/snipe-it#9396]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
production.ERROR: SQLSTATE[28000] [1045] Access denied for user 'felcrape_userdb'@'localhost' (using password: YES)

**Server (please complete the following information):**
 - Snipe-IT Version : v5.1.4 build 5886 (g9f3a8a43c)
 - Web Server: [e.g. Apache, IIS] : Litespeed
 - PHP Version : 7.3.27

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
`production.ERROR: SQLSTATE[28000] [1045] Access denied for user 'assetdata_userdb'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = assetdata_assetdemo and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'assetdata_userdb'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = assetdata_assetdemo and table_name = migrations and table_type = 'BASE TABLE') at /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)#29 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/assetdata/public_html/assetdemo/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 {main}

Next Illuminate\Database\QueryException: SQLSTATE[28000] [1045] Access denied for user 'assetdata_userdb'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = assetdata_assetdemo and table_name = migrations and table_type = 'BASE TABLE') in /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
Stack trace:
#0 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#2 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#3 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#4 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(590): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#5 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(91): Illuminate\Database\Migrations\Migrator->repositoryExists()
#6 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(63): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#7 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
#8 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#13 /home/assetdata/public_html/assetdemo/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /home/assetdata/public_html/assetdemo/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/assetdata/public_html/assetdemo/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/assetdata/public_html/assetdemo/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/assetdata/public_html/assetdemo/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/assetdata/public_html/assetdemo/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}  
`

**Additional context**
- Is this a fresh install or an upgrade? 
- Upgrade
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Using GIT

I can login, logout, add/edit item without any problem but i can see the error under log.
The problem is the log is display the different from my .env setting for username, database. I already changed the database name, db username, but the log keep display the old data setting.

**Comment by yosiasz** [comment]
Clear your cache. Things might be cached

**Comment by x3inspire** [comment]
> Clear your cache. Things might be cached

I clear my browser cache, still same. Any idea?

**Comment by yosiasz** [comment]
Snipeit cache not browser cache

**Comment by x3inspire** [comment]
> Snipeit cache not browser cache

Yes, i clear the cache using php artisan , also delete all file in bootstrap/cache folder but still same.

**Comment by snipe** [comment]
What version of MySQL are you using?

**Comment by x3inspire** [comment]
> What version of MySQL are you using?

10.3.28-MariaDB-log-cll-lve

**Comment by snipe** [comment]
> Yes, i clear the cache using php artisan

php artisan what? You'd want to clear your config cache, specifically: `php artisan config:clear` then `php artisan cache:clear` and `php artisan view:clear`

**Comment by x3inspire** [comment]
> > Yes, i clear the cache using php artisan
> 
> php artisan what? You'd want to clear your config cache, specifically: `php artisan config:clear` then `php artisan cache:clear` and `php artisan view:clear`

hi, yes what i mean is i use those code for clear the cache but result still same.

**Comment by snipe** [comment]
Hi there - sorry for the freakishly long time in responding here. This one fell off our radar :( 

Since the time this issue was opened, a ton of changes have been made in Snipe-IT. If you're still seeing this issue in the current version, please open a new issue that includes:

- Version of Snipe-IT you're running
- Specific errors you're seeing in the UI and/or in the browser console and error logs
- Steps to reproduce 
- Whether or not you can reproduce this on the demo (https://demo.snipeitapp.com)

Thanks - and again, sorry for the very late reply. We're doing some cleanup of old issues, so we're rediscovering some older things that didn't get addressed the first time around. 

![BeakerEmbarrased](https://github.com/user-attachments/assets/229984a9-95a3-44ca-a9e1-4111b08fa999)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
