### ISSUE TITLE
Cannot create events from API Rest

### ISSUE THREAD

**Issue by deivishome** [grokability/snipe-it#9400]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot call event creator on checkout/checkin as in web interface due to user, as no user is logged in because we authorized connection using Authorization + Bearer + API_KEY on request header, the instance of event class with function:
event(new CheckoutableCheckedOut($licenseSeat, $target, Auth::user(), request('note')));
On top of LicensesController.php i have already declared the following:
use App\Http\Controllers\Api\Auth;

**To Reproduce**
1. write into app/Http/Controllers/Api/LicensesController.php the function event(new CheckoutableCheckedOut($licenseSeat, $target, Auth::user(), request('note')));  inside a function and fill the data as if you were checking out a license.
As i set checkout/checkin capability for licenses i would like to have the event too, as it will be recorded when it was cheked also will make authomatic email sending
2. Call that function using API Rest
3. Have a look into snipe-it/storage/logs/laravel.log

**Expected behavior**
Create a new event from API Rest call.

**Screenshots**
![scsh-error_if_event_is_called_laravel](https://user-images.githubusercontent.com/36065681/113632401-98389480-965a-11eb-8bd4-2d6429961abc.PNG)
![scsh-error_if_event_is_called](https://user-images.githubusercontent.com/36065681/113632403-98d12b00-965a-11eb-844d-df5f5052195e.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.4
 - OS: Ubuntu 18.04 x64
 - Web Server: Apache 2.4.46
 - PHP Version 7.4

**Error Messages**
[2021-04-06 00:00:07] production.ERROR: Class 'App\Http\Controllers\Api\Auth' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Http\\Controllers\\Api\\Auth' not found at /var/www/snipe-it/app/Http/Controllers/Api/LicensesController.php:362)
[stacktrace]
#0 /var/www/snipe-it/app/Http/Controllers/Api/LicensesController.php(330): App\\Http\\Controllers\\Api\\LicensesController->checkoutToUser()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\LicensesController->checkout()
#2 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#6 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#9 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#11 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#12 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#13 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#14 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#15 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#16 /var/www/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#18 /var/www/snipe-it/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle()
#20 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/snipe-it/app/Http/Middleware/CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#24 /var/www/snipe-it/app/Http/Middleware/CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#26 /var/www/snipe-it/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#28 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#32 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#34 /var/www/snipe-it/app/Http/Middleware/NoSessionStore.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\NoSessionStore->handle()
#36 /var/www/snipe-it/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#38 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#41 /var/www/snipe-it/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#42 {main}

**Additional context**
-Fresh install, modified LicensesController.php from API folder to have checkout/checkin functionality, it needs as in web controller the event creator, but cannot use the same function as no user is logged in api, just authorized with API KEY

It would be nice to have the possiblity of event creation from API Rest, i will get a better aproach to web interface, for example on checking out or checking in assets/licenses/consumables, if you do it from web interface it generates the event as it uses logged in user, but from api rest it is not possible. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by finn8889** [comment]
Below are the logs from laravel.log when reproducing the issue:

2021-04-16 13:24:15] production.ERROR: htmlspecialchars() expects parameter 1 to be string, array given {"userId":16,"exception":"[object] (ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:251)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/snipei...', 251, Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(251): htmlspecialchars(Array, 3, 'UTF-8', true)
#2 /var/www/snipeit/app/Http/Controllers/ReportsController.php(568): e(Array)
#3 /var/www/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(112): App\\Http\\Controllers\\ReportsController->App\\Http\\Controllers\\{closure}()
#4 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(381): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#5 /var/www/snipeit/public/index.php(61): Symfony\\Component\\HttpFoundation\\Response->send()
#6 {main}
"}
[2021-04-16 13:47:39] production.ERROR: ErrorException: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:251
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/snipei...', 251, Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(251): htmlspecialchars(Array, 3, 'UTF-8', true)
#2 /var/www/snipeit/app/Http/Controllers/ReportsController.php(568): e(Array)
#3 /var/www/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(112): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#4 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(381): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/snipeit/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#6 {main}
[2021-04-16 13:47:39] production.ERROR: htmlspecialchars() expects parameter 1 to be string, array given {"userId":16,"exception":"[object] (ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:251)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/snipei...', 251, Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(251): htmlspecialchars(Array, 3, 'UTF-8', true)
#2 /var/www/snipeit/app/Http/Controllers/ReportsController.php(568): e(Array)
#3 /var/www/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(112): App\\Http\\Controllers\\ReportsController->App\\Http\\Controllers\\{closure}()
#4 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(381): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#5 /var/www/snipeit/public/index.php(61): Symfony\\Component\\HttpFoundation\\Response->send()
#6 {main}
"}

**Comment by snipe** [comment]
Hi there - sorry for the freakishly long time in responding here. This one fell off our radar :( 

Since the time this issue was opened, a ton of changes have been made in Snipe-IT. If you're still seeing this issue in the current version, please open a new issue that includes:

- Version of Snipe-IT you're running
- Specific errors you're seeing in the UI and/or in the browser console and error logs
- Steps to reproduce 
- Whether or not you can reproduce this on the demo (https://demo.snipeitapp.com)

Thanks - and again, sorry for the very late reply. We're doing some cleanup of old issues, so we're rediscovering some older things that didn't get addressed the first time around. 

![BeakerEmbarrased](https://github.com/user-attachments/assets/7a44966e-ed17-4987-bd58-cea38d072076)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
