### ISSUE TITLE
Custom Asset Report Error - ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by finn8889** [grokability/snipe-it#9444]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**When running the "Custom Asset Report", with any combination of tick options selected, once I select "Generate" it fails to load with chrome error "Hmmm… can't reach this page" and  "ERR_INVALID_RESPONSE"**. With Firefox, the page doesn't error but no file is generated. Debug mode when using Firefox doesn't show or generate any errors.

**To Reproduce**
1. Go to '...' **Reports - Custom Asset Reports** 
2. Click on '....' **Select Generate**

**Expected behavior**
**Excel file generated with data**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  **v5.1.4 build 5886**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu 20.04**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **7.2.31-1**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 20H2
 - Browser [e.g. chrome, safari] **Chrome, Firefox, Edge**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by finn8889** [comment]
Below are the logs from laravel.log when reproducing the issue:

2021-04-16 13:24:15] production.ERROR: htmlspecialchars() expects parameter 1 to be string, array given {"userId":16,"exception":"[object] (ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:251)
[stacktrace]
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/snipei...', 251, Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(251): htmlspecialchars(Array, 3, 'UTF-8', true)
#2 /var/www/snipeit/app/Http/Controllers/ReportsController.php(568): e(Array)
#3 /var/www/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(112): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#4 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(381): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/snipeit/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#6 {main}
"}
[2021-04-16 13:47:39] production.ERROR: ErrorException: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:251
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/snipei...', 251, Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(251): htmlspecialchars(Array, 3, 'UTF-8', true)
#2 /var/www/snipeit/app/Http/Controllers/ReportsController.php(568): e(Array)
#3 /var/www/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(112): App\Http\Controllers\ReportsController->App\Http\Controllers{closure}()
#4 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(381): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/snipeit/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#6 {main}
[2021-04-16 13:47:39] production.ERROR: htmlspecialchars() expects parameter 1 to be string, array given {"userId":16,"exception":"[object] (ErrorException(code: 0): htmlspecialchars() expects parameter 1 to be string, array given at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:251)
[stacktrace]
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'htmlspecialchar...', '/var/www/snipei...', 251, Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php(251): htmlspecialchars(Array, 3, 'UTF-8', true)
#2 /var/www/snipeit/app/Http/Controllers/ReportsController.php(568): e(Array)
#3 /var/www/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(112): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#4 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(381): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/snipeit/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#6 {main}
"}

**Comment by snipe** [comment]
Hi there - I know this is a pretty old issue, but I wanted to check and see if you ever got this resolved? If so, can you please close the ticket? If not, can you update us on what version of Snipe-IT you're currently using, so we can see if it's still an issue on latest?

:) Thanks!
